### ISSUE TITLE
NPE in FeedbackSessionsLogic.getSessionResultsForUser

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10688]
Received from the live server

R.von [04/Sep/2020:02:39:23 +0800] "GET /webapi/result?courseid=tresorier.lut-demo&fsname=9%20Sep%202020&intent=INSTRUCTOR_RESULT&questionid=Tutorial%20Group%202&frgroupbysection=EITHER HTTP/1.1" 500 314 https://teammatesv4.appspot.com/web/instructor/sessions/result?courseid=tresorier.lut-demo&fsname=9%20Sep%202020 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15" "teammatesv4.appspot.com" ms=423 cpu_ms=164 cpm_usd=3.5092e-8 loading_request=0 instance=00c61b117c73745fd6b519ae1271d25254cfcd39a7d961f26eb52f532e14b262324ba3 app_engine_release=1.9.71 trace_id=07ee672ee1ff6e35c43fd2a176f077b4

> Error Message: teammates.common.util.Logger severe: NullPointerException caught by WebApiServlet:
java.lang.NullPointerException
at teammates.logic.core.FeedbackSessionsLogic.getSessionResultsForUser(FeedbackSessionsLogic.java:653)
at teammates.logic.api.Logic.getSessionResultsForUser(Logic.java:1214)
at teammates.ui.webapi.action.GetSessionResultsAction.execute(GetSessionResultsAction.java:82)
at teammates.ui.webapi.action.WebApiServlet.invokeServlet(WebApiServlet.java:75)
at teammates.ui.webapi.action.WebApiServlet.doGet(WebApiServlet.java:42)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
at teammates.ui.webapi.action.OriginCheckFilter.doFilter(OriginCheckFilter.java:98)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:119)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:187)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:293)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
at org.eclipse.jetty.server.Server.handle(Server.java:539)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:213)
at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:761)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:724)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:694)
at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:880)
at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:270)
at java.lang.Thread.run(Thread.java:748)

**Comment by madanalogy** [comment]
Looks like the same underlying issue as #10650 (i.e. no null check when retrieving feedback session)

**Comment by wkurniawan07** [comment]
`questionid=Tutorial%20Group%202` this is a red flag. Question ID is not supposed to look like this.

**Comment by xpdavid** [comment]
The bug is here:

https://github.com/TEAMMATES/teammates/blob/master/src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts#L414-L433

Clearly their is a misalignment when passing the arguments

![image](https://user-images.githubusercontent.com/13977235/92292576-becefb00-eed2-11ea-91e1-23cd3605dfa5.png)

**Comment by wkurniawan07** [comment]
The wrong argument passed is as suspected. Another problem existing here is that null question is not well-handled in the back-end.
