### ISSUE TITLE
Student reports the submission is rejected due to unauthorized access error

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10748]
Error reported by student
![image](https://user-images.githubusercontent.com/1673303/94913651-34cb7f80-04dc-11eb-8cd5-4d7e4922fe0e.png)

From the logs, it looks like he attempted to submit near the deadline, but this is still a few minutes before the deadline.
He has joined the course already.

>Request received: [PUT] https://teammatesv4.appspot.com/webapi/responses, Params: {"questionid": "ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAwM2KwNwLDA", "intent": "STUDENT_SUBMISSION", "key": "9BAD2E2350CD80B71674EEFC744794145675FF2259E2F04870A30EC5B82646B13ED64269D605685BBEE8143E09B34C11B9D ...

>teammates.common.util.Logger warning: UnauthorizedAccessException caught by WebApiServlet:  (Logger.java:43)
teammates.common.exception.UnauthorizedAccessException: Login is required to access this feedback session
	at teammates.ui.webapi.BasicFeedbackSubmissionAction.checkAccessControlForStudentFeedbackSubmission(BasicFeedbackSubmissionAction.java:89)
	at teammates.ui.webapi.SubmitFeedbackResponsesAction.checkSpecificAccessControl(SubmitFeedbackResponsesAction.java:61)
	at teammates.ui.webapi.Action.checkAccessControl(Action.java:97)
	at teammates.ui.webapi.WebApiServlet.invokeServlet(WebApiServlet.java:73)
	at teammates.ui.webapi.WebApiServlet.doPut(WebApiServlet.java:52)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:710)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at teammates.ui.webapi.OriginCheckFilter.doFilter(OriginCheckFilter.java:98)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:119)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
	at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:187)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:293)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:213)
	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:781)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:744)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:714)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:900)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:270)
	at java.lang.Thread.run(Thread.java:748)

I'm trying to decipher what happened. Is it possible that we allow accessing submission form using the key (without logging in first) even if the student has joined already, but reject the submission because the student is not logged in?

Let me know if more information is needed.

**Comment by madanalogy** [comment]
> I'm trying to decipher what happened. Is it possible that we allow accessing submission form using the key (without logging in first) even if the student has joined already, but reject the submission because the student is not logged in?

This shouldn't be the case I think. Could he possibly have had this submission form open prior to registering, then registered in a new tab and logged out, then went back to the submission form? That's one scenario I can think of that might have caused the series of events you outlined.

**Comment by damithc** [comment]
> This shouldn't be the case I think. Could he possibly have had this submission form open prior to registering, then registered in a new tab and logged out, then went back to the submission form? That's one scenario I can think of that might have caused the series of events you outlined.

Unlikely. He joined the course the day before.

**Comment by madanalogy** [comment]
The error shown in the log should only occur if the registration key had been used to register a student but the student is not logged in:

https://github.com/TEAMMATES/teammates/blob/a5cad8417129abd6bb223b35e396047358d1c17e/src/main/java/teammates/ui/webapi/BasicFeedbackSubmissionAction.java#L87-L93

Since the student managed to reach the submission page, it means the frontend auth check should have passed, which means the student either (1) had registered using the key and is logged in, or (2) has not registered using the key

https://github.com/TEAMMATES/teammates/blob/a5cad8417129abd6bb223b35e396047358d1c17e/src/web/app/pages-session/session-submission-page/session-submission-page.component.ts#L160-L170

Since the outcome and error log indicates the presence of a key, it means the submission page was opened before the student was registered. That's the only explanation I can think of. Maybe @wkurniawan07 can help clarify if I missed anything.

**Comment by wkurniawan07** [comment]
> Could he possibly have had this submission form open prior to registering, then registered in a new tab and logged out, then went back to the submission form?

This is the only way the above can happen.

**Comment by damithc** [comment]
> > Could he possibly have had this submission form open prior to registering, then registered in a new tab and logged out, then went back to the submission form?
> 
> This is the only way the above can happen.

Is this slight variation also possible?

1. Already logged in to the matching Google account.
1. Opens the submission page using unique submission link.
1. Logout from Google in a different tab.
1. Submits responses.

**Comment by wkurniawan07** [comment]
The variation will lead into another kind of user error. At step (2), if the person is logged in to a matching Google account, s/he will be redirected to the logged in equivalent without the registration key. I'm not sure if logging out at step (3) will affect cookie correctness at another tab (it should be), but assuming it does, at step (4) it will send the responses without login information and without registration key, which is another kind of 403 error.

**Comment by damithc** [comment]
> The variation will lead into another kind of user error. At step (2), if the person is logged in to a matching Google account, s/he will be redirected to the logged in equivalent without the registration key. I'm not sure if logging out at step (3) will affect cookie correctness at another tab (it should be), but assuming it does, at step (4) it will send the responses without login information and without registration key, which is another kind of 403 error.

Got it. Thx.

**Comment by damithc** [comment]
Another student reported this today. 
![image](https://user-images.githubusercontent.com/1673303/94980724-fdea7d80-055e-11eb-9134-c7154c8ca70f.png)

The error looks the same but this student has not joined the course. The session is still open.

Two errors found in the log (for this session)

For some questions:

>teammates.common.util.Logger warning: UnauthorizedAccessException caught by WebApiServlet:  (Logger.java:43)
teammates.common.exception.UnauthorizedAccessException: The recipient is not a valid recipient of the question
	at teammates.ui.webapi.SubmitFeedbackResponsesAction.checkSpecificAccessControl(SubmitFeedbackResponsesAction.java:81)
	at teammates.ui.webapi.Action.checkAccessControl(Action.java:97)
	at teammates.ui.webapi.WebApiServlet.invokeServlet(WebApiServlet.java:73)
	at teammates.ui.webapi.WebApiServlet.doPut(WebApiServlet.java:52)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:710)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at teammates.ui.webapi.OriginCheckFilter.doFilter(OriginCheckFilter.java:98)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:119)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
	at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:187)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:293)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:213)
	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:781)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:744)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:714)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:900)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:270)
	at java.lang.Thread.run(Thread.java:748)

For other questions:
>teammates.common.util.Logger warning: UnauthorizedAccessException caught by WebApiServlet:  (Logger.java:43)
teammates.common.exception.UnauthorizedAccessException: The feedback session is not available for submission
	at teammates.ui.webapi.BasicFeedbackSubmissionAction.verifySessionOpenExceptForModeration(BasicFeedbackSubmissionAction.java:157)
	at teammates.ui.webapi.SubmitFeedbackResponsesAction.checkSpecificAccessControl(SubmitFeedbackResponsesAction.java:52)
	at teammates.ui.webapi.Action.checkAccessControl(Action.java:97)
	at teammates.ui.webapi.WebApiServlet.invokeServlet(WebApiServlet.java:73)
	at teammates.ui.webapi.WebApiServlet.doPut(WebApiServlet.java:52)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:710)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at teammates.ui.webapi.OriginCheckFilter.doFilter(OriginCheckFilter.java:98)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:119)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
	at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:187)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:293)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:213)
	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:781)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:744)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:714)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:900)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:270)
	at java.lang.Thread.run(Thread.java:748)

I tried the same link using an incognito window and it seemed to work (I submitted an empty submission form though)

A third student from a different university has reported a similar error. She seem to have joined the course but only after the error showed up. Her log shows only the second error message.

**Comment by damithc** [comment]
Ignore the above two cases for now. I'm trying to get more info.
One student replied that she was able to submit after she logged in using a Google account, whatever that means.
Also, it looks like they are from the same university. It's just that one student used an email address from a different university/organization for some reason.

**Comment by damithc** [comment]
The second student managed to submit using an incognito window. Will update if I receive more info or more similar error reports.

**Comment by wkurniawan07** [comment]
Closing due to lack of information
