### ISSUE TITLE
Instructors viewing results: 'Observers' cannot view session results

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10845]
It looks like instructors with 'Observer' permissions cannot view session results.

![image](https://user-images.githubusercontent.com/1673303/99620981-abf3ad80-2a61-11eb-9af4-2d69b4c4e199.png)

![image](https://user-images.githubusercontent.com/1673303/99621025-c463c800-2a61-11eb-8e21-4bbbbf812c78.png)

I only investigated one case (reported by the user). Not sure if this is a general problem or there's something special about this course. Let me know if I should dig deeper.

But this class has 600+ students and many observer users. We need to fix it soon.

From the log:
```
GET /webapi/questions?intent=INSTRUCTOR_RESULT&courseid=VBPFall2020&fsname=VBPFall2020

... 
teammates.common.util.Logger warning: UnauthorizedAccessException caught by WebApiServlet:  (Logger.java:43)
teammates.common.exception.UnauthorizedAccessException: You don't have submission privilege
	at teammates.logic.api.GateKeeper.verifySessionSubmissionPrivilegeForInstructor(GateKeeper.java:310)
	at teammates.ui.webapi.BasicFeedbackSubmissionAction.checkAccessControlForInstructorFeedbackSubmission(BasicFeedbackSubmissionAction.java:133)
	at teammates.ui.webapi.GetFeedbackQuestionsAction.checkSpecificAccessControl(GetFeedbackQuestionsAction.java:47)
	at teammates.ui.webapi.Action.checkAccessControl(Action.java:99)
	at teammates.ui.webapi.WebApiServlet.invokeServlet(WebApiServlet.java:91)
	at teammates.ui.webapi.WebApiServlet.doGet(WebApiServlet.java:42)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at teammates.ui.webapi.OriginCheckFilter.doFilter(OriginCheckFilter.java:98)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:119)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
	at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:187)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:293)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:213)
	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:781)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:744)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:714)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:900)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:270)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by madanalogy** [comment]
I thought this was fixed in #10613 :\

I'll be free starting Wednesday will take a look at it then if no one has. @damithc can try getting observers to export the results as csv in the meantime as a workaround

**Comment by damithc** [comment]
@niqiukun any thoughts? Is it something we can fix quickly?

**Comment by wkurniawan07** [comment]
> teammates.common.exception.UnauthorizedAccessException: You don't have submission privilege

This tells everything that's wrong.

**Comment by damithc** [comment]
Thanks for the investigation @wkurniawan07 
So, ticking this option should make the results accessible, right?
![image](https://user-images.githubusercontent.com/1673303/99813130-4519e580-2b82-11eb-9663-8235fe393826.png)
