### ISSUE TITLE
Datastore emulator: Tests fail to run to completion

### ISSUE THREAD

**Issue by jianhandev** [TEAMMATES/teammates#11024]
### Environment:
- `objectify-v6-migration` branch

### Set-up
**OfyHelper**
```
ObjectifyService.init(new ObjectifyFactory(
                DatastoreOptions.newBuilder()
                        .setHost("http://localhost:" + Config.APP_LOCALDATASTORE_PORT)
                        .setProjectId(Config.APP_ID)
                        .build()
                        .getService()
        ));
```
`build.properties`
```
app.id = teammates-jianhandev

...
app.localdatastore.port = 8484
```
### Steps taken
Ran `gcloud beta emulators datastore start --host-port=localhost:8484`
```
[datastore] API endpoint: http://localhost:8484
[datastore] If you are using a library that supports the DATASTORE_EMULATOR_HOST environment variable, run:
[datastore] 
[datastore]   export DATASTORE_EMULATOR_HOST=localhost:8484
[datastore] 
[datastore] Dev App Server is now running.
[datastore] 
[datastore] The previous line was printed for backwards compatibility only.
[datastore] If your tests rely on it to confirm emulator startup,
[datastore] please migrate to the emulator health check endpoint (/). Thank you!
[datastore] The health check endpoint for this emulator instance is http://localhost:8484/Mar 10, 2021 11:01:12 AM io.gapi.emulators.grpc.GrpcServer$3 operationComplete

```
Set the environment variables with `(gcloud beta emulators datastore env-init)`
```
export DATASTORE_DATASET=teammates-jianhandev
export DATASTORE_EMULATOR_HOST=localhost:8484
export DATASTORE_EMULATOR_HOST_PATH=localhost:8484/datastore
export DATASTORE_HOST=http://localhost:8484
export DATASTORE_PROJECT_ID=teammates-jianhandev
```

After passing the first 25 backend component tests, the tests get "stuck" and no longer proceeds. 

<img width="1229" alt="Screenshot 2021-03-10 at 11 27 42 AM" src="https://user-images.githubusercontent.com/59337195/110572057-a72f4280-8193-11eb-90ef-924cb908399c.png">

Log messages from datastore emulator:
```
[datastore] Mar 10, 2021 11:13:18 AM com.google.cloud.datastore.emulator.v1.DatastoreV1Emulator reset
[datastore] WARNING: Cannot reset a Datastore Emulator when it is storing data on disk.
[datastore] Re-run the emulator with the --testing flag to start the emulator in-memory.
[datastore] Mar 10, 2021 11:13:18 AM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
[datastore] WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
[datastore] java.lang.NullPointerException
[datastore] 	at io.netty.buffer.ByteBufUtil.utf8MaxBytes(ByteBufUtil.java:599)
[datastore] 	at io.netty.buffer.ByteBufUtil.writeUtf8(ByteBufUtil.java:498)
[datastore] 	at io.gapi.emulators.netty.SimpleHttpHandler.writeUtf8(SimpleHttpHandler.java:117)
[datastore] 	at io.gapi.emulators.netty.SimpleHttpHandler$1.onError(SimpleHttpHandler.java:83)
[datastore] 	at io.gapi.emulators.netty.ResetHandler.handleRequest(ResetHandler.java:58)
[datastore] 	at io.gapi.emulators.netty.SimpleHttpHandler.channelRead(SimpleHttpHandler.java:67)
[datastore] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[datastore] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[datastore] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[datastore] 	at io.gapi.emulators.netty.SimpleHttpHandler.channelRead(SimpleHttpHandler.java:102)
[datastore] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[datastore] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[datastore] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[datastore] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[datastore] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[datastore] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[datastore] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[datastore] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[datastore] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[datastore] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[datastore] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[datastore] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
[datastore] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
[datastore] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[datastore] 	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
[datastore] 	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353)
[datastore] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[datastore] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[datastore] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:474)
[datastore] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
[datastore] 	at java.lang.Thread.run(Thread.java:748)
[datastore] 
[datastore] Mar 10, 2021 11:13:42 AM com.google.cloud.datastore.emulator.impl.LocalDatastoreFileStub lambda$persist$7
[datastore] INFO: Time to persist datastore: 81 ms
```

**Comment by wkurniawan07** [comment]
This is exactly what I meant when I said fixing the port number to 8484 will cause trouble

**Comment by Derek-Hardy** [comment]
@jianhandev For component tests, there's already setup added in `BaseTestCaseWithObjectifyAccess`

```java
@BeforeSuite
public void setupLocalDatastoreHelper() throws IOException, InterruptedException {
    localDatastoreHelper = LocalDatastoreHelper.create(DB_CONSISTENCY, EMULATOR_PORT);
    localDatastoreHelper.start();
}
```

So you can run `./gradlew componentTests` directly without booting up datastore emulator in local.

**Comment by Derek-Hardy** [comment]
@wkurniawan07 then shall we remove `setupLocalDatastoreHelper` for all tests and give back the flexibility of local configuration?

**Comment by wkurniawan07** [comment]
> remove `setupLocalDatastoreHelper`

Why? It's a practical setup, as you can run component tests in one command instead of two. The only problem here is the port number used is the exact same as the port number used by local datastore emulator.
