### ISSUE TITLE
Deadline exceeded while doing StringHelper.encrypt

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11070]
v7.12.0

Received quite a few like these today. Not sure if `StringHelper.encrypt` is contributing to this problem or it's just coincidence that the timeout occurred while that method is executing.

>Error Message: teammates.common.util.Logger severe: DeadlineExceededException caught by WebApiServlet:
com.google.apphosting.api.DeadlineExceededException: This request (000001787beb7935) started at 2021/03/29 02:58:52.853 UTC and was still executing at 2021/03/29 02:59:56.558 UTC.
at com.sun.crypto.provider.AESCrypt.makeSessionKey(AESCrypt.java:594)
at com.sun.crypto.provider.AESCrypt.init(AESCrypt.java:93)
at com.sun.crypto.provider.ElectronicCodeBook.init(ElectronicCodeBook.java:94)
at com.sun.crypto.provider.CipherCore.init(CipherCore.java:592)
at com.sun.crypto.provider.CipherCore.init(CipherCore.java:620)
at com.sun.crypto.provider.AESCipher.engineInit(AESCipher.java:355)
at javax.crypto.Cipher.init(Cipher.java:1536)
at javax.crypto.Cipher.init(Cipher.java:1469)
at teammates.common.util.StringHelper.encrypt(StringHelper.java:127)
at teammates.ui.output.SessionResultsData$ResponseOutput$Builder.withResponseId(SessionResultsData.java:583)
at teammates.ui.output.SessionResultsData.buildSingleResponseForInstructor(SessionResultsData.java:258)
at teammates.ui.output.SessionResultsData.buildResponsesForInstructor(SessionResultsData.java:188)
at teammates.ui.output.SessionResultsData.lambda$initForInstructor$0(SessionResultsData.java:56)
at teammates.ui.output.SessionResultsData$$Lambda$111/1395735859.accept(Unknown Source)
at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
at teammates.ui.output.SessionResultsData.initForInstructor(SessionResultsData.java:50)
at teammates.ui.webapi.GetSessionResultsAction.execute(GetSessionResultsAction.java:84)

**Comment by moziliar** [comment]
A reasonable guess from @wkurniawan07 is that `GetSessionResultsAction` was processing too many responses and just so happened that the execution thread timeouts at that point. PR #11017 should be able to address this particular stack trace by upper bound the number of responses returned with section limit, i.e. a single fetch now can only get response from a section of users per question, effectively limiting the number of responses to 100 (same as section limit).

However, as discussed, this particular stack trace is recurring. The primary guess is that the course just exceed the threshold and by coincidence the request stops right at this point; we could just wait for the aforementioned PR to be merged and deployed and see if such error from instructor result workflow has been eradicated, after which we could apply the same frontend change to the student record page too.

**Comment by damithc** [comment]
Yup, let's wait until the ongoing fixes are applied. Although there were about 10 of those errors today, I suspect they are from the same session which is likely a 'heavy' session. As I didn't get any help request from the user, I assume the user succeeded in a subsequent try. 
Will monitor and update here if the recurrence rate goes up.

**Comment by wkurniawan07** [comment]
Closing as this is a false report from the very beginning.
