### ISSUE TITLE
StatisticsPerInstitute: Failing due to OutOfMemoryError

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11249]
V7

`teammates.client.scripts.statistics.StatisticsPerInstitute` which is used to generate statistics (run by admin monthly) has started failing with this error.

>[96400] Counting institutions stats by scanning student entities...
[96500] Counting institutions stats by scanning student entities...
[96600] Counting institutions stats by scanning student entities...
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at com.google.appengine.repackaged.com.google.io.protocol.ProtocolSink.<init>(ProtocolSink.java:49)
	at com.google.appengine.repackaged.com.google.io.protocol.ProtocolMessage.toProtocolSink(ProtocolMessage.java:330)
	at com.google.appengine.repackaged.com.google.io.protocol.ProtocolMessage.toByteArray(ProtocolMessage.java:357)
	at com.google.appengine.tools.remoteapi.RemoteDatastore.runQuery(RemoteDatastore.java:187)
	at com.google.appengine.tools.remoteapi.RemoteDatastore.handleRunQuery(RemoteDatastore.java:116)
	at com.google.appengine.tools.remoteapi.RemoteDatastore.handleDatastoreCall(RemoteDatastore.java:94)
	at com.google.appengine.tools.remoteapi.RemoteApiDelegate.makeDefaultSyncCall(RemoteApiDelegate.java:57)
	at com.google.appengine.tools.remoteapi.StandaloneRemoteApiDelegate.makeSyncCall(StandaloneRemoteApiDelegate.java:47)
	at com.google.appengine.tools.remoteapi.StandaloneRemoteApiDelegate$1.call(StandaloneRemoteApiDelegate.java:58)
	at com.google.appengine.tools.remoteapi.StandaloneRemoteApiDelegate$1.call(StandaloneRemoteApiDelegate.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

It fails after counting 96K student entities (happens at that exact point every time).

Not sure why it worked all this time but started failing this month. Perhaps caused by an SDK update?

Not urgent as this is not a critical feature.

**Comment by damithc** [comment]
I managed to work around this problem by using an old copy of the statistics (rather than generate statistics from the start, which was causing the error). Will close this for now.
