### ISSUE TITLE
FileNotFound Exception occurred during starting the server

### ISSUE THREAD

**Issue by Shubhojeetban** [TEAMMATES/teammates#11445]
I was trying to start the server then this exception occurred. The folder exploded-teammates is already created in build folder.
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by teammates.common.util.TzdbResourceZoneRulesProvider (file:/D:/Open%20Source%20Contribution/Teammates/teammates/build/exploded-teammates/WEB-INF/cl
asses/) to method java.time.zone.ZoneRules.readExternal(java.io.DataInput)
WARNING: Please consider reporting this to the maintainers of teammates.common.util.TzdbResourceZoneRulesProvider
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-10-14 16:59:16.088:INFO::main: Logging initialized @464ms to org.eclipse.jetty.util.log.StdErrLog
{"severity":"INFO","instanceId":"dev_server_instance_id","message":"Instance startup: dev_server_instance_id","event":"INSTANCE_LOG","instanceEvent":"STARTUP"}
2021-10-14 16:59:16.484:INFO:oejs.Server:main: jetty-9.4.39.v20210325; built: 2021-03-25T14:42:11.471Z; git: 9fc7ca5a922f2a37b84ec9dbc26a5168cee7e667; jvm 11.0.12+8-LTS-237
2021-10-14 16:59:16.799:WARN:oejw.WebInfConfiguration:main: Web application not found D:\Open%20Source%20Contribution\Teammates\teammates\build\exploded-teammates
2021-10-14 16:59:16.800:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@3646a422{/,null,STOPPED}{D:\Open%20Source%20Contribution\Teammates\teammates\build
\exploded-teammates}
java.io.FileNotFoundException: D:\Open%20Source%20Contribution\Teammates\teammates\build\exploded-teammates
        at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfiguration.java:670)
        at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:143)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:488)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:523)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.server.Server.start(Server.java:423)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.server.Server.doStart(Server.java:387)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at teammates.main.Application.main(Application.java:89)
2021-10-14 16:59:16.827:INFO:oejs.AbstractConnector:main: Started ServerConnector@16aa0a0a{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2021-10-14 16:59:16.829:INFO:oejs.Server:main: Started @1206ms
2021-10-14 16:59:16.845:INFO:teammates.main.Application$1:lifeCycleStarted:70: Using zone rules version 2021a
```

**Comment by moziliar** [comment]
@madanalogy Perhaps someone with windows can try to replicate and resolve?

**Comment by ypinhsuan** [comment]
I am guessing it might be because of the spaces in the filepath. Can you try removing the spaces for  `Open Source Contribution` folder?

**Comment by Shubhojeetban** [comment]
@ypinhsuan Thanks it worked. Can you tell me how I can log in to devServer and log in as an instructor?

I am getting this error while log in I am getting the error
![Screenshot (102)](https://user-images.githubusercontent.com/50337427/137585899-c0f79059-66a2-45bf-9858-0711861b0d2f.png)

**Comment by hhdqirui** [comment]
Hi @Shubhojeetban , you need to log in as admin first and then create an instructor using your email. Then you should be able to log in as an instructor.
