### ISSUE TITLE
Answering rubric questions: only one row can be clicked

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11778]
v8.14.1

Two users (I remember at least one more case reported sometime back) have reported that when answering a rubric question, an option from only one row can be clicked. Upon clicking another row, the previously clicked row is reset.

Example:

>At the bottom of the page, where we are supposed to choose 1 response in all 5 categories for each member, it will only allow me to choose 1 response out of all 5 categories for each member. So I'm only able to mark 1 evaluation per teammate, out of all 20 options. 

Example:

>For question 7: team ratings, I cannot select multiple lines.
Each time that I select a response on a line it deletes the response that it precedes it. 

The second user managed to submit eventually.

Co-incidentally, I found this error in the logs related to rubric questions, reported a whole bunch of times during the last month, may or may not be linked though.

> Error Message: NullPointerException caught by WebApiServlet: null
caused by java.lang.NullPointerException: null
at teammates.common.datatransfer.questions.FeedbackRubricQuestionDetails.lambda$validateResponsesDetails$2(FeedbackRubricQuestionDetails.java:166)
at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:533)
at teammates.common.datatransfer.questions.FeedbackRubricQuestionDetails.validateResponsesDetails(FeedbackRubricQuestionDetails.java:166)
at teammates.ui.webapi.SubmitFeedbackResponsesAction.execute(SubmitFeedbackResponsesAction.java:192)
at teammates.ui.webapi.SubmitFeedbackResponsesAction.execute(SubmitFeedbackResponsesAction.java:33)
at teammates.ui.servlets.WebApiServlet.invokeServlet(WebApiServlet.java:65)
at teammates.ui.servlets.WebApiServlet.doPut(WebApiServlet.java:48)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:710)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

Vast majority of students in the same session (of 118 students) as the above two submitted that question without any problem though, based on session results.

**Comment by wkurniawan07** [comment]
The second problem is known. It's stale front-end cache.

**Comment by wkurniawan07** [comment]
Also, if "the [second] user managed to submit eventually", high chance that the first problem is also stale front-end cache.

**Comment by wkurniawan07** [comment]
Close as there is no recent occurrence
