### ISSUE TITLE
Cannot start main.Application

### ISSUE THREAD

**Issue by yengah** [TEAMMATES/teammates#11965]
2022-10-08 04:06:24.691:INFO:oejs.Server:main: jetty-9.4.48.v20220622; built: 2022-06-21T20:42:25.880Z; git: 6b67c5719d1f4371b33655ff2d047d24e171e49a; jvm 11.0.10+8-LTS-162
2022-10-08 04:06:25.252:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=0ms
2022-10-08 04:06:25.260:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2022-10-08 04:06:25.275:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2022-10-08 04:06:25.275:INFO:oejs.session:main: No SessionScavenger set, using defaults
2022-10-08 04:06:25.278:INFO:oejs.session:main: node0 Scavenging every 660000ms
2022-10-08 04:06:25.312:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@766653e6{/,file:///C:/Users/yenga/IdeaProjects/teammates/build/classes/,AVAILABLE}{C:\Users\yenga\IdeaProjects\teammates\build\classes}
Oct. 08, 2022 4:06:25 AM teammates.common.util.Logger severe
SEVERE: teammates.main.Application$1:lifeCycleFailure:75: Instance failed to start/stop: dev_server_instance_id
Exception in thread "main" java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8080
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.server.Server.doStart(Server.java:401)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at teammates.main.Application.main(Application.java:89)
Caused by: java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:455)
	at java.base/sun.nio.ch.Net.bind(Net.java:447)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344)
	... 7 more

- **Commit SHA:** b47a59b78001caa1124257307c79b4bf569b3716
- **Operating System:** Windows 11
- **JDK Version:** JDK v11.0.10
- **Node.js Version:**  v16.17.1
- **Firefox / Chrome Version (if applicable):**  Version 106.0.5249.103 (Official Build) (64-bit)

**What I was trying to do / What I need help with**

I am trying to run main.Application. I believe this is the thick client.  

When I try running this from my development IDE, the above error occurs.

Can someone please help?

**Attempts to resolve the problem**

I have already run "appengineCloudSdkLogin" (gradle).

**Comment by zhaojj2209** [comment]
Not sure what IDE you're using and how you're "trying to run" it, but the backend server isn't meant to be started directly and we are not responsible for debugging your IDE. Please run `./gradlew serverRun` instead.

**Comment by yengah** [comment]
@zhaojj2209 Thanks.  Let me try.
