### ISSUE TITLE
Problem with BACK-END TEST SUITES

### ISSUE THREAD

**Issue by viniciusvieira00** [TEAMMATES/teammates#13067]
### Environment

- **Commit SHA:**735afbd2747465c9f2702c1e60f97dc32b5c6ebd
- **Operating System:**MacOS Apple Silicon 14.4.1
- **JDK Version: openjdk 11.0.22 2024-01-16**
- **Node.js Version:v20.10.0**

### Intention

So, Im trying to run the test suite, for the back-end, everythin in the front works properly, I followed every step on the documentation, using docker to run the containers, building the application on the front...

When I try to ./gradlew componentTests for the run of all component tests in the back-end, I receive 313 test successful, and just one with error, I will send over here
```bash
org.gradle.internal.serialize.PlaceholderException: Full-text search is not available.
        at teammates.storage.sqlsearch.SearchManager.performQuery(SearchManager.java:74)
        at teammates.storage.sqlsearch.AccountRequestSearchManager.searchAccountRequests(AccountRequestSearchManager.java:55)
        at teammates.storage.sqlapi.AccountRequestsDb.searchAccountRequestsInWholeSystem(AccountRequestsDb.java:162)
        at teammates.it.storage.sqlapi.AccountRequestsDbIT.testSqlInjectionSearchAccountRequestsInWholeSystem(AccountRequestsDbIT.java:204)
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.lang.reflect.Method.invoke(Method.java:578)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.testng.TestRunner.privateRun(TestRunner.java:806)
        at org.testng.TestRunner.run(TestRunner.java:601)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
        at org.testng.SuiteRunner.run(SuiteRunner.java:330)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
        at org.testng.TestNG.runSuites(TestNG.java:1099)
        at org.testng.TestNG.run(TestNG.java:1067)
        at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:146)
        at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:91)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.lang.reflect.Method.invoke(Method.java:578)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at jdk.proxy2.$Proxy5.stop(null:-1)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

component-tests > component-tests > teammates.it.storage.sqlapi.AccountRequestsDbIT > testSqlInjectionSearchAccountRequestsInWholeSystem FAILED
    teammates.common.exception.SearchServiceException at AccountRequestsDbIT.java:204
```

### Resolution Attempt

The only thing I suspected, but i couldn`t resolve too, is when i run the server, I just receive this:
<img width="326" alt="Screenshot 2024-04-19 at 23 20 39" src="https://github.com/TEAMMATES/teammates/assets/64455111/2cfb2d3c-87a9-4b38-8756-8f605ca09c15">

And the documentation said that: To start the server in the background, run the following command and wait until the task exits with a BUILD SUCCESSFUL:
So.. Im really thinking about this, so running again but now without the &, to run in the background I can see one deal.

<img width="1363" alt="Screenshot 2024-04-19 at 23 23 37" src="https://github.com/TEAMMATES/teammates/assets/64455111/b5f4b8ca-1ce4-4ef6-8c0d-279a9ec587a7">

Is been stuck on this...

Trying with debug mode to see what is happening

<img width="1354" alt="Screenshot 2024-04-19 at 23 24 58" src="https://github.com/TEAMMATES/teammates/assets/64455111/c5bd5fa7-ab3c-443c-9964-0131bc0a4038">

And been infinite waiting for this: 2024-04-19T23:24:24.323-0300 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.

Can see some errors, in the beginning of the last screenshot too..

```bash
2024-04-19T23:24:09.151-0300 [ERROR] [system.err] 2024-04-19 23:24:09.151:INFO :oejs.Server:main: jetty-10.0.13; built: 2022-12-07T20:13:20.134Z; git: 1c2636ea05c0ca8de1ffd6ca7f3a98ac084c766d; jvm 20.0.1+9-29
2024-04-19T23:24:09.339-0300 [ERROR] [system.err] 2024-04-19 23:24:09.339:INFO :oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2024-04-19T23:24:09.348-0300 [ERROR] [system.err] 2024-04-19 23:24:09.349:INFO :oejss.DefaultSessionIdManager:main: Session workerName=node0
2024-04-19T23:24:09.579-0300 [QUIET] [system.out] 2024-04-19 23:24:09.578:INFO:teammates.logic.core.LogicStarter:initializeDependencies:43: Initialized dependencies between logic classes
2024-04-19T23:24:09.584-0300 [QUIET] [system.out] 2024-04-19 23:24:09.584:INFO:teammates.sqllogic.core.LogicStarter:initializeDependencies:57: Initialized dependencies between logic classes
2024-04-19T23:24:09.609-0300 [ERROR] [system.err] 2024-04-19 23:24:09.609:WARN:HHH000505: Ignoring ServiceConfigurationError caught while trying to instantiate service 'interface org.hibernate.boot.registry.selector.StrategyRegistrationProvider'.
2024-04-19T23:24:09.619-0300 [ERROR] [system.err] 2024-04-19 23:24:09.620:INFO:HHH000412: Hibernate ORM core version 6.1.6.Final
2024-04-19T23:24:09.739-0300 [ERROR] [system.err] 2024-04-19 23:24:09.739:INFO:HHH000130: Instantiating explicit connection provider: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
2024-04-19T23:24:09.750-0300 [ERROR] [system.err] 2024-04-19 23:24:09.749:INFO :czh.HikariDataSource:main: HikariPool-1 - Starting...
2024-04-19T23:24:09.881-0300 [ERROR] [system.err] 2024-04-19 23:24:09.881:INFO :czh.HikariDataSource:main: HikariPool-1 - Start completed.
2024-04-19T23:24:09.900-0300 [ERROR] [system.err] 2024-04-19 23:24:09.900:INFO:HHH000400: Using dialect: org.hibernate.dialect.PostgreSQLDialect
2024-04-19T23:24:10.852-0300 [ERROR] [system.err] 2024-04-19 23:24:10.851:INFO :oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@2b72cb8a{/,file:///Users/viniciusvieira/Documents/Unb/2024.1/TS/AAE-1/teammates-forked-aae1/build/exploded-teammates/,AVAILABLE}{/Users/viniciusvieira/Documents/Unb/2024.1/TS/AAE-1/teammates-forked-aae1/build/exploded-teammates}
2024-04-19T23:24:10.859-0300 [ERROR] [system.err] 2024-04-19 23:24:10.859:INFO :oejs.AbstractConnector:main: Started ServerConnector@4cb2c100{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2024-04-19T23:24:10.860-0300 [ERROR] [system.err] 2024-04-19 23:24:10.860:INFO :oejs.Server:main: Started Server@1df82230{STARTING}[10.0.13,sto=0] @1899ms
```

_Originally posted by @viniciusvieira00 in https://github.com/TEAMMATES/teammates/discussions/13065_

**Comment by wkurniawan07** [comment]
Please do not duplicate discussion into issues.
