### ISSUE TITLE
Failing component test

### ISSUE THREAD

**Issue by weiquu** [TEAMMATES/teammates#13173]
The `SearchAccountRequestsActionTest` has suddenly started failing... did a quick check and couldn't find any recent code change that caused it. The tests are failing due to this error: `java.lang.IllegalArgumentException: UUID string too large`, from the same method. Example stack trace:
```
java.lang.IllegalArgumentException: UUID string too large
	at java.util.UUID.fromString(UUID.java:199)
	at teammates.storage.sqlsearch.AccountRequestSearchManager.getEntityFromDocument(AccountRequestSearchManager.java:39)
	at teammates.storage.sqlsearch.AccountRequestSearchManager.getEntityFromDocument(AccountRequestSearchManager.java:19)
	at teammates.storage.sqlsearch.SearchManager.convertDocumentToEntities(SearchManager.java:220)
	at teammates.storage.sqlsearch.AccountRequestSearchManager.searchAccountRequests(AccountRequestSearchManager.java:56)
	at teammates.storage.sqlapi.AccountRequestsDb.searchAccountRequestsInWholeSystem(AccountRequestsDb.java:187)
	at teammates.sqllogic.core.AccountRequestsLogic.searchAccountRequestsInWholeSystem(AccountRequestsLogic.java:182)
	at teammates.sqllogic.api.Logic.searchAccountRequestsInWholeSystem(Logic.java:1712)
	at teammates.ui.webapi.SearchAccountRequestsAction.execute(SearchAccountRequestsAction.java:24)
	at teammates.ui.webapi.SearchAccountRequestsAction.execute(SearchAccountRequestsAction.java:16)
	at teammates.ui.webapi.BaseActionTest.getJsonResult(BaseActionTest.java:571)
	at teammates.ui.webapi.BaseActionTest.getJsonResult(BaseActionTest.java:561)
	at teammates.ui.webapi.SearchAccountRequestsActionTest.testExecute_searchName_shouldSucceed(SearchAccountRequestsActionTest.java:94)
	...
```

Might be related to this PR, but needs more investigation: https://github.com/TEAMMATES/teammates/pull/12950. Could also be a setup issue on the database or data bundle side.

Putting as `p.High` since we should really ensure all tests are passing...

**Comment by jasonqiu212** [comment]
After further investigation, the `IllegalArgumentException` comes from Line 39 of `AccountRequestSearchManager.java`. 

```
UUID id = UUID.fromString((String) document.getFieldValue("id"));
```

`document.getFieldValue("id")` returns a String like `"instr1@course1.tmt%TEAMMATES Test Institute 1"`, which seems like a concatenation of email and institute. Since it's not a UUID, the above exception will be thrown.

**Comment by jasonqiu212** [comment]
Something odd I observed is that `SearchAccountRequestsActionTest` only fails when I run it on its own?

When I run all of the backend component tests together via `./gradlew componentTests --continue`, the test passes:

<img width="1142" alt="Image" src="https://github.com/user-attachments/assets/4faf9346-5722-4cf1-b3d8-7de2f8a1f73b" />

This may be related to why the component tests on the GitHub CI pass
