### ISSUE TITLE
Datastore Failure

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2682]
Datastore Failure

Request Path /page
Request Parameters {}
Stack Trace

javax.jdo.JDODataStoreException: Datastore Failure
    at org.datanucleus.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:304)
    at org.datanucleus.jdo.JDOPersistenceManager.getObjectById(JDOPersistenceManager.java:1676)
    at org.datanucleus.jdo.JDOPersistenceManager.getObjectById(JDOPersistenceManager.java:1767)
    at org.datanucleus.store.appengine.jdo.DatastoreJDOPersistenceManager.getObjectById(DatastoreJDOPersistenceManager.java:73)
    at teammates.storage.api.AccountsDb.getAccountEntity(AccountsDb.java:213)
    at teammates.storage.api.AccountsDb.getAccount(AccountsDb.java:93)
    at teammates.storage.api.AccountsDb.getAccount(AccountsDb.java:105)
    at teammates.logic.core.AccountsLogic.isAccountAnInstructor(AccountsLogic.java:73)
    at teammates.logic.api.GateKeeper.isInstructor(GateKeeper.java:451)
    at teammates.logic.api.GateKeeper.getCurrentUser(GateKeeper.java:69)
    at teammates.logic.api.Logic.getCurrentUser(Logic.java:139)
    at teammates.ui.controller.Action.getLogMessage(Action.java:386)
    at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:67)
    at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:37)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:142)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:254)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
    at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:480)
    at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:438)
    at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:445)
    at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:220)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:309)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:301)
    at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:442)
    at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:251)
    at java.lang.Thread.run(Thread.java:724)
NestedThrowablesStackTrace:
com.google.appengine.api.datastore.DatastoreFailureException: Unexpected failure
    at com.google.appengine.api.datastore.FutureHelper.getInternal(FutureHelper.java:74)
    at com.google.appengine.api.datastore.FutureHelper.quietGet(FutureHelper.java:58)
    at com.google.appengine.api.datastore.DatastoreServiceImpl.get(DatastoreServiceImpl.java:41)
    at org.datanucleus.store.appengine.RuntimeExceptionWrappingDatastoreService.get(RuntimeExceptionWrappingDatastoreService.java:56)
    at org.datanucleus.store.appengine.DatastorePersistenceHandler.get(DatastorePersistenceHandler.java:100)
    at org.datanucleus.store.appengine.DatastorePersistenceHandler.get(DatastorePersistenceHandler.java:112)
    at org.datanucleus.store.appengine.DatastorePersistenceHandler.fetchObject(DatastorePersistenceHandler.java:517)
    at org.datanucleus.state.JDOStateManagerImpl.validate(JDOStateManagerImpl.java:4263)
    at org.datanucleus.ObjectManagerImpl.findObject(ObjectManagerImpl.java:2444)
    at org.datanucleus.jdo.JDOPersistenceManager.getObjectById(JDOPersistenceManager.java:1671)
    at org.datanucleus.jdo.JDOPersistenceManager.getObjectById(JDOPersistenceManager.java:1767)
    at org.datanucleus.store.appengine.jdo.DatastoreJDOPersistenceManager.getObjectById(DatastoreJDOPersistenceManager.java:73)
    at teammates.storage.api.AccountsDb.getAccountEntity(AccountsDb.java:213)
    at teammates.storage.api.AccountsDb.getAccount(AccountsDb.java:93)
    at teammates.storage.api.AccountsDb.getAccount(AccountsDb.java:105)
    at teammates.logic.core.AccountsLogic.isAccountAnInstructor(AccountsLogic.java:73)
    at teammates.logic.api.GateKeeper.isInstructor(GateKeeper.java:451)
    at teammates.logic.api.GateKeeper.getCurrentUser(GateKeeper.java:69)
    at teammates.logic.api.Logic.getCurrentUser(Logic.java:139)
    at teammates.ui.controller.Action.getLogMessage(Action.java:386)
    at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:67)
    at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:37)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:142)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
1. Error Type: ERROR
   Error Message: 
   at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
   at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
   at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
   at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
   at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
   at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
   at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
   at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
   at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
   at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:254)
   at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
   at org.mortbay.jetty.Server.handle(Server.java:326)
   at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
   at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
   at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
   at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
   at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
   at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:480)
   at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:438)
   at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:445)
   at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:220)
   at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:309)
   at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:301)
   at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:442)
   at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:251)
   at java.lang.Thread.run(Thread.java:724)
   Caused by: java.lang.InterruptedException
   at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1038)
   at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1326)
   at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:268)
   at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
   at com.google.appengine.tools.development.TimedFuture.get(TimedFuture.java:42)
   at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:63)
   at com.google.appengine.tools.appstats.RecordingFuture.get(RecordingFuture.java:108)
   at com.google.appengine.tools.appstats.RecordingFuture$ExtendedFuture.get(RecordingFuture.java:49)
   at com.google.appengine.tools.appstats.RecordingFuture.get(RecordingFuture.java:108)
   at com.google.appengine.tools.appstats.RecordingFuture$ExtendedFuture.get(RecordingFuture.java:49)
   at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:88)
   at com.google.appengine.api.datastore.AsyncDatastoreServiceImpl$5.getFutureWithOptionalTimeout(AsyncDatastoreServiceImpl.java:292)
   at com.google.appengine.api.datastore.AsyncDatastoreServiceImpl$5.aggregate(AsyncDatastoreServiceImpl.java:264)
   at com.google.appengine.api.datastore.AsyncDatastoreServiceImpl$5.get(AsyncDatastoreServiceImpl.java:235)
   at com.google.appengine.api.datastore.AsyncDatastoreServiceImpl$5.get(AsyncDatastoreServiceImpl.java:224)
   at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:88)
   at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:88)
   at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:88)
   at com.google.appengine.api.datastore.FutureHelper.getInternal(FutureHelper.java:71)
   ... 59 more

|||/page/instructorHomePage

**Comment by Femina** [comment]
javax.jdo.JDODataStoreException: Datastore Failure

Any update on this issue? We are facing consistently... It affects our business a lot!!!

**Comment by damithc** [comment]
@Femina Sorry, we completely missed your comment. Are you a TEAMMATES user?

**Comment by Femina** [comment]
@damithc NO. I am not. But I love ... I am a general GAE user who is experiencing an unexpected datastore failures often. If you have any idea help me on it.

**Comment by damithc** [comment]
@Femina no solution at the moment Femina. We don't encounter it that frequently.

**Comment by damithc** [comment]
Old issue. Although not resolved, putting it down to intermittent failures general distributed databases and closing the issue.
