### ISSUE TITLE
Submit responses: fix 'null feedback recipientEmail' error

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2983]
Error received:
```
Null feedback recipientEmail

Request Path /page 
Request Parameters {studentemail::abc@student.manchester.ac.uk, responsetext-2-5::3, responsetext-2-4::4, responsetext-2-3::3, responsetext-2-2::4, responsetext-2-6::4, responsetext-2-1::4, responsetext-2-0::3, numscalemax-5-2::5, responsetext-6-0::, questiontype-3::NUMSCALE, numscalemax-5-1::5, responsetext-6-1::, questiontype-4::NUMSCALE, numscalemax-5-4::5, questiontype-1::NUMSCALE, numscalemax-5-3::5, questiontype-2::NUMSCALE, responsetext-6-4::, responsetext-6-5::, numscalemax-5-0::5, responsetext-6-2::, responsetext-6-3::, responsetext-4-1::5, responsetext-4-0::4, numscalemax-4-1::5, responsetext-4-3::3, numscalemax-4-0::5, responsetext-4-2::3, numscalemax-4-3::5, responsetext-4-5::3, numscalemax-4-2::5, responsetext-4-4::4, questiontype-5::NUMSCALE, numscalemax-4-5::5, numscalemax-4-4::5, questiontype-6::TEXT, responsetext-4-6::4, numscalemax-4-6::5, numscalemin-5-3::0, numscalemin-5-4::0, numscalemin-5-5::0, numscalemin-5-6::0, numscalemin-5-0::0, numscalemin-5-1::0, numscalemin-5-2::0, numscalemax-5-5::5, numscalemax-5-6::5, courseid::CHEN30012, numscalemax-2-3::5, numscalestep-3-3::1, numscalemax-2-2::5, numscalestep-3-4::1, numscalestep-3-5::1, numscalemax-2-1::5, numscalestep-3-6::1, numscalemax-2-0::5, numscalemin-1-6::0, numscalemax-2-6::5, numscalestep-3-0::1, numscalemin-1-5::0, numscalemax-2-5::5, numscalestep-3-1::1, numscalemin-1-4::0, numscalestep-3-2::1, numscalemax-2-4::5, numscalemin-1-3::0, numscalemax-3-6::5, numscalemin-1-2::0, questionresponsetotal-6::7, numscalemax-3-5::5, numscalemin-1-1::0, questionresponsetotal-5::7, numscalemax-3-4::5, numscalemin-1-0::0, numscalemax-3-3::5, questionresponsetotal-4::7, questionresponsetotal-3::7, numscalemax-3-2::5, questionresponsetotal-2::7, numscalemax-3-1::5, numscalemax-3-0::5, questionresponsetotal-1::7, fsname::Design project peer assessment week 3, questionid-2::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgKS4uIMKDA, questionid-3::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgKSf6YYKDA, numscalemin-3-0::0, numscalemax-1-5::5, numscalestep-1-0::1, numscalemax-1-6::5, questionid-1::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgKSR9ocKDA, numscalemax-1-3::5, numscalemax-1-4::5, numscalemax-1-1::5, numscalemax-1-2::5, numscalestep-1-6::1, numscalemax-1-0::5, numscalestep-1-5::1, numscalemin-3-5::0, numscalemin-3-6::0, numscalestep-1-2::1, questionid-6::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgKSR6ZYKDA, numscalemin-3-3::0, numscalestep-1-1::1, numscalemin-3-4::0, numscalemin-3-1::0, questionid-4::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgKSD1ZQKDA, numscalestep-1-4::1, questionid-5::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgKSDi40KDA, numscalestep-1-3::1, numscalemin-3-2::0, numscalestep-5-0::1, numscalestep-5-4::1, numscalestep-5-3::1, numscalestep-5-2::1, numscalestep-5-1::1, numscalestep-4-5::1, numscalestep-4-4::1, numscalestep-4-3::1, numscalestep-4-2::1, numscalestep-4-1::1, numscalestep-4-0::1, key::ag1zfnRlYW1tYXRlc3Y0chQLEgdTdHVkZW50GICAgKS94YMJDA, numscalestep-4-6::1, responsetext-6-6::, numscalestep-5-5::1, numscalestep-5-6::1, clientAction::578.click, responsetext-3-0::4, responsetext-1-0::4, responsetext-1-1::4, responsetext-1-2::4, responsetext-1-3::4, responsetext-3-5::4, responsetext-1-4::4, responsetext-3-6::4, responsetext-1-5::4, responsetext-1-6::4, responsetext-3-1::4, responsetext-3-2::4, responsetext-3-3::4, responsetext-3-4::4, responsetext-5-4::4, responsetext-5-3::3, responsetext-5-6::4, responsetext-5-5::3, responsetext-5-0::3, responsetext-5-2::4, responsetext-5-1::4, numscalemin-2-4::0, numscalemin-2-5::0, numscalemin-2-2::0, numscalemin-2-3::0, numscalemin-2-6::0, numscalemin-4-1::0, numscalemin-4-0::0, numscalemin-4-3::0, numscalemin-4-2::0, numscalemin-2-0::0, numscalemin-4-5::0, numscalemin-2-1::0, numscalemin-4-4::0, numscalemin-4-6::0, numscalestep-2-0::1, numscalestep-2-1::1, numscalestep-2-2::1, numscalestep-2-3::1, numscalestep-2-4::1, numscalestep-2-5::1, numscalestep-2-6::1} 
Stack Trace

java.lang.AssertionError: Null feedback recipientEmail
    at teammates.common.util.Assumption.fail(Assumption.java:58)
    at teammates.common.util.Assumption.assertTrue(Assumption.java:27)
    at teammates.common.util.Assumption.assertNotNull(Assumption.java:254)
    at teammates.ui.controller.FeedbackSubmissionEditSaveAction.extractFeedbackResponseData(FeedbackSubmissionEditSaveAction.java:191)
    at teammates.ui.controller.FeedbackSubmissionEditSaveAction.execute(FeedbackSubmissionEditSaveAction.java:93)
    at teammates.ui.controller.Action.executeAndPostProcess(Action.java:328)
    at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:58)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:142)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:254)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
    at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:484)
    at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:438)
    at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:445)
    at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:220)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:309)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:301)
    at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:442)
    at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:251)
    at java.lang.Thread.run(Thread.java:724)
```

**Comment by damithc** [comment]
Happened again. Anything we can do?

**Comment by LowWeiLin** [comment]
Can we find what browser is being used? The request parameters are strange. All recipient emails are missing, and there is this clientAction parameter which i have not seen before.

**Comment by damithc** [comment]
2015-02-11 22:00:09.693 /page/studentFeedbackSubmissionEditSave 302 1654ms 0kb UCWEB/2.0 (MIDP-2.0; U; Adr 4.3; en-US; GT-I9300) U2/1.0.0 UCBrowser/9.8.0.534 U2/1.0.0 Mobile module=default version=5-35
168.235.196.242 - - [11/Feb/2015:06:00:09 -0800] "POST /page/studentFeedbackSubmissionEditSave HTTP/1.1" 302 117 "https://teammatesv4.appspot.com/page/studentFeedbackSubmissionEditPage" "UCWEB/2.0 (MIDP-2.0; U; Adr 4.3; en-US; GT-I9300) U2/1.0.0 UCBrowser/9.8.0.534 U2/1.0.0 Mobile" "teammatesv4.appspot.com" ms=1654 cpu_ms=770 cpm_usd=0.000949 app_engine_release=1.9.18 instance=00c61b117cce55ef0cda35fcb223f86d16fb4a24

**Comment by damithc** [comment]
Another case:

/page/studentFeedbackSubmissionEditSave 302 772ms 0kb UCWEB/2.0 (MIDP-2.0; U; Adr 4.4.2; id; Xperia_Z) U2/1.0.0 UCBrowser/9.8.0.534 U2/1.0.0 Mobile module=default version=5-36
8.37.225.71 - - [18/Feb/2015:05:27:15 -0800] "POST /page/studentFeedbackSubmissionEditSave HTTP/1.1" 302 117 "https://teammatesv4.appspot.com/page/studentFeedbackSubmissionEditPage" "UCWEB/2.0 (MIDP-2.0; U; Adr 4.4.2; id; Xperia_Z) U2/1.0.0 UCBrowser/9.8.0.534 U2/1.0.0 Mobile" "teammatesv4.appspot.com" ms=773 cpu_ms=373 cpm_usd=0.000619 app_engine_release=1.9.17 instance=00c61b117c8e26fb51da9e4a34a3f2351a4ec129
I 2015-02-18 21:27:15.154
teammates.ui.controller.ControllerServlet doPost: Request received : https://teammatesv4.appspot.com/page/studentFeedbackSubmissionEditSave:{questiontype-3::TEXT, questiontype-1::CONTRIB, questiontype-2::TEXT, responsetext-3-0::Good job!, responsetext-1-0::110, responsetext-1-1::120, responsetext-1-2::-101, responsetext-3-5::Good job!, responsetext-1-3::160, responsetext-1-4::120, responsetext-3-6::Good job!, responsetext-1-5::110, responsetext-1-6::140, responsetext-1-7::150, responsetext-3-1::Good job!, responsetext-3-2::Good job!, responsetext-3-3::Good job!, responsetext-3-4::Good job!, courseid::LMP15_Music, key::ag1zfnRlYW1tYXRlc3Y0chQLEgdTdHVkZW50GICAgJTSgYEKDA, studentemail::d.hanung@sbm-itb.ac.id, questionresponsetotal-3::7, questionresponsetotal-2::1, questionresponsetotal-1::8, fsname::Peer-Evaluation 1 Music Team, questionid-2::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgJS2_eEIDA, questionid-3::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgJT4nNcKDA, clientAction::552.click, questionid-1::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgJT4yOYKDA, responsetext-2-0::Keep our spirit in top, work together, cause together is better}
I 2015-02-18 21:27:15.154
teammates.ui.controller.ControllerServlet doPost: User agent : UCWEB/2.0 (MIDP-2.0; U; Adr 4.4.2; id; Xperia_Z) U2/1.0.0 UCBrowser/9.8.0.534 U2/1.0.0 Mobile
I 2015-02-18 21:27:15.154
teammates.ui.controller.ActionFactory getAction: URL received :https://teammatesv4.appspot.com/page/studentFeedbackSubmissionEditSave
I 2015-02-18 21:27:15.300
teammates.storage.api.InstructorsDb getInstructorForEmail: Trying to get non-existent Instructor: LMP15_Music/d.hanung@sbm-itb.ac.id
I 2015-02-18 21:27:15.376
teammates.storage.api.InstructorsDb getInstructorForEmail: Trying to get non-existent Instructor: LMP15_Music/d.hanung@sbm-itb.ac.id
I 2015-02-18 21:27:15.466
teammates.storage.api.InstructorsDb getInstructorForEmail: Trying to get non-existent Instructor: LMP15_Music/d.hanung@sbm-itb.ac.id
I 2015-02-18 21:27:15.595
teammates.logic.core.Emails sendEmail: [Email sent]to=teammates@comp.nus.edu.sg|from=TEAMMATES Admin <Admin@teammatesv4.appspotmail.com>|subject=TEAMMATES (5.36): New System Exception: Null feedback recipientEmail
E 2015-02-18 21:27:15.877
teammates.logic.core.Emails sendErrorReport: Sent crash report: [Email sent]to=teammates@comp.nus.edu.sg|from=TEAMMATES Admin <Admin@teammatesv4.appspotmail.com>|subject=TEAMMATES (5.36): New System Exception: Null feedback recipientEmail
E 2015-02-18 21:27:15.877
teammates.ui.controller.ControllerServlet doPost: TEAMMATESLOG|||page|||System Error Report|||true|||Unknown|||Unknown|||Unknown|||Unknown|||<span class="text-danger">TEAMMATES (5.36): New System Exception: Null feedback recipientEmail</span><br><a href="#" onclick="showHideErrorMessage('error4710646');">Show/Hide Details >></a><br><span id="error4710646" style="display: none;"><b>Error Message</b> 
<br/> 
<pre><code> 
Null feedback recipientEmail 
</code></pre> 
<br/> 
 
<b>Request Path</b> 
/page 
<br/> 
 
<b>Request Parameters</b> 
{questiontype-3::TEXT, questiontype-1::CONTRIB, questiontype-2::TEXT, responsetext-3-0::Good job!, responsetext-1-0::110, responsetext-1-1::120, responsetext-1-2::-101, responsetext-3-5::Good job!, responsetext-1-3::160, responsetext-1-4::120, responsetext-3-6::Good job!, responsetext-1-5::110, responsetext-1-6::140, responsetext-1-7::150, responsetext-3-1::Good job!, responsetext-3-2::Good job!, responsetext-3-3::Good job!, responsetext-3-4::Good job!, courseid::LMP15_Music, key::ag1zfnRlYW1tYXRlc3Y0chQLEgdTdHVkZW50GICAgJTSgYEKDA, studentemail::d.hanung@sbm-itb.ac.id, questionresponsetotal-3::7, questionresponsetotal-2::1, questionresponsetotal-1::8, fsname::Peer-Evaluation 1 Music Team, questionid-2::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgJS2_eEIDA, questionid-3::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgJT4nNcKDA, clientAction::552.click, questionid-1::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgJT4yOYKDA, responsetext-2-0::Keep our spirit in top, work together, cause together is better} 
<br/> 
 
<b>Stack Trace</b> 
<pre><code> 

java.lang.AssertionError: Null feedback recipientEmail
	at teammates.common.util.Assumption.fail(Assumption.java:58)
	at teammates.common.util.Assumption.assertTrue(Assumption.java:27)
	at teammates.common.util.Assumption.assertNotNull(Assumption.java:254)
	at teammates.ui.controller.FeedbackSubmissionEditSaveAction.extractFeedbackResponseData(FeedbackSubmissionEditSaveAction.java:191)
	at teammates.ui.controller.FeedbackSubmissionEditSaveAction.execute(FeedbackSubmissionEditSaveAction.java:93)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:328)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:58)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:142)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:254)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:484)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:438)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:445)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:220)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:309)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:301)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:442)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:251)
	at java.lang.Thread.run(Thread.java:724)
 
</code></pre> 
 
 
</span>|||/page/studentFeedbackSubmissionEditSave

**Comment by damithc** [comment]
Another one:
teammates.ui.controller.ControllerServlet doPost: User agent : UCWEB/2.0 (MIDP-2.0; U; Adr 4.4.2; id; Xperia_Z) U2/1.0.0 UCBrowser/9.8.0.534 U2/1.0.0 Mobile

**Comment by kanghj** [comment]
This can be replicated using UC browser mini in speed mode, which is on by default. On speed mode, US browser tries to speed up browsing by "compressing web pages on the server, and pre-loading pages automatically". The error happens on questions with recipient type to all students, and the feedback giver is allowed to select which student to give a response to. The browser submits the form on its own, without the recipient data, on the second time the user selects a recipient. I am still trying to figure out why this is happening.

**Comment by damithc** [comment]
In the worst case we may have to detect the browser and inform that it is 'not supported' :-p

**Comment by damithc** [comment]
Got a few more of these.

**Comment by damithc** [comment]
Old issue. closing.

**Comment by damithc** [comment]
Still getting these. Reopening.



Error Message: teammates.common.util.Logger severe: TEAMMATESLOG|||page|||System Error Report|||true|||Unknown|||Unknown|||Unknown|||Unknown|||TEAMMATES (5.95.02): New System Exception: Null feedback recipientEmail
Show/Hide Details >>
Error Message 

        Null feedback recipientEmail

    



Actual user 

Not logged in 



Request Method 

POST 



User Agent 

Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 



Request Url 

https://teammatesv4.appspot.com/page/studentFeedbackSubmissionEditSave 



Request Path 

/page 



Request Parameters 

{questiontype-3::TEXT, questiontype-4::TEXT, questiontype-1::CONTRIB, responsetext-3-0::

Gets work done (on time & accurate). Requires minimal direction and guidance. Effective speaker (during presentation). Team player. Positive attitude.

, questiontype-2::TEXT, responsetext-1-0::100, responsetext-1-1::100, responsetext-1-2::100, responsetext-1-3::100, responsetext-4-0::
Able to work as an effective team. Focused on solutions to project, rather than complaining. Initative was taken by all. Communication was effective. Able to work out differences related to the project in a professional manner. 

, responsetext-3-1::
Takes initative. Communicates effectively. Puts in exra effort, without being asked. Creative. Team player. Has leadership potential. Positive attitude.

, responsetext-3-2::
Gets work done (on time & accurate). Team player. Good Communication. Works with minimal guidance. Positive attitude.

, questiontype-5::TEXT, responsetext-5-0::
Effective speaker/presenter. Doer; got work done with minimal guidance. 

, responsetext-5-2::, responserecipient-1-3::tgraven@liberty.edu, courseid::ENGR-381-002-201720, responserecipient-1-1::cphan1@liberty.edu, key::0F1780ED98D4DB1E893CFB7E0B4BAB40D5B2824A4B00352536FC302EEFA81A465E57EAC3A327F7E011528824FA327D1D13B7DCBA57FD135AAF65889F7abc, responserecipient-1-2::jwford1@liberty.edu, studentemail::jwford1@liberty.edu, responserecipient-2-0::jwford1@liberty.edu, responserecipient-1-0::bmelton1@liberty.edu, sendsubmissionemail::on, questionresponsetotal-5::3, responserecipient-4-0::P1_Team_06, questionresponsetotal-4::1, questionresponsetotal-3::3, questionresponsetotal-2::1, responserecipient-5-0::bmelton1@liberty.edu, questionresponsetotal-1::4, fsname::Team peer evaluation #1, questionid-2::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgKPFqZwJDA, questionid-3::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgKOO8dgKDA, questionid-1::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgKOj7IQKDA, responserecipient-3-0::bmelton1@liberty.edu, responserecipient-3-1::cphan1@liberty.edu, responserecipient-3-2::tgraven@liberty.edu, responsetext-2-0::
Arranged meetings. assigned management portion of project. Edited paper. 

, questionid-4::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgOPolokJDA, questionid-5::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgKP2064KDA} 


Stack Trace 



java.lang.AssertionError: Null feedback recipientEmail
	at teammates.common.util.Assumption.fail(Assumption.java:61)
	at teammates.common.util.Assumption.assertTrue(Assumption.java:29)
	at teammates.common.util.Assumption.assertNotNull(Assumption.java:271)
	at teammates.ui.controller.FeedbackSubmissionEditSaveAction.extractFeedbackResponseData(FeedbackSubmissionEditSaveAction.java:293)
	at teammates.ui.controller.FeedbackSubmissionEditSaveAction.execute(FeedbackSubmissionEditSaveAction.java:111)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:365)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:66)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:145)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:559)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:519)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:489)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:238)
	at java.lang.Thread.run(Thread.java:745)

**Comment by damithc** [comment]
Another few today.

**Comment by damithc** [comment]
Still happening

**Comment by damithc** [comment]
Got one more today.

**Comment by damithc** [comment]
Doesn't seem to be happening anymore.
