### ISSUE TITLE
FeedbackSubmissionAdjustmentAction failing to complete

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4193]
CS2103 has about 235 students. After 3 sessions were over, I changed the section and team of all students to put them in to proper teams/tutorials. Previously they were in 3 sections, each section containing a single team. After the change, I'm getting lot of these errors. A scalability issue in the submission adjustment code? Perhaps the unusually large team size earlier is a factor too. 

Error Message: teammates.logic.automated.FeedbackSubmissionAdjustmentAction execute: Error encountered while adjusting feedback session responses of L1 wrap up in course : CS2103-Aug2015 : API call has not completed yet. TEAMMATESLOG|||feedbackSubmissionAdjustmentWorker|||Servlet Action Failure|||true|||Unknown|||Unknown|||Unknown|||Unknown|||Servlet Action failure in feedbackSubmissionAdjustmentWorker
class java.lang.IllegalStateException: java.lang.IllegalStateException: API call has not completed yet. at com.google.apphosting.runtime.ApiProxyImpl$AsyncApiFuture.getWallclockTimeInMillis(ApiProxyImpl.java:444) at com.google.appengine.tools.appstats.RecordingFuture$ExtendedFuture.getWallclockTimeInMillis(RecordingFuture.java:71) at com.google.appengine.tools.appstats.RecordingFuture$ExtendedFuture.getWallclockTimeInMillis(RecordingFuture.java:71) at com.google.appengine.tools.appstats.Recorder.processRecordingFuture(Recorder.java:413) at com.google.appengine.tools.appstats.Recorder.processAsyncRpc(Recorder.java:370) at com.google.appengine.tools.appstats.RecordingFuture.maybeRecordStats(RecordingFuture.java:140) at com.google.appengine.tools.appstats.RecordingFuture.get(RecordingFuture.java:110) at com.google.appengine.tools.appstats.RecordingFuture$ExtendedFuture.get(RecordingFuture.java:49) at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:88) at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:88) at com.google.appengine.api.datastore.FutureHelper.getInternal(FutureHelper.java:76) at com.google.appengine.api.datastore.FutureHelper.quietGet(FutureHelper.java:36) at com.google.appengine.api.datastore.BaseQueryResultsSource.getIndexList(BaseQueryResultsSource.java:152) at com.google.appengine.api.datastore.BaseQueryResultsSource.loadMoreEntities(BaseQueryResultsSource.java:181) at com.google.appengine.api.datastore.BaseQueryResultsSource.loadMoreEntities(BaseQueryResultsSource.java:164) at com.google.appengine.api.datastore.QueryResultIteratorImpl.ensureLoaded(QueryResultIteratorImpl.java:147) at com.google.appengine.api.datastore.QueryResultIteratorImpl.hasNext(QueryResultIteratorImpl.java:64) at org.datanucleus.store.appengine.query.RuntimeExceptionWrappingIterator$1.get(RuntimeExceptionWrappingIterator.java:50) at org.datanucleus.store.appengine.query.RuntimeExceptionWrappingIterator$1.get(RuntimeExceptionWrappingIterator.java:46) at org.datanucleus.store.appengine.query.QueryExceptionWrappers$1.get(QueryExceptionWrappers.java:51) at org.datanucleus.store.appengine.query.QueryExceptionWrappers$2.get(QueryExceptionWrappers.java:86) at org.datanucleus.store.appengine.query.RuntimeExceptionWrappingIterator.hasNext(RuntimeExceptionWrappingIterator.java:105) at org.datanucleus.store.appengine.query.LazyResult.resolveAll(LazyResult.java:115) at org.datanucleus.store.appengine.query.LazyResult.size(LazyResult.java:110) at org.datanucleus.store.appengine.query.StreamingQueryResult.size(StreamingQueryResult.java:130) at org.datanucleus.store.query.AbstractQueryResult.isEmpty(AbstractQueryResult.java:312) at teammates.storage.api.FeedbackResponsesDb.getFeedbackResponseEntity(FeedbackResponsesDb.java:655) at teammates.storage.api.FeedbackResponsesDb.getEntity(FeedbackResponsesDb.java:1019) at teammates.storage.api.FeedbackResponsesDb.getFeedbackResponseEntityOptimized(FeedbackResponsesDb.java:120) at teammates.logic.core.FeedbackResponsesLogic.updateFeedbackResponseForChangingSection(FeedbackResponsesLogic.java:560) at teammates.logic.core.StudentsLogic.adjustFeedbackResponseForEnrollments(StudentsLogic.java:643) at teammates.logic.automated.FeedbackSubmissionAdjustmentAction.execute(FeedbackSubmissionAdjustmentAction.java:83) at teammates.logic.automated.FeedbackSubmissionAdjustmentWorkerServlet.doGet(FeedbackSubmissionAdjustmentWorkerServlet.java:12) at teammates.logic.automated.WorkerServlet.doPost(WorkerServlet.java:31) at javax.servlet.http.HttpServlet.service(HttpServlet.java:637) at javax.servlet.http.HttpServlet.service(HttpServlet.java:717) at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166) at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388) at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216) at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182) at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765) at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418) at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257) at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) at org.mortbay.jetty.Server.handle(Server.java:326) at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923) at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76) at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146) at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:468) at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437) at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444) at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230) at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308) at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300) at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441) at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:234) at java.lang.Thread.run(Thread.java:745)

**Comment by damithc** [comment]
old issue. closing.
