### ISSUE TITLE
Instructor: search: fix error caused by query strings longer than 2000 bytes

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4345]
```

query string must not be longer than 2000 bytes, was 2197


Request Path /page
Request Parameters {searchstudents::true, searchcommentforresponses::false, user::abc, searchkey::li jie, searchcommentforstudents::false}
Stack Trace



java.lang.IllegalArgumentException: query string must not be longer than 2000 bytes, was 2197
    at com.google.appengine.api.search.checkers.Preconditions.checkArgument(Preconditions.java:55)
    at com.google.appengine.api.search.checkers.QueryChecker.checkQueryFast(QueryChecker.java:99)
    at com.google.appengine.api.search.checkers.QueryChecker.checkQuery(QueryChecker.java:27)
    at com.google.appengine.api.search.Query$Builder.setQueryString(Query.java:225)
    at com.google.appengine.api.search.Query$Builder.build(Query.java:241)
    at teammates.storage.search.SearchQuery.toQuery(SearchQuery.java:104)
    at teammates.storage.api.EntitiesDb.searchDocuments(EntitiesDb.java:320)
    at teammates.storage.api.StudentsDb.search(StudentsDb.java:59)
    at teammates.logic.core.StudentsLogic.searchStudents(StudentsLogic.java:135)
    at teammates.logic.api.Logic.searchStudents(Logic.java:948)
    at teammates.ui.controller.InstructorSearchPageAction.execute(InstructorSearchPageAction.java:71)
    at teammates.ui.controller.Action.executeAndPostProcess(Action.java:337)
    at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:59)
    at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:38)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:142)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
    at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:442)
    at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
    at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
    at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
    at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
    at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:234)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by damithc** [comment]
Labeling as 'high' until we figure out the cause.

**Comment by kanghj** [comment]
Can happen if the student searched for is in many courses. This is an example of the query formed, for search query "jean":

<code>
teammates.storage.search.SearchQuery buildQueryString: Query: courseId:(1 OR 10 OR 11 OR 12 OR 13 OR 14 OR 15 OR 16 OR 17 OR 18 OR 19 OR 2 OR 20 OR 21 OR 22 OR 23 OR 24 OR 25 OR 26 OR 27 OR 28 OR 29 OR 3 OR 30 OR 31 OR 32 OR 33 OR 34 OR 35 OR 36 OR 37 OR 38 OR 39 OR 4 OR 40 OR 41 OR 42 OR 43 OR 44 OR 45 OR 46 OR 48 OR 5 OR 6 OR 7 OR 8 OR 9 OR 98 OR 99 OR AAA OR ABC OR CS1010 OR One OR anotheroldcourse OR courseForArchiving OR empty OR kanghongjin.gma-demo OR meandmyself OR myself OR oldcourse OR oldcourse2) AND (giverEmail:(kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com OR kanghongjin@gmail.com) OR isVisibleToInstructor:true) AND searchableText:(jean)

</code>

**Comment by damithc** [comment]
What can we do to solve it?

**Comment by kanghj** [comment]
We could construct queries for batches of courses, instead of for all courses at one time.

**Comment by damithc** [comment]
This means the instructor has many courses right?

**Comment by kanghj** [comment]
Yup, maybe we could filter out archived courses instead.

**Comment by damithc** [comment]
I think we should include them too. Otherwise search is not very useful.

**Comment by junhaoyap** [comment]
Agree with hong jin, we can break up the query into batches (of less than 2000 bytes each and still meaningful, by that I mean no parameters that are sliced in such a way that it means gibberish) instead of doing one lump querying

**Comment by thyageshm** [comment]
@kanghj any updates on this one?
@damithc is this one still `p.High`?

**Comment by damithc** [comment]
Yes, it is an ugly bug. Even if we don't fix it soon, the feature should at least fail gracefully.

**Comment by kanghj** [comment]
I am only halfway done with this. I'll move this to the next milestone.

**Comment by thyageshm** [comment]
Continue on with the work, if it slips this release, we will shift it to the next one

**Comment by samsontmr** [comment]
Hi @kanghj, I'm interested in learning more about the storage component. Perhaps you could guide me through this if you're not working on it anymore?

**Comment by kanghj** [comment]
@samsontmr, the storage of the teammates data that we use in most places is separate from the GAE search API. This issue is related to searching. IIRC, the class that needs editing here should be `SearchQuery` and its subclasses. You will probably need to refactor it quite a bit first before you can modify it to fix the bug described in this issue.

**Comment by samsontmr** [comment]
@kanghj I see that would be similar to pagination right?

**Comment by wkurniawan07** [comment]
@kanghj @samsontmr you both would be glad to know that I'm already doing it in #6495.

**Comment by whipermr5** [comment]
@malayaleecoder This is the error you're facing :)

**Comment by damithc** [comment]
This error is cropping up again. It will be good to fix as those who have many courses are the ones who need the search feature :-p

**Comment by Ayush517** [comment]
Can this error be because of the limitation of characters in url? I found [this](https://stackoverflow.com/questions/29458445/what-is-a-safe-maximum-length-a-segment-in-a-url-path-should-be/33733386) :

"According to the HTTP spec, there is no limit to a URL's length. Keep your URLs under 2048 characters; this will ensure the URLs work in all clients & server configurations. Also, search engines like URLs to remain under approximately 2000 characters.
Chrome has a 2MB limit for URLs, IE8 and 9 have a 2084 character limit. So everything points in keeping your URLs limited to approx. 2000 characters.
Also, from a usability point-of-view, URLs that long are not usable/readable by users.
However, the domain name has a max. length of 255 characters. So to be on the safe side, the max. length of an URL segment would be around 1745 characters, given that your URL exists out of 1 segment."

**Comment by xpdavid** [comment]
@Ayush517 Nope. It because of the search query limit in GAE. Need refactor the query generation logic.

**Comment by xpdavid** [comment]
With the new REST architecture, this can be solved by issuing multiple search requests and join them together.

**Comment by damithc** [comment]
> With the new REST architecture, this can be solved by issuing multiple search requests and join them together.

I'm not sure. The problem is the query string is too long, not the size of the result set. Unless we do a logical split of the query and and then do a logical `JOIN` of the results.

Looking at [this comment](https://github.com/TEAMMATES/teammates/issues/4345#issuecomment-145350398), perhaps the query can be shortened? There seems to be a lot of duplicated `OR` clauses.

**Comment by xpdavid** [comment]
> The problem is the query string is too long

So I am suggesting to break the queries to multiple one (by REST calls).

The full context is here:

We don't have `giverEmail` in the search query anymore so the comment here https://github.com/TEAMMATES/teammates/issues/4345#issuecomment-145350398 is no longer valid. I guess why we have this issue till now is because the number of courses is unbounded (i.e. The system assume instructor wants to search all students for **all** courses), while we need the `courseId` filed to restrict the visibility so that is why we have a long query with a lot of `courseId`.

Here is one possible way to solve it with the current REST architecture (it is hard before).
- Refine the search API to accept a list of courseId.
- Get all courses the current instructor has in frontend
- (Sort them (maybe)) and send the search query in batch (can be done with lazy-loading)
- Join them together

**Comment by damithc** [comment]
Yes, if we break the query over `OR` conditions, the subsequent `JOIN` is a simple accumulation.

**Comment by wkurniawan07** [comment]
Solr gives 8192 bytes default limit. If we exceed that, we should instead rethink how the feature is designed.
