### ISSUE TITLE
NumberFormatException in submission edit

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4521]
For input string: "APMTqukEGhvoiaOKWMDaOFZnJchubTpvrCVcyrqTtGiNhC9uFosAH4Bk3Dsf_GR6Y92LZaLk1ZfK97WrVikdsB4ksZIU021AhQ"

Actual user userabc 
Request Method POST 
User Agent Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0) 
Request Url https://teammatesv4.appspot.com/page/studentFeedbackSubmissionEditSave 
Request Path /page 
Request Parameters {questiontype-3::NUMSCALE, questiontype-4::NUMSCALE, questiontype-1::NUMSCALE, questiontype-2::NUMSCALE, responsetext-4-1::, responsetext-4-0::, responsetext-4-3::, responsetext-4-2::, responsetext-4-5::, responsetext-4-4::, questiontype-5::TEXT, responsetext-4-6::, questiontype-6::NUMSCALE, courseid::BSV11114, numscalestep-3-3::1, numscalestep-3-4::1, numscalestep-3-5::1, numscalestep-3-6::1, numscalestep-3-0::1, numscalestep-3-1::1, numscalestep-3-2::1, questionresponsetotal-6::7, questionresponsetotal-5::7, questionresponsetotal-4::7, questionresponsetotal-3::7, questionresponsetotal-2::7, questionresponsetotal-1::APMTqukEGhvoiaOKWMDaOFZnJchubTpvrCVcyrqTtGiNhC9uFosAH4Bk3Dsf_GR6Y92LZaLk1ZfK97WrVikdsB4ksZIU021AhQ, numscalestep-1-0::youtube:671:0, numscalestep-1-6::1, numscalestep-1-5::1, numscalestep-1-2::1, numscalestep-1-1::1, numscalestep-1-4::1, numscalestep-1-3::1, responserecipient-6-2::40181624@test.gmail.uk, responserecipient-6-3::40188504@test.gmail.uk, responserecipient-6-0::40220715@test.gmail.uk, responserecipient-6-1::40062560@test.gmail.uk, responserecipient-6-6::40221117@test.gmail.uk, responserecipient-6-4::40160308@test.gmail.uk, responserecipient-6-5::40218423@test.gmail.uk, responsetext-6-6::, responsetext-3-0::, responsetext-1-0::, responsetext-1-1::, responsetext-1-2::, responsetext-1-3::, responsetext-3-5::, responsetext-1-4::, responsetext-3-6::, responsetext-1-5::, responsetext-1-6::, responsetext-3-1::, responsetext-3-2::, responsetext-3-3::, responsetext-3-4::, responsetext-5-4::, responsetext-5-3::, responsetext-5-6::, responsetext-5-5::, responsetext-5-0::, responsetext-5-2::, responsetext-5-1::, numscalestep-6-6::1, numscalestep-6-4::1, numscalestep-6-5::1, responserecipient-2-3::40188504@test.gmail.uk, numscalestep-6-1::1, responserecipient-2-2::40181624@test.gmail.uk, numscalestep-6-0::1, numscalestep-6-3::1, responserecipient-2-1::40062560@test.gmail.uk, responserecipient-2-0::40220715@test.gmail.uk, numscalestep-6-2::1, responserecipient-2-6::40221117@test.gmail.uk, responserecipient-2-5::40218423@test.gmail.uk, responserecipient-2-4::40160308@test.gmail.uk, numscalemin-4-1::0, numscalemin-4-0::0, numscalemin-4-3::0, numscalemin-4-2::0, numscalemin-4-5::0, numscalemin-4-4::0, numscalemin-4-6::0, numscalestep-2-0::1, numscalestep-2-1::1, numscalestep-2-2::1, numscalestep-2-3::1, numscalestep-2-4::1, numscalestep-2-5::1, numscalestep-2-6::1, responserecipient-1-0::40220715@test.gmail.uk, responsetext-2-5::, responsetext-2-4::, responsetext-2-3::, responsetext-2-2::, responsetext-2-6::, responsetext-2-1::, responsetext-2-0::, responsetext-6-0::, responsetext-6-1::, responsetext-6-4::, responsetext-6-5::, responsetext-6-2::, responsetext-6-3::, numscalemax-6-5::5, numscalemax-6-4::5, numscalemax-4-1::5, numscalemax-6-6::5, numscalemax-4-0::5, numscalemax-4-3::5, numscalemax-4-2::5, numscalemax-4-5::5, numscalemax-4-4::5, numscalemax-4-6::5, numscalemax-6-0::5, numscalemax-6-1::5, numscalemax-6-2::5, numscalemax-6-3::5, responserecipient-1-5::40218423@test.gmail.uk, responserecipient-1-6::40221117@test.gmail.uk, responserecipient-1-3::40188504@test.gmail.uk, responserecipient-1-4::40160308@test.gmail.uk, responserecipient-1-1::40062560@test.gmail.uk, responserecipient-1-2::40181624@test.gmail.uk, numscalemax-2-3::5, numscalemax-2-2::5, numscalemax-2-1::5, numscalemax-2-0::5, numscalemin-1-6::0, responserecipient-5-6::40221117@test.gmail.uk, numscalemax-2-6::5, numscalemin-1-5::0, responserecipient-5-5::40218423@test.gmail.uk, numscalemax-2-5::5, numscalemin-1-4::0, numscalemax-2-4::5, numscalemin-1-3::0, numscalemin-1-2::0, numscalemax-3-6::5, responserecipient-5-2::40181624@test.gmail.uk, numscalemin-1-1::0, numscalemax-3-5::5, responserecipient-5-1::40062560@test.gmail.uk, numscalemin-1-0::1, numscalemax-3-4::5, responserecipient-5-4::40160308@test.gmail.uk, numscalemax-3-3::5, responserecipient-5-3::40188504@test.gmail.uk, numscalemax-3-2::5, numscalemax-3-1::5, numscalemax-3-0::5, fsname::Self and Peer assessment - CW1, responserecipient-5-0::40220715@test.gmail.uk, questionid-2::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgLLw7IUKDA, responserecipient-3-3::40188504@test.gmail.uk, numscalemin-3-0::0, questionid-3::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgLLkopkKDA, responserecipient-3-4::40160308@test.gmail.uk, numscalemax-1-5::5, responserecipient-3-5::40218423@test.gmail.uk, questionid-1::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgNKPieUKDA, numscalemax-1-6::5, responserecipient-3-6::40221117@test.gmail.uk, numscalemax-1-3::5, responserecipient-3-0::40220715@test.gmail.uk, numscalemax-1-4::5, responserecipient-3-1::40062560@test.gmail.uk, numscalemax-1-1::5, responserecipient-3-2::40181624@test.gmail.uk, numscalemax-1-2::5, numscalemax-1-0::5, numscalemin-3-5::0, numscalemin-3-6::0, numscalemin-3-3::0, questionid-6::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgJKe3bUJDA, numscalemin-3-4::0, numscalemin-3-1::0, questionid-4::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgNKryIwIDA, numscalemin-3-2::0, questionid-5::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgNKmq4cKDA, numscalestep-4-5::1, numscalestep-4-4::1, numscalestep-4-3::1, numscalestep-4-2::1, numscalestep-4-1::1, numscalestep-4-0::1, numscalestep-4-6::1, numscalemin-6-1::0, numscalemin-6-0::0, numscalemin-6-3::0, numscalemin-6-2::0, numscalemin-6-5::0, numscalemin-6-4::0, numscalemin-2-4::0, responserecipient-4-6::40221117@test.gmail.uk, numscalemin-2-5::0, numscalemin-2-2::0, numscalemin-2-3::0, numscalemin-2-6::0, numscalemin-6-6::0, responserecipient-4-0::40220715@test.gmail.uk, responserecipient-4-1::40062560@test.gmail.uk, numscalemin-2-0::0, responserecipient-4-2::40181624@test.gmail.uk, numscalemin-2-1::0, responserecipient-4-3::40188504@test.gmail.uk, responserecipient-4-4::40160308@test.gmail.uk, responserecipient-4-5::40218423@test.gmail.uk, user::userabc} 
Stack Trace

java.lang.NumberFormatException: For input string: "APMTqukEGhvoiaOKWMDaOFZnJchubTpvrCVcyrqTtGiNhC9uFosAH4Bk3Dsf_GR6Y92LZaLk1ZfK97WrVikdsB4ksZIU021AhQ"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:492)
	at java.lang.Integer.parseInt(Integer.java:527)
	at teammates.ui.controller.FeedbackSubmissionEditSaveAction.execute(FeedbackSubmissionEditSaveAction.java:85)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:337)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:59)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:142)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:147)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:457)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wkurniawan07** [comment]
Does this still happen?

**Comment by damithc** [comment]
Not since the bug report. Closing for now.
