### ISSUE TITLE
Null in StudentCourseJoinAuthenticatedAction

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4571]
Actual user abc@hotmail.com 
Request Method GET 
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7 
Request Url https://teammatesv4.appspot.com/page/studentCourseJoinAuthenticated 
Request Path /page 
Request Parameters {key::ABCCEDDB2E31655D8616C352B81A1C7D322F6D73156D620837CE1C625AFA0CAA5DB3649A851973A6646B67CC3AD0C1EBAAF8C8D3733A50182BA805335714C19B} 
Stack Trace

java.lang.AssertionError: null
    at teammates.common.util.Assumption.fail(Assumption.java:59)
    at teammates.common.util.Assumption.assertTrue(Assumption.java:27)
    at teammates.common.util.Assumption.assertNotNull(Assumption.java:269)
    at teammates.common.util.Assumption.assertNotNull(Assumption.java:261)
    at teammates.ui.controller.StudentCourseJoinAuthenticatedAction.execute(StudentCourseJoinAuthenticatedAction.java:28)
    at teammates.ui.controller.Action.executeAndPostProcess(Action.java:337)
    at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:59)
    at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:38)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:148)
    at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:469)
    at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
    at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
    at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:234)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
    at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
    at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
    at java.lang.Thread.run(Thread.java:745)

**Comment by damithc** [comment]
Another one:

Actual user def@husky.neu.edu 
Request Method GET 
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36 
Request Url https://teammatesv4.appspot.com/page/studentCourseJoinAuthentication 
Request Path /page 
Request Parameters {studentemail::def@husky.neu.edu, courseid::2016-spring-cs5500-Tues, key::DEFCEDDB2E31655D8616C352B81A1C7D322F6D73156D620837CE1C625AFA0CAA2CA730C7F68DAABF52B85550B9103395AAF8C8D3733A50182BA805335714C19B} 
Stack Trace


java.lang.NullPointerException
	at teammates.ui.controller.StudentCourseJoinAction.execute(StudentCourseJoinAction.java:44)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:337)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:59)
	at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:38)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:148)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:469)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:256)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
	at java.lang.Thread.run(Thread.java:745)

**Comment by damithc** [comment]
Actually, the 2nd one is a different action. It happened again, twice, to another student.

**Comment by damithc** [comment]
Here's the sequence of actions. 
![image](https://cloud.githubusercontent.com/assets/1673303/12540996/79f317d0-c34b-11e5-939d-17fdd9d43453.png)
May be an eventual consistency issue? @LowWeiLin @thyageshm

**Comment by damithc** [comment]
Just realized the sequence is in reverse chronological order. So the failed attempts to view home page was *before* the student joined. The two NPE's are correspond to the two failed attempts to load the home page though. The NPEs were recorded at at 9.33.04 and 9.33.44

**Comment by thyageshm** [comment]
I believe the output is expected but not desired. If the user is not supposed to be there, s/he should be given a UnauthorisedAccessException. 

Also, if the exceptions were thrown in homepage why does the log show null pointer exception in the join action page?

**Comment by damithc** [comment]
NPE should not be 'expected' under any situation. Which object is null? Here's the trace from the log.

![image](https://cloud.githubusercontent.com/assets/1673303/12545464/74daca54-c37d-11e5-8d2e-92c745c1de19.png)

**Comment by damithc** [comment]
Got two more of these. This time too, same student caused both, within a minute of each other.

**Comment by LowWeiLin** [comment]
If the line numbers are still the same as in master, the error on line 44 is:
```
String courseId = student.course;
```
student is null, causing the NPE.
student is supposed to be "the unregistered and not loggedin student's attributes."

Can we check if the student is still enrolled in the course(registered or not)?

**Comment by damithc** [comment]
This particular student is already registered, but he has used the join link again for some reason.
This guy's computer seems to be sending a duplicate request each time. See boxes in the screenshot. The circled one is from a different student, and doesn't have a duplicate. The same case for the other student who triggered the error y'day. Seems certain browsers has this weird behavior which may be causing the problem.
![image](https://cloud.githubusercontent.com/assets/1673303/12572206/03c5caf6-c424-11e5-9f06-7f9014ac160e.png)

**Comment by damithc** [comment]
This could be due to the student email being changed at some point (by the instructor) but the student may be using the link sent earlier. Is that possible?

**Comment by damithc** [comment]
Happened again

java.lang.NullPointerException
	

Actual user abc
Request Method GET 
User Agent Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0 
Request Url https://teammatesv4.appspot.com/page/studentCourseJoinAuthentication 
Request Path /page 
Request Parameters {studentemail::abc@gmail.com, courseid::Test11111, key::216CEDDB2E31655D8616C352B81A1C7D322F6D73156D620837CE1C625AFA0CAA276563EF8ADA28F2CDB10A280B40961BAAF8C8D3733A50182BA805335714C19B} 
Stack Trace


java.lang.NullPointerException
	at teammates.ui.controller.StudentCourseJoinAction.execute(StudentCourseJoinAction.java:41)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:344)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:64)
	at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:43)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:29)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:148)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:469)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:439)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:446)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:256)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:310)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:302)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:443)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
	at java.lang.Thread.run(Thread.java:745)

**Comment by damithc** [comment]
In this particular case, the student is not in the course anymore.

**Comment by damithc** [comment]
Old issue. closing.
