### ISSUE TITLE
JDODataStoreException: Concurrent Modification

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4662]
javax.jdo.JDODataStoreException: Concurrent Modification
	at org.datanucleus.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:304)
	at org.datanucleus.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:674)
	at org.datanucleus.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:694)
	at teammates.storage.api.EntitiesDb.createEntity(EntitiesDb.java:73)
	at teammates.storage.api.StudentsDb.createStudent(StudentsDb.java:132)
	at teammates.logic.core.StudentsLogic.createStudentCascade(StudentsLogic.java:83)
	at teammates.logic.core.StudentsLogic.enrollStudent(StudentsLogic.java:678)
	at teammates.logic.core.StudentsLogic.enrollStudents(StudentsLogic.java:364)
	at teammates.logic.core.StudentsLogic.enrollStudents(StudentsLogic.java:309)
	at teammates.logic.api.Logic.enrollStudents(Logic.java:1237)
	at teammates.ui.controller.InstructorCourseEnrollSaveAction.enrollAndProcessResultForDisplay(InstructorCourseEnrollSaveAction.java:86)
	at teammates.ui.controller.InstructorCourseEnrollSaveAction.execute(InstructorCourseEnrollSaveAction.java:39)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:337)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:59)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)

**Comment by damithc** [comment]
These database errors are a bit worrying because we didn't get them before, and this is not even a busy period for TEAMMATES. Did we do any changes to DB layer recently? Or may be GAE folks tweaked something on their side.

**Comment by kanghj** [comment]
Are we still getting these errors recently?

**Comment by damithc** [comment]
Lat noted on Jan 26th. Closing for now.
