### ISSUE TITLE
InstructorCoursesPageUiTest sometimes fails

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/teammates#4711]
```
org.junit.ComparisonFailure: expected:<[Failed]> but was:<[]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at teammates.test.driver.AssertHelper.assertContains(AssertHelper.java:60)
	at teammates.test.pageobjects.InstructorCoursesPage.waitForAjaxLoadCourseStatsError(InstructorCoursesPage.java:187)
	at teammates.test.cases.ui.browsertests.InstructorCoursesPageUiTest.testCourseStats(InstructorCoursesPageUiTest.java:167)
	at teammates.test.cases.ui.browsertests.InstructorCoursesPageUiTest.allTests(InstructorCoursesPageUiTest.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by damithc** [comment]
I keep getting this on the live server. Tried 4 times with the same result.
