### ISSUE TITLE
NPE in FeedbackContributionQuestionDetails

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4803]
java.lang.NullPointerException
	at java.util.ArrayList.(ArrayList.java:164)
	at teammates.common.datatransfer.FeedbackContributionQuestionDetails.getTeamMembersEmail(FeedbackContributionQuestionDetails.java:568)
	at teammates.common.datatransfer.FeedbackContributionQuestionDetails.getTeamEvalResults(FeedbackContributionQuestionDetails.java:471)
	at teammates.common.datatransfer.FeedbackContributionResponseDetails.getContribQnTeamEvalResult(FeedbackContributionResponseDetails.java:207)
	at teammates.common.datatransfer.FeedbackContributionResponseDetails.getContributionQuestionResponseAnswerHtml(FeedbackContributionResponseDetails.java:81)
	at teammates.common.datatransfer.FeedbackContributionResponseDetails.getAnswerHtml(FeedbackContributionResponseDetails.java:65)
	at teammates.common.datatransfer.FeedbackSessionResultsBundle.getResponseAnswerHtml(FeedbackSessionResultsBundle.java:884)
	at teammates.ui.controller.InstructorFeedbackResultsPageData.buildResponseRowsForQuestion(InstructorFeedbackResultsPageData.java:1229)
	at teammates.ui.controller.InstructorFeedbackResultsPageData.buildQuestionTableAndResponseRows(InstructorFeedbackResultsPageData.java:1045)
	at teammates.ui.controller.InstructorFeedbackResultsPageData.buildQuestionTableAndResponseRows(InstructorFeedbackResultsPageData.java:1001)
	at teammates.ui.controller.InstructorFeedbackResultsPageData.initForViewByQuestion(InstructorFeedbackResultsPageData.java:153)
	at teammates.ui.controller.InstructorFeedbackResultsPageAction.execute(InstructorFeedbackResultsPageAction.java:130)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:337)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:59)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:148)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:468)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:256)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
	at java.lang.Thread.run(Thread.java:745)

**Comment by damithc** [comment]
One instructor cannot view results because of this. Need to fix quickly.

**Comment by damithc** [comment]
The session has two 'team contribution' questions that is causing this error. Other questions work fine.
![image](https://cloud.githubusercontent.com/assets/1673303/13181098/5305a186-d766-11e5-9c83-5f2a139f4834.png)

**Comment by kanghj** [comment]
Are there any teams with special characters in the class? We might have missed out something here during the de-sanitization of student's team.

**Comment by damithc** [comment]
That's possible. That course has following teams:
Hard Rock Café
Hershey's Chocolate
Miami Children's

He has another course with the same two questions, but that session works fine. That course has no unusual team names.

**Comment by wkurniawan07** [comment]
Very likely that's the case. Single quote (`'`) is HTML-sanitized.

**Comment by kanghj** [comment]
Ah, yes. The error appears to be in <code>getTeamNameForEmail</code> in FeedbackSessionResultsBundle. @bamboo3250, or @wkurniawan07, does any of you want to do this now?

**Comment by damithc** [comment]
Need a hot fix pronto.

**Comment by kanghj** [comment]
Fixed in #4805.
