### ISSUE TITLE
InstructorFeedbackAddAction AssertionError: null

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4831]
Actual user abc
Request Method POST 
User Agent Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36 
Request Url https://teammatesv4.appspot.com/page/instructorFeedbackAdd 
Request Path /page 
Request Parameters {endtime::24, graceperiod::15, starttime::10, instructions::Please answer all the given questions., resultsVisibleFromButton::later, fsname::, timezone::-6, fstype::TEAMEVALUATION, startdate::26/02/2016, sessionVisibleFromButton::atopen, enddate::, user::abc, courseid::, sendreminderemail::FEEDBACK_CLOSING//FEEDBACK_PUBLISHED} 
Stack Trace

java.lang.AssertionError: null
    at teammates.common.util.Assumption.fail(Assumption.java:59)
    at teammates.common.util.Assumption.assertTrue(Assumption.java:27)
    at teammates.common.util.Assumption.assertFalse(Assumption.java:44)
    at teammates.common.util.Assumption.assertFalse(Assumption.java:52)
    at teammates.common.util.Assumption.assertNotEmpty(Assumption.java:366)
    at teammates.ui.controller.InstructorFeedbackAddAction.execute(InstructorFeedbackAddAction.java:37)
    at teammates.ui.controller.Action.executeAndPostProcess(Action.java:337)
    at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:59)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:148)
    at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:468)
    at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
    at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
    at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:256)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
    at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
    at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
    at java.lang.Thread.run(Thread.java:745)

**Comment by damithc** [comment]
Another one today.

**Comment by LowWeiLin** [comment]
Does the user have any active courses when this occurred? I can't think of a good reason why courseId is empty in the POST request.

**Comment by damithc** [comment]
Apparently, it's the same user, with the same parameters. Yes, he has two active courses.

{endtime::24, graceperiod::15, starttime::10, instructions::Please answer all the given questions., resultsVisibleFromButton::later, fsname::, timezone::-6, fstype::TEAMEVALUATION, startdate::26/02/2016, sessionVisibleFromButton::atopen, enddate::, user::abc, courseid::, sendreminderemail::FEEDBACK_CLOSING//FEEDBACK_PUBLISHED}

He doesn't have 'Add session' permission in his current course (just an observer). So this could be case of browser trying to auto load a cached page?.

**Comment by LowWeiLin** [comment]
Will need to check if the ui has any problems when the instructor has no permissions to add a session.

**Comment by kanghj** [comment]
This could be the cause: #3712

**Comment by damithc** [comment]
No recent recurrences. Closing.
