### ISSUE TITLE
AssertionError: Question disappeared

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4864]
Actual user abc@fortlewis.edu 
Request Method GET 
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/7.1.8 Safari/537.85.17 
Request Url https://teammatesv4.appspot.com/page/instructorFeedbackDelete 
Request Path /page 
Request Parameters {next::/page/instructorFeedbacksPage?user=abc%40fortlewis.edu, user::abc@fortlewis.edu, courseid::MOB_TEAM_5, fsname::Peer Eval 5.1} 
Stack Trace

java.lang.AssertionError: Question disappeared.
    at teammates.common.util.Assumption.fail(Assumption.java:59)
    at teammates.logic.core.FeedbackQuestionsLogic.shiftQuestionNumbersDown(FeedbackQuestionsLogic.java:758)
    at teammates.logic.core.FeedbackQuestionsLogic.deleteFeedbackQuestionCascade(FeedbackQuestionsLogic.java:743)
    at teammates.logic.core.FeedbackQuestionsLogic.deleteFeedbackQuestionCascade(FeedbackQuestionsLogic.java:680)
    at teammates.logic.core.FeedbackQuestionsLogic.deleteFeedbackQuestionsForSession(FeedbackQuestionsLogic.java:664)
    at teammates.logic.core.FeedbackSessionsLogic.deleteFeedbackSessionCascade(FeedbackSessionsLogic.java:1601)
    at teammates.logic.api.Logic.deleteFeedbackSession(Logic.java:1751)
    at teammates.ui.controller.InstructorFeedbackDeleteAction.execute(InstructorFeedbackDeleteAction.java:27)
    at teammates.ui.controller.Action.executeAndPostProcess(Action.java:337)
    at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:59)
    at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:38)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:148)
    at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:468)
    at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
    at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
    at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:256)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
    at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
    at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
    at java.lang.Thread.run(Thread.java:745)

**Comment by damithc** [comment]
No recent occurrences.
