### ISSUE TITLE
Getting Error while running TeamMates application

### ISSUE THREAD

**Issue by tarun14110** [TEAMMATES/teammates#4913]
Project in eclipse shows no error. But while running I am getting the below error.
Everything was running fine for me till I updated firefox to a new version. My test cases were failing afer updating firefox. After a little bit of research I found that I need to update the selenium version . So I added selenium `selenium-server-standalone-2.52.0.jar` . From there problem started . I reverted back to previous selenium jar. But still same problem. Cleaning the project didn't worked. 
Could someone explain what I am missing ?

```
java.lang.RuntimeException: Unable to create a DevAppServer
	at com.google.appengine.tools.development.DevAppServerFactory.doCreateDevAppServer(DevAppServerFactory.java:266)
	at com.google.appengine.tools.development.DevAppServerFactory.access$000(DevAppServerFactory.java:36)
	at com.google.appengine.tools.development.DevAppServerFactory$1.run(DevAppServerFactory.java:226)
	at com.google.appengine.tools.development.DevAppServerFactory$1.run(DevAppServerFactory.java:224)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.appengine.tools.development.DevAppServerFactory.createDevAppServer(DevAppServerFactory.java:224)
	at com.google.appengine.tools.development.DevAppServerFactory.createDevAppServer(DevAppServerFactory.java:94)
	at com.google.appengine.tools.development.DevAppServerMain$StartAction.apply(DevAppServerMain.java:258)
	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:48)
	at com.google.appengine.tools.development.DevAppServerMain.run(DevAppServerMain.java:218)
	at com.google.appengine.tools.development.DevAppServerMain.main(DevAppServerMain.java:209)
Caused by: java.lang.RuntimeException: Cannot generate policy file.
	at com.google.apphosting.utils.security.SecurityManagerInstaller.install(SecurityManagerInstaller.java:96)
	at com.google.appengine.tools.development.DevAppServerFactory.doCreateDevAppServer(DevAppServerFactory.java:251)
	... 10 more
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2024)
	at java.io.File.createTempFile(File.java:2070)
	at com.google.apphosting.utils.security.SecurityManagerInstaller.generatePolicyFile(SecurityManagerInstaller.java:144)
	at com.google.apphosting.utils.security.SecurityManagerInstaller.install(SecurityManagerInstaller.java:94)
	... 11 more

```

**Comment by wkurniawan07** [comment]
Can you navigate to the app in localhost? If it's a testing-specific error, I think it's caused by the new Firefox version. Selenium 2.46.0 doesn't support anything beyond 42.0 yet, and upgrading to new one is not a trivial task.

**Comment by tarun14110** [comment]
yeah, newer firefox version doesn't support selenium 2.46.0. No, I am not able to access app on localhost.

**Comment by wkurniawan07** [comment]
Hmm do you remember what you did after upgrading Firefox that might affect this? The line `Caused by: java.io.IOException: No such file or directory` might suggest that you've modified some directory that you shouldn't.

**Comment by tarun14110** [comment]
@wkurniawan07 I hadn't touched any directory. And it don't show any change in the repository on `git status`. Should I again do setup ?
And it will be better to update to latest Selenium version, if there is nothing specific attached to the present Selenium version.

**Comment by wkurniawan07** [comment]
If all else fails, then perhaps setting up again is the only thing to do.
As for updating, we update libraries as per needed (usually 1-2 times per year). While there's nothing specific attached to 2.46.0, there's nothing specific attached to the newest version either. Since we don't use automated build tool, we can't just update libraries "whenever we wish" because all active contributors/developers need to be in sync with every single library file added/updated (not so much for removed).

**Comment by tarun14110** [comment]
@wkurniawan07 
I again setup the application. But I am getting 20 fails on running tests, and on re-running 18 fails and 2 skips. There were many mismatches in the expected and actual. What may be the reason ?

![screenshot from 2016-03-07 16 37 21](https://cloud.githubusercontent.com/assets/12219700/13567777/5275ee5e-e483-11e5-8d35-78ab624c58a8.png)


logic.EmailsTest
![screenshot from 2016-03-07 16 20 25](https://cloud.githubusercontent.com/assets/12219700/13567448/63361c98-e481-11e5-9a6d-67b6a28209e6.png)

FeedbackSessionsLogicTest
![screenshot from 2016-03-07 16 20 49](https://cloud.githubusercontent.com/assets/12219700/13567449/637f8c8e-e481-11e5-9e97-56d3208ff112.png)

logic.FeedbackResponseCommentsLogic.Test
`java.lang.NullPointerException
	at teammates.test.cases.logic.FeedbackResponseCommentsLogicTest.restoreFrCommentIdFromExistingOne(FeedbackResponseCommentsLogicTest.java:359)
	at teammates.test.cases.logic.FeedbackResponseCommentsLogicTest.restoreFrCommentFromDataBundle(FeedbackResponseCommentsLogicTest.java:340)
	at teammates.test.cases.logic.FeedbackResponseCommentsLogicTest.testDeleteFeedbackResponseComment(FeedbackResponseCommentsLogicTest.java:270)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`
ui.InstructorCourseInstructorDeleteActionTest
![screenshot from 2016-03-07 16 29 59](https://cloud.githubusercontent.com/assets/12219700/13567549/e1410fee-e481-11e5-80ed-4d7fa0f76a9a.png)

InstructorEditStudentDetailsEditSaveActionTest
![screenshot from 2016-03-07 16 32 05](https://cloud.githubusercontent.com/assets/12219700/13567629/582b57a4-e482-11e5-9714-a7da914dc946.png)



I just attached some of these. Can upload remaining if required .

**Comment by kanghj** [comment]
@tarun14110, Can you check that that you are using a Java 7 JDK (in Window->Java->Installed JREs) and not a Java 8 one? If changing to Java 7 resolves the issue, can you still list down or take a screenshot of the failing tests here (just the names will do)?

**Comment by tarun14110** [comment]
@kanghj  Thanks a lot. Java 7 resolved most of the issues.

But I have ran tests many today, I got between 6-12 failures. This time now on running and on and re-running test cases I am left with 4 failed tests. This is the first time I reached to such low number of failed tests :-p.

@wkurniawan07   Could you help me with this ? 

browsertests.InstructorCommentsPageUiTest
![screenshot from 2016-03-08 19 48 03](https://cloud.githubusercontent.com/assets/12219700/13604144/641cb8f6-e567-11e5-9dc5-74dc266816ee.png)

browsertests.InstructorFeedbackResultsPageUiTest
```
java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:41)
	at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:49)
	at teammates.test.pageobjects.InstructorFeedbackResultsPage.verifyParticipantPanelIsCollapsed(InstructorFeedbackResultsPage.java:462)
	at teammates.test.cases.ui.browsertests.InstructorFeedbackResultsPageUiTest.testPanelsCollapseExpand(InstructorFeedbackResultsPageUiTest.java:497)
	at teammates.test.cases.ui.browsertests.InstructorFeedbackResultsPageUiTest.testFrontEndActions(InstructorFeedbackResultsPageUiTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

```


browsertests.InstructorFeedbackEditPageUiTest
`org.openqa.selenium.TimeoutException: Timed out after 800 seconds waiting for presence of element located by: By.className: ui-datepicker-month
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'mafia-Inspiron-3542', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16.0-57-generic', java.version: '1.7.0_80'
Session ID: 522bf2d0-fe5e-4480-b074-d2e6887696a0
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, browserConnectionEnabled=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=28.0}]
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:229)
	at teammates.test.pageobjects.AppPage.waitForElementPresence(AppPage.java:222)
	at teammates.test.pageobjects.InstructorFeedbackEditPage.getDatepickerMonth(InstructorFeedbackEditPage.java:640)
	at teammates.test.pageobjects.InstructorFeedbackEditPage.navigate(InstructorFeedbackEditPage.java:618)
	at teammates.test.pageobjects.InstructorFeedbackEditPage.areDatesOfPreviousCurrentAndNextMonthEnabled(InstructorFeedbackEditPage.java:556)
	at teammates.test.pageobjects.InstructorFeedbackEditPage.areDatesOfPreviousCurrentAndNextMonthEnabled(InstructorFeedbackEditPage.java:540)
	at teammates.test.cases.ui.browsertests.InstructorFeedbackEditPageUiTest.testEditSessionAction(InstructorFeedbackEditPageUiTest.java:139)
	at teammates.test.cases.ui.browsertests.InstructorFeedbackEditPageUiTest.allTests(InstructorFeedbackEditPageUiTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"class name","selector":"ui-datepicker-month"}
Command duration or timeout: 5 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'mafia-Inspiron-3542', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16.0-57-generic', java.version: '1.7.0_80'
*** Element info: {Using=class name, value=ui-datepicker-month}
Session ID: 522bf2d0-fe5e-4480-b074-d2e6887696a0
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, browserConnectionEnabled=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=28.0}]
	at sun.reflect.GeneratedConstructorAccessor58.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:358)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByClassName(RemoteWebDriver.java:439)
	at org.openqa.selenium.By$ByClassName.findElement(By.java:388)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:350)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:809)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$0(ExpectedConditions.java:807)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:181)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:209)
	... 20 more
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"class name","selector":"ui-datepicker-month"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'mafia-Inspiron-3542', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16.0-57-generic', java.version: '1.7.0_80'
Driver info: driver.version: unknown
	at <anonymous class>.FirefoxDriver.prototype.findElementInternal_(file:///tmp/anonymous763494744482487442webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10299)
	at <anonymous class>.FirefoxDriver.prototype.findElement(file:///tmp/anonymous763494744482487442webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10308)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///tmp/anonymous763494744482487442webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12282)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///tmp/anonymous763494744482487442webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12287)
	at <anonymous class>.DelayedCommand.prototype.execute/<(file:///tmp/anonymous763494744482487442webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12229)
`

**Comment by kanghj** [comment]
@tarun14110, I think you can make new issues for InstructorFeedbackEditPageUiTest, and InstructorCommentsPageUiTest. Post the stacktrace, screenshots and relevant information on the new issues. These are caused by some of our tests having poor reliability. We should improve the reliability of those tests. For InstructorFeedbackResultsPageUiTest, #4564 seems to be about the same problem. 

I think you can ignore these test failures for now.

**Comment by tarun14110** [comment]
And what about InstructorFeedbackResultsPageUiTest ?

**Comment by wkurniawan07** [comment]
For the failure in `InstructorCommentsPageUiTest`, the screenshot doesn't help much. Can you post the stack trace as well next time you encounter it?
