### ISSUE TITLE
Getting Error while running TeamMates application in localhost

### ISSUE THREAD

**Issue by RatulGhosh** [TEAMMATES/teammates#4917]
I followed as the steps given in "Setting up the dev server "[https://github.com/TEAMMATES/teammates/blob/master/devdocs/settingUp.md](url)

Till step 5 it was fine but in step 6 while entering credentials for an instructor, I got an error "Cannot send Ajax Request !"
![capture1](https://cloud.githubusercontent.com/assets/8985903/13555274/088b2562-e3e2-11e5-934c-0d60225f88f5.PNG)

Also the course join link for that student is not working.
I am getting the following error - "Error: Not Found

The requested URL /page/studentCourseJoinAuthentication?key=C079C7842EB2D825ABE9D2F82AC43381CE80E7EB1548A2849DC6D2B0F678B90B5BFA31EEEC97C78FB05A28DDBA128400F4E92498C547B3441E68E62114FF3068&studentemail=alice.b.tmms%40gmail.tmt&courseid=imm2014007.iii-demo0 was not found on this server."

**Comment by damithc** [comment]
Actually, I got this from the live server as well. Created issue #4920

**Comment by RatulGhosh** [comment]
Sir is there any way to use the full feature of TEAMMATES in the dev server.
I am unable to use some features like sessions, comments etc.
Also the course join link for that student is not working.

**Comment by damithc** [comment]
When you use the join link on the dev server, remember to replace the domain name in the link with `http://localhost:8888`
All features should be available on the dev server, except email sending.

**Comment by RatulGhosh** [comment]
I synced by master with the main repo but still I am getting the same error  "Cannot send Ajax Request !"
![capture1](https://cloud.githubusercontent.com/assets/8985903/13555274/088b2562-e3e2-11e5-934c-0d60225f88f5.PNG)

And when I am using the joining link : "http://localhost:8888/page/instructorCourseJoin?key=F2AD69F8994BA92C8D605BAEDB35949A41E71A573721C8D60521776714DE0BF8B0860F12DD19C6B955F735D8FBD0D289&instructorinstitution=NUS" , I am redirected to the http://localhost:8888/errorPage.jsp page.

**Comment by kanghj** [comment]
What are you getting in the console in eclipse when you try to create the instructor?

**Comment by shreyamahapatra** [comment]
hello 
still my eclipse project shows many errors . I am unable to download the library files.Is there other means to download the same

**Comment by shreyamahapatra** [comment]
ok..I was able to download the libraries.Linked library to project folder then followed step - 3 as it is.Still errors are prevalent.Please help me out

**Comment by thyageshm** [comment]
@shreyamahapatra please post a screenshot of the errors that occur. Also, if the error(s) you are talking about are different from the current error being discussed here, please look for a related issue or open a new issue

**Comment by jhleefred** [comment]
Hi all,
I am also getting "Cannot send Ajax Request!" error when trying to add an instructor.
![image](https://user-images.githubusercontent.com/22018780/30842256-a6c84998-a246-11e7-9024-ece11a850e08.png)
When I go to the Joining link and click "Yes, this is my account", I get directed to  http://localhost:8888/errorPage.jsp page like @RatulGhosh.

Here are messages from the console:
`9월 25, 2017 11:12:04 오후 com.google.apphosting.utils.jetty.AppEngineAuthentication$AppEngineUserRealm isUserInRole
정보: Checking if principal test@example.com is in role admin
9월 25, 2017 11:12:04 오후 teammates.common.util.Logger info
정보: Request received : [POST] http://localhost:8888/admin/adminInstructorAccountAdd:{instructorshortname::Instructor, token::5B2A0F021280CE601AD59669D42AD442, instructoremail::jhleefred, instructorinstitution::MSU, instructorname::Fred}
9월 25, 2017 11:12:04 오후 teammates.common.util.Logger info
정보: User agent : Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
9월 25, 2017 11:12:04 오후 teammates.common.util.Logger info
정보: URL received : [POST] http://localhost:8888/admin/adminInstructorAccountAdd
9월 25, 2017 11:12:04 오후 com.google.apphosting.utils.jetty.JettyLogger warn
경고: Error for /admin/adminInstructorAccountAdd
java.lang.NoClassDefFoundError: Could not initialize class teammates.common.util.Const
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)
	at com.google.appengine.tools.development.agent.runtime.RuntimeHelper.checkRestricted(RuntimeHelper.java:70)
	at com.google.appengine.tools.development.agent.runtime.Runtime.checkRestricted(Runtime.java:63)
	at teammates.common.exception.TeammatesException.toStringWithStackTrace(TeammatesException.java:32)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:155)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:134)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:122)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:95)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:508)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)`

I have looked at the same issue from the issue tracker and tried to rerun `npm run build`, but it was not working for me. Can anyone help me please?

**Comment by whipermr5** [comment]
@jhleefred How are you starting the dev server? Command line or IDE?

**Comment by jhleefred** [comment]
@whipermr5 I start by running it from Eclipse IDE.

**Comment by whipermr5** [comment]
@jhleefred You've followed all the [Eclipse setup instructions](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-usage.md#eclipse-ide) exactly?

**Comment by jhleefred** [comment]
@whipermr5, yes I followed them thoroughly and got to the point where it returned no error but just warnings. Will I need to start over from the scratch?

**Comment by whipermr5** [comment]
Try:
1. `./gradlew resetEclipseDeps`
1. `Project` → `Properties` → `Java Build Path` → `Libraries` → Remove `Web App Libraries` → `OK`.
1. `Project` → `Clean`

**Comment by jhleefred** [comment]
@whipermr5 It still give me the same error.

**Comment by whipermr5** [comment]
@jhleefred Does your `gradle.properties` file have the `org.gradle.java.home` set to the path of a JDK 7 directory? Is your JRE system library (under Java Build Path) and compiler compliance level (under Java Compiler) set to Java 7?

**Comment by jhleefred** [comment]
I just reinstalled JDK 1.7.0_80 completely and went through the configurations on Eclipse, and it is still giving me "Cannot send Ajax Request!" with pretty much the same Console message.

Below are my settings related to JDK.
![image](https://user-images.githubusercontent.com/22018780/31051243-f7f055aa-a628-11e7-8ba7-ef74843c5fe2.png)
![image](https://user-images.githubusercontent.com/22018780/31051245-1f2259a2-a629-11e7-82f0-5373d1a6e8da.png)
![image](https://user-images.githubusercontent.com/22018780/31051250-2ebbcea2-a629-11e7-8b44-866f577370e1.png)
![image](https://user-images.githubusercontent.com/22018780/31051259-436490aa-a629-11e7-95bd-706530ec0d44.png)
![image](https://user-images.githubusercontent.com/22018780/31051262-6fb7e094-a629-11e7-8279-98acc1cc7e55.png)
![image](https://user-images.githubusercontent.com/22018780/31051270-c86e4c82-a629-11e7-86b1-373f0a6990e4.png)

I am sorry and thank you for all your help @whipermr5 .

**Comment by whipermr5** [comment]
You've done these too, right?
>   * Google App Engine: set up the following by going to `Google → ...`:
>     * Disable Datanucleus: `App Engine` → uncheck `Use Datanucleus JDO/JPA to access the datastore`.
>     * Validation exclusion: `App Engine → Validation` → add two entries: `src/test/java` and `src/client/java`.
>     * WAR directory: `Web Application` → tick both `This project has a WAR directory` and `Launch and deploy from this directory`, and enter `src/main/webapp` as `WAR directory`.

Try going into `src/main/webapp/WEB-INF` and deleting the `classes` folder.

**Comment by jhleefred** [comment]
After deleting the `classes` folder, I started getting the error below:
![image](https://user-images.githubusercontent.com/22018780/31161246-533e7800-a89b-11e7-90ef-117609b82118.png)
I rebuilt the project using `./gradlew setupEclipse` and it create 'classes' folder, and it fixed the error above.
However, it did not fix the Ajax request error.
I made sure checkpoint you suggested are correct:
![image](https://user-images.githubusercontent.com/22018780/31161331-e332dc26-a89b-11e7-82e6-ab848fa11417.png)
![image](https://user-images.githubusercontent.com/22018780/31161339-ef3cfaba-a89b-11e7-8f08-53f63d1be57a.png)
![image](https://user-images.githubusercontent.com/22018780/31161354-017de784-a89c-11e7-9931-902c987cad3d.png)

Thanks @whipermr5 !

**Comment by whipermr5** [comment]
@jhleefred Does it work if you start the dev server from the command line?
