### ISSUE TITLE
Starting the dev server

### ISSUE THREAD

**Issue by samatdav** [TEAMMATES/teammates#4938]
Hi there!
I believe I successfully completed all the steps [here ](https://github.com/TEAMMATES/teammates/blob/master/devdocs/settingUp.md) including all prerequisites and partly in setting up  the dev server (until 5th step). I successfully launched website and can see it at localhost:8888 the console says "Dev App Server is now running".
The problem is that I cannot continue the guide as link http://localhost:8888/admin/adminHomePage throws a 500 server error. The fun part is that the first time I launched the server the adminHomePage loaded and crashed only after I clicked login.
The console throws error "Could not initialize class teammates.logic.api.Logic"

I would be glad if anyone could help me resolve it.

**Comment by kanghj** [comment]
@samatdav, Good work on completing most of the steps! For that particular error, check that you have correctly renamed both build.properties and appengine-web.xml. If you already have set that up correctly, then try refreshing and cleaning the project in eclipse.

**Comment by samatdav** [comment]
@kanghj Thank you! That did work and now my server is up and running, what is amazing! I was confused because this renaming process was not explicitly described in the project - only in the [Troubleshooting guide](https://docs.google.com/document/d/1_p7WOGryOStPfTGA_ZifE1kVlskb1zfd3HZwc4lE4QQ/pub?embedded=true) (which I unfortunately missed initially). May be that is worth describing more explicitly. 

Anyway, thanks again!

**Comment by damithc** [comment]
@samatdav yes, renaming is not explicitly mentioned in the documentation. You can create an issue and a PR to add the missing info to the documentation. :-)

**Comment by yj-soh** [comment]
It has been explicitly mentioned in the [setting up guide](https://github.com/TEAMMATES/teammates/blob/master/devdocs/settingUp.md) for as far as I recall. Search for the terms, "Create main config files".

**Comment by nikhilmudholkar** [comment]
@samatdav  @kanghj .....can you explicitly tell about the renaming the files? I am facing exactly the same problem.I am not able to find what name we have to give to the files? Is is just mentioned that you have to rename the file. Nothing else.

**Comment by damithc** [comment]
@nikhilmudholkar can you quote here the instructions that is not clear to you?

**Comment by nikhilmudholkar** [comment]
in the guide it is given as.........
src/test/resources/test.properties
Append a unique id (e.g. your name) to each of the default accounts found at the bottom of this file. e.g. change test.student1.account=alice.tmms to test.student1.account=alice.tmms.KevinChan
src/main/webapp/WEB-INF/appengine-web.xml
For now, property values can remain as they are.

it is not mentioned what we have to do with appengine-web.xml file.




ERROR: Everything seems normal and the dev server starts normally. But you get a "Class not found" or "Class cannot initialize" error when you try to access any non-static pages of the app.

SOLUTION: Check if the build.properties and appengine-web.xml has been renamed properly, which you were supposed to during the set up.

It is not given in the setup about renaming the file. Also what name we have to give them after renaming.
Can you please tell in detail what exactly we have to do??

**Comment by damithc** [comment]
>it is not mentioned what we have to do with appengine-web.xml file.
ERROR: Everything seems normal and the dev server starts normally. But you get a "Class not found" or "Class cannot initialize" error when you try to access any non-static pages of the app.
SOLUTION: Check if the build.properties and appengine-web.xml has been renamed properly, which you were supposed to during the set up.

This is an outdated instruction. I've removed it. There is no need to rename the files.

If you are getting errors when accessing the dev server, post more details of the error messages here.

**Comment by nikhilmudholkar** [comment]
my dev server in running. It says so in the console. i even get the login screen.
![issue8](https://cloud.githubusercontent.com/assets/20753893/21467598/bac5282c-ca19-11e6-98ae-415aa3fe88ea.png)
But when i click login after checking sign as administrator, this screen in shown.
![issue9](https://cloud.githubusercontent.com/assets/20753893/21467605/df2ee55e-ca19-11e6-94d8-0bbfb7a893b2.png)
What am i supposed to do now?The browser always shows error page after the login page.

**Comment by damithc** [comment]
@samatdav check the dev server console after seeing the error message in the browser. It is likely to show some error messages that caused the error page to show up. If you cannot figure out how to resolve the error shown in the dev server console, you can post it here to see if anyone else can help with it.

**Comment by nikhilmudholkar** [comment]
@damithc ..is browser a issue? i am not using firefox or chrome.

**Comment by damithc** [comment]
@nikhilmudholkar unlikely.

**Comment by nikhilmudholkar** [comment]
java.lang.UnsupportedClassVersionError: com/google/common/collect/ImmutableSet : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at com.google.appengine.tools.development.IsolatedAppClassLoader.loadClass(IsolatedAppClassLoader.java:195)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.owasp.html.HtmlPolicyBuilder.<clinit>(HtmlPolicyBuilder.java:163)
	at teammates.common.util.Sanitizer.<clinit>(Sanitizer.java:24)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at com.google.appengine.tools.development.agent.runtime.RuntimeHelper.checkRestricted(RuntimeHelper.java:70)
	at com.google.appengine.tools.development.agent.runtime.Runtime.checkRestricted(Runtime.java:63)
	at teammates.common.util.Url.addParamToUrl(Url.java:74)
	at teammates.ui.controller.ActionResult.appendParameters(ActionResult.java:101)
	at teammates.ui.controller.ActionResult.getDestinationWithParams(ActionResult.java:89)
	at teammates.ui.controller.ShowPageResult.send(ShowPageResult.java:54)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:65)
	at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:43)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:29)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:128)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:122)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:95)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:508)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

</code></pre>
Dec 24, 2016 9:03:50 PM com.google.appengine.api.mail.dev.LocalMailService log
INFO: MailService.send
Dec 24, 2016 9:03:50 PM com.google.appengine.api.mail.dev.LocalMailService log
INFO:   From: TEAMMATES Admin <admin@teammates-nikhilmudholkar.appspotmail.com>
Dec 24, 2016 9:03:50 PM com.google.appengine.api.mail.dev.LocalMailService log
INFO:   To: app_admin@gmail.com
Dec 24, 2016 9:03:50 PM com.google.appengine.api.mail.dev.LocalMailService log
INFO:   Reply-to: teammates@comp.nus.edu.sg
Dec 24, 2016 9:03:50 PM com.google.appengine.api.mail.dev.LocalMailService log
INFO:   Subject: [Javamail Copy] TEAMMATES (4.99): New System Exception: com/google/common/collect/ImmutableSet : Unsupported major.minor version 52.0
Dec 24, 2016 9:03:50 PM com.google.appengine.api.mail.dev.LocalMailService log
INFO:   Body:
Dec 24, 2016 9:03:50 PM com.google.appengine.api.mail.dev.LocalMailService log
INFO:     Content-type: text/html
Dec 24, 2016 9:03:50 PM com.google.appengine.api.mail.dev.LocalMailService log
INFO:     Data length: 5887
Dec 24, 2016 9:03:50 PM teammates.logic.core.EmailSender sendErrorReport
INFO: Sent crash report: [Email sent]to=app_admin@gmail.com|from=admin@teammates-nikhilmudholkar.appspotmail.com|subject=[Javamail Copy] TEAMMATES (4.99): New System Exception: com/google/common/collect/ImmutableSet : Unsupported major.minor version 52.0
Dec 24, 2016 9:03:50 PM teammates.ui.controller.ControllerServlet doPost
SEVERE: TEAMMATESLOG|||admin|||System Error Report|||true|||Unknown|||Unknown|||nikhil@redifmail.com|||Unknown|||<span class="text-danger">[Javamail Copy] TEAMMATES (4.99): New System Exception: com/google/common/collect/ImmutableSet : Unsupported major.minor version 52.0</span><br><a href="#" onclick="showHideErrorMessage('error19952007');">Show/Hide Details >></a><br><span id="error19952007" style="display: none;"><b>Error Message</b>
<br>
<pre><code>
com/google/common/collect/ImmutableSet : Unsupported major.minor version 52.0
</code></pre>
<br>

<b>Actual user</b>
nikhil@redifmail.com
<br>

<b>Request Method</b>
GET
<br>

<b>User Agent</b>
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 UBrowser/5.7.16817.1002 Safari/537.36
<br>

<b>Request Url</b>
http://localhost:8888/admin/adminHomePage
<br>

<b>Request Path</b>
/admin
<br>

<b>Request Parameters</b>
{}
<br>

<b>Stack Trace</b>
<pre><code>

java.lang.UnsupportedClassVersionError: com/google/common/collect/ImmutableSet : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at com.google.appengine.tools.development.IsolatedAppClassLoader.loadClass(IsolatedAppClassLoader.java:195)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.owasp.html.HtmlPolicyBuilder.<clinit>(HtmlPolicyBuilder.java:163)
	at teammates.common.util.Sanitizer.<clinit>(Sanitizer.java:24)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at com.google.appengine.tools.development.agent.runtime.RuntimeHelper.checkRestricted(RuntimeHelper.java:70)
	at com.google.appengine.tools.development.agent.runtime.Runtime.checkRestricted(Runtime.java:63)
	at teammates.common.util.Url.addParamToUrl(Url.java:74)
	at teammates.ui.controller.ActionResult.appendParameters(ActionResult.java:101)
	at teammates.ui.controller.ActionResult.getDestinationWithParams(ActionResult.java:89)
	at teammates.ui.controller.ShowPageResult.send(ShowPageResult.java:54)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:65)
	at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:43)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:29)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:128)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:122)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:95)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:508)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

</code></pre></span>|||/admin/adminHomePage|||nikhil@redifmail.com%20161224233350451









this was the message that was flashed on the console after i visited the link

**Comment by damithc** [comment]
@nikhilmudholkar See item 11 in [this doc](https://github.com/TEAMMATES/teammates/blob/master/docs/troubleshooting-guide.md)
