### ISSUE TITLE
InstructorFeedbackPageUiTest is failing on live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4956]
com.thoughtworks.selenium.Wait$WaitTimedOutException: Failed to load page within 60000 ms
	at com.thoughtworks.selenium.Wait.wait(Wait.java:99)
	at com.thoughtworks.selenium.Wait.wait(Wait.java:76)
	at com.thoughtworks.selenium.webdriven.commands.WaitForPageToLoad.handleSeleneseCommand(WaitForPageToLoad.java:80)
	at com.thoughtworks.selenium.webdriven.commands.WaitForPageToLoad.handleSeleneseCommand(WaitForPageToLoad.java:1)
	at com.thoughtworks.selenium.webdriven.SeleneseCommand.apply(SeleneseCommand.java:36)
	at com.thoughtworks.selenium.webdriven.Timer.run(Timer.java:41)
	at com.thoughtworks.selenium.webdriven.WebDriverCommandProcessor.execute(WebDriverCommandProcessor.java:149)
	at com.thoughtworks.selenium.webdriven.WebDriverCommandProcessor.doCommand(WebDriverCommandProcessor.java:74)
	at com.thoughtworks.selenium.DefaultSelenium.waitForPageToLoad(DefaultSelenium.java:681)
	at teammates.test.pageobjects.AppPage.waitForPageToLoad(AppPage.java:197)
	at teammates.test.pageobjects.AppPage.goToPreviousPage(AppPage.java:267)
	at teammates.test.cases.ui.browsertests.InstructorFeedbackPageUiTest.testCopyToAction(InstructorFeedbackPageUiTest.java:499)
	at teammates.test.cases.ui.browsertests.InstructorFeedbackPageUiTest.testCopyActions(InstructorFeedbackPageUiTest.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

**Comment by damithc** [comment]
Didn't fail at V5.72. closing.

**Comment by damithc** [comment]
Failing at V5.77

org.openqa.selenium.TimeoutException: Timed out after 60 seconds waiting for visibility of [[FirefoxDriver: firefox on WINDOWS (d47cb332-1eae-49fd-9779-3830385d46de)] -> id: modalCopiedSessionName]
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'damithch-d9010', ip: '172.26.184.190', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_45'
Session ID: d47cb332-1eae-49fd-9779-3830385d46de
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=38.0.5}]
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:229)
	at teammates.test.pageobjects.AppPage.waitForElementVisibility(AppPage.java:229)
	at teammates.test.pageobjects.InstructorFeedbacksPage.copyFeedbackSession(InstructorFeedbacksPage.java:250)
	at teammates.test.cases.ui.browsertests.InstructorFeedbackPageUiTest.testCopyFromAction(InstructorFeedbackPageUiTest.java:471)
	at teammates.test.cases.ui.browsertests.InstructorFeedbackPageUiTest.testCopyActions(InstructorFeedbackPageUiTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

**Comment by ashrayjain** [comment]
@damithc This test occasionally fails on the first try on Travis as well (always passes on subsequent retries though).

**Comment by damithc** [comment]
I tried a few times but could not get it to pass. But yes, it used to pass before.
