### ISSUE TITLE
New contributor self intro [Priyam Gupta]

### ISSUE THREAD

**Issue by priyamm** [TEAMMATES/teammates#5003]
**Dear Sir/Madam,
I am Priyam, a final year undergraduate student in Computer Science at AKGEC, India.

I am a GSOC aspirant and have worked on various projects on Java, ANTLR and Web Development. Going through your Organisation page I came through quite a large number of interesting projects. I tried to Set-Up the development environment and successfully launched the Web Application.
As indicated in the Contribution guide, I can choose any of the two roles: Web-Page Developer and Front-End Developer. I can also try for the Back-end, though some learning will be required.
The Projects I am interested are:
1. Comments
2. Email Customizer
3. Feedback Resume**

![screenshot 102](https://cloud.githubusercontent.com/assets/5033626/13764341/5437afa6-ea74-11e5-80d5-9cc41c5bdc83.png)
![screenshot 101](https://cloud.githubusercontent.com/assets/5033626/13764349/696146ee-ea74-11e5-85cd-06526c0b2611.png)
![screenshot 103](https://cloud.githubusercontent.com/assets/5033626/13764360/7d61d3a2-ea74-11e5-9bf1-13d4747416c3.png)

**While running the Application, I also got some error while Logging In as Administrator with the window showing that "Local Host isn't working".**

The error is"
Mar 15, 2016 5:48:59 AM com.google.apphosting.utils.jetty.JettyLogger warn
WARNING: Nested in javax.servlet.ServletException: java.lang.NoClassDefFoundError: Could not initialize class teammates.common.util.Config:
java.lang.NoClassDefFoundError: Could not initialize class teammates.common.util.Config
	at org.apache.jsp.jsp.footer_jsp._jspService(footer_jsp.java:62)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:97)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:377)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
	at com.google.appengine.tools.development.PrivilegedJspServlet.access$101(PrivilegedJspServlet.java:23)
	at com.google.appengine.tools.development.PrivilegedJspServlet$2.run(PrivilegedJspServlet.java:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.appengine.tools.development.PrivilegedJspServlet.service(PrivilegedJspServlet.java:58)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
	at org.mortbay.jetty.servlet.Dispatcher.include(Dispatcher.java:192)
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:968)
	at org.apache.jsp.deadlineExceededErrorPage_jsp._jspService(deadlineExceededErrorPage_jsp.java:94)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:97)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:377)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
	at com.google.appengine.tools.development.PrivilegedJspServlet.access$101(PrivilegedJspServlet.java:23)
	at com.google.appengine.tools.development.PrivilegedJspServlet$2.run(PrivilegedJspServlet.java:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.appengine.tools.development.PrivilegedJspServlet.service(PrivilegedJspServlet.java:58)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:327)
	at org.mortbay.jetty.servlet.Dispatcher.error(Dispatcher.java:135)
	at org.mortbay.jetty.servlet.ErrorPageErrorHandler.handle(ErrorPageErrorHandler.java:129)
	at org.mortbay.jetty.Response.sendError(Response.java:274)
	at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:108)
	at com.google.appengine.tools.development.JettyContainerService$RecordingResponseWrapper.sendError(JettyContainerService.java:596)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:492)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:509)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
"
Thanks,
Priyam Gupta

**Comment by kanghj** [comment]
@priyamm, Good work on completing most of the steps to set up the project! For that particular error, check that you have correctly renamed both build.properties and appengine-web.xml.

**Comment by junhaoyap** [comment]
Welcome to the TEAMMATES contributor community @priyamm, good work on moving into Phase D and following the instructions!

Please refer to our 'Instructions for Google Summer of Code Applicants' for guidance on how you can move forward in applying to contribute to TEAMMATES under GSoC :)

As for fixing the above and moving on to contributing, do look at what @kanghj has advised

**Comment by priyamm** [comment]
@kanghj Thank you for your inputs sir, I am pleased to tell you that I have been successfully able to **Login in as Admin** and completed the rest of the task upto accessing the _dev server as a student_. Shall I do cover up the **Running Test Suite** part or directly move up to the contributing phase.
I am currently watching the **Dev Role** instructions in **procees.md**. It says I have to pick one of the issues. Will I have to pick one of the issues listed by others on the **teammate issue** page or by ourself by analyzing? or Can you suggest me some of the beginner level issues that I should start with.
Regards,
Priyam

**Comment by priyamm** [comment]
Dear Sir/Madam, 
I think I found one issue: https://github.com/TEAMMATES/teammates/issues/5020
Looking forward to solve it.
Thanks

**Comment by damithc** [comment]
@priyamm please change the issue title to include your name

**Comment by priyamm** [comment]
@junhaoyap  Dear Sir, As I have previously mentioned I like to be a part of GSOC under your organization. I am going to submit my proposal by today . I wanted to ask that can I apply for more than one topic  like I am interested in Comments, Email Customizer and Resume Feedback. I am really interested in these three topics and I have also worked on 2 issues and made pull requests.
Thanks

**Comment by junhaoyap** [comment]
@priyamm I'm sure you can :) cc @damithc to confirm

**Comment by damithc** [comment]
Yes you can submit multiple applications to the same org, but I think the deadline is over now.
