### ISSUE TITLE
InstructorStudentListPageUiTest fails at line 172

### ISSUE THREAD

**Issue by ashrayjain** [TEAMMATES/teammates#5017]
This happens regularly on Travis and sometimes on local environments as well.

The stack trace is:
```
java.lang.AssertionError: expected:<http://localhost:8888/page/studentProfilePic?studentemail=F702AF37C82846594241AA61DA9E8121513646F6B96E433CF5475D7A0DDC960D8A760297A033C316073F728DF8BAE432&courseid=C179779D673504E85F7ADD572ED9CD4D&user=instructorWith2Courses> but was:<http://localhost:8888/images/profile_picture_default.png>
        at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
        at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
        at teammates.test.pageobjects.InstructorStudentListPage.verifyProfilePhoto(InstructorStudentListPage.java:117)
        at teammates.test.cases.ui.browsertests.InstructorStudentListPageUiTest.testShowPhoto(InstructorStudentListPageUiTest.java:172)
        at teammates.test.cases.ui.browsertests.InstructorStudentListPageUiTest.testAll(InstructorStudentListPageUiTest.java:68)
```

**Comment by ashrayjain** [comment]
@thyageshm
