### ISSUE TITLE
unable to deploy to google app engine

### ISSUE THREAD

**Issue by shreyamahapatra** [TEAMMATES/teammates#5090]
exception occured

Unable to update:
com.google.appengine.tools.admin.JspCompilationException: Failed to compile jsp files.
	at com.google.appengine.tools.admin.Application.compileJsps(Application.java:908)
	at com.google.appengine.tools.admin.Application.populateStagingDirectory(Application.java:724)
	at com.google.appengine.tools.admin.Application.createStagingDirectory(Application.java:666)
	at com.google.appengine.tools.admin.AppAdminImpl.doUpdate(AppAdminImpl.java:569)
	at com.google.appengine.tools.admin.AppAdminImpl.update(AppAdminImpl.java:58)
	at com.google.appengine.eclipse.core.proxy.AppEngineBridgeImpl.deploy(AppEngineBridgeImpl.java:433)
	at com.google.appengine.eclipse.core.deploy.DeployProjectJob.runInWorkspace(DeployProjectJob.java:158)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by damithc** [comment]
This is likely to be a common issue for GAE developers. Try searching the web for a solution.

**Comment by shreyamahapatra** [comment]
ok..thank you

**Comment by damithc** [comment]
In the mean time, you can skip over the 'deploy' step and move to other things. You can still contribute to TEAMMATES even without deploying to a remote server.

**Comment by RatulGhosh** [comment]
I was facing the same problem but I found a way to resolve it. 
1. Make sure that JDK is pointing in your build path of eclipse, not the JRE. 
2. Change the eclipse.ini file in your eclipse directory. Add the following argument.

-vm
C:\Program Files\Java\jdk_1.7.0_45\bin\javaw.exe

3. change the system variable JAVA_HOME to point to C:\Program Files\Java\jdk1.7.0_45

4. ensure that the system variable PATH contains C:\Program Files\Java\jdk1.7.0_45\bin
I hope these will help

**Comment by damithc** [comment]
Thanks @RatulGhosh for the response.
Closing this now. @shreyamahapatra please reopen if you need further help.

**Comment by shreyamahapatra** [comment]
thank you  @RatulGhosh .But I had already implemented all those solutions but couldn't deploy

**Comment by shreyamahapatra** [comment]
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/tools/ant/Task
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:410)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2442)
	at java.lang.Class.getMethod0(Class.java:2685)
	at java.lang.Class.getMethod(Class.java:1620)
	at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:488)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:480)
Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.Task
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	... 19 more

this is the error in console window.

**Comment by nikhilmudholkar** [comment]
@RatulGhosh ....i am not able to find the eclipse.ini file. can you help. I am facing similar errors. Nearly 434 errors are present and most of them are in jsp files.

**Comment by damithc** [comment]
@nikhilmudholkar If you cannot find the eclipse.ini file, a google search might give you some pointers on how to find it.
