### ISSUE TITLE
NumberFormatException in admin activity log (live server)

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5198]
failing at V5.75

See next comment for description.

**Comment by damithc** [comment]
Error recorded on the server logs 
java.lang.NumberFormatException: For input string: "rbat017@auckla"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:441)
	at java.lang.Long.parseLong(Long.java:483)
	at teammates.common.util.ActivityLogEntry.initUsingAppLogMessage(ActivityLogEntry.java:134)
	at teammates.common.util.ActivityLogEntry.<init>(ActivityLogEntry.java:105)

**Comment by damithc** [comment]
Did not happen at V5.76. However, this seems to be an intermittent problem in logs that can trip up the activity logs. We need to ensure the code is resilient to this problem.

**Comment by wkurniawan07** [comment]
Superseded by #5956.
