### ISSUE TITLE
Error while instructor joining course: "No institute found for the course"

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5246]
I've been getting a few of these lately. 

```
Request Method
GET



User Agent
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36



Request Url
https://teammatesv4.appspot.com/page/instructorCourseJoinAuthenticated



Request Path
/page



Request Parameters
{key::8949199B9E2E855sxx32D069E1BF53E2C5885D38C1881D0419677B55CACB6B5DF29ABD5E8B1AD9771CF0D8C1925803B1}



Stack Trace
java.lang.AssertionError: No institute found for the course
    at teammates.common.util.Assumption.fail(Assumption.java:59)
    at teammates.common.util.Assumption.assertTrue(Assumption.java:27)
    at teammates.common.util.Assumption.assertFalse(Assumption.java:44)
    at teammates.common.util.Assumption.assertNotEmpty(Assumption.java:370)
    at teammates.logic.core.AccountsLogic.getCourseInstitute(AccountsLogic.java:100)
    at teammates.logic.core.AccountsLogic.joinCourseForInstructorWithInstitute(AccountsLogic.java:181)
    at teammates.logic.core.AccountsLogic.joinCourseForInstructor(AccountsLogic.java:162)
    at teammates.logic.api.Logic.joinCourseForInstructor(Logic.java:581)
    at teammates.ui.controller.InstructorCourseJoinAuthenticatedAction.execute(InstructorCourseJoinAuthenticatedAction.java:35)
    at teammates.ui.controller.Action.executeAndPostProcess(Action.java:337)
    at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:63)
    at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:42)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:148)
    at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:468)
    at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:439)
    at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:446)
    at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:256)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:310)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:302)
    at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:443)
    at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by damithc** [comment]
It's nice if we can add the course ID to the request (and the log message). When troubleshooting, it is useful to identify which course the user is trying to join.

**Comment by damithc** [comment]
Old issue. Closing.
