### ISSUE TITLE
failed tests on master branch in local environment

### ISSUE THREAD

**Issue by tarun14110** [TEAMMATES/teammates#5626]
I am getting 15 failed tests on master branch 

![screenshot from 2016-06-14 20 02 28](https://cloud.githubusercontent.com/assets/12219700/16046686/ff1d7188-326a-11e6-9689-7706dd889c71.png)

logic.EmailGeneratorTest
```
java.lang.AssertionError: expected:<student5InCourse1@gmail.tmt> but was:<student4InCourse1@gmail.tmt>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at teammates.test.cases.BaseTestCase.assertEquals(BaseTestCase.java:139)
	at teammates.test.cases.logic.EmailGeneratorTest.verifyEmail(EmailGeneratorTest.java:230)
	at teammates.test.cases.logic.EmailGeneratorTest.testGenerateFeedbackSessionEmails(EmailGeneratorTest.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

logic.FeedbackResponseCommentsLogicTest
```
java.lang.NullPointerException
	at teammates.test.cases.logic.FeedbackResponseCommentsLogicTest.restoreFrCommentIdFromExistingOne(FeedbackResponseCommentsLogicTest.java:369)
	at teammates.test.cases.logic.FeedbackResponseCommentsLogicTest.restoreFrCommentFromDataBundle(FeedbackResponseCommentsLogicTest.java:350)
	at teammates.test.cases.logic.FeedbackResponseCommentsLogicTest.testDeleteFeedbackResponseComment(FeedbackResponseCommentsLogicTest.java:281)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

logic.FeedbackSessionLogicTest
![screenshot from 2016-06-14 19 48 14](https://cloud.githubusercontent.com/assets/12219700/16046153/0532bf44-3269-11e6-81f0-7df85041f3ad.png)

@kanghj @wkurniawan07  Could you help me with this ?

**Comment by kanghj** [comment]
Can you check that you are using jdk1.7?

**Comment by tarun14110** [comment]
@wkurniawan07 @kanghj  thanks , resolved.
