### ISSUE TITLE
Student submit session: send a confirmation email

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5675]

**Comment by tarun14110** [comment]
@wkurniawan07 @kanghj Can you please help me with this ? 

at stagging server, while adding new instructor. Having issue while sending Email.

Actual user tarun14110@iiitd.ac.in
Request Method POST
User Agent Mozilla/5.0 (X11; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0
Request Url https://4-20-dot-teammates-1201.appspot.com/admin/adminInstructorAccountAdd
Request Path /admin
Request Parameters {instructorshortname::bhai, instructoremail::tarun14110@iiitd.ac.in, instructorinstitution::IIIT Delhi, instructorname::bhai}


Stack Trace
```
`
java.lang.RuntimeException: Unexpected error while sending email
	at teammates.logic.core.InstructorsLogic.sendJoinLinkToNewInstructor(InstructorsLogic.java:310)
	at teammates.logic.api.Logic.sendJoinLinkToNewInstructor(Logic.java:585)
	at teammates.ui.controller.AdminInstructorAccountAddAction.execute(AdminInstructorAccountAddAction.java:124)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:344)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:64)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:29)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:148)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:469)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:439)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:446)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:256)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:310)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:302)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:443)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at javax.mail.internet.AddressParser.tokenizeAddress(AddressParser.java:645)
	at javax.mail.internet.AddressParser.parseAddress(AddressParser.java:113)
	at javax.mail.internet.InternetAddress.(InternetAddress.java:70)
	at javax.mail.internet.InternetAddress.(InternetAddress.java:61)
	at teammates.logic.core.JavamailService.parseToEmail(JavamailService.java:34)
	at teammates.logic.core.JavamailService.sendEmail(JavamailService.java:53)
	at teammates.logic.core.EmailSender.sendEmail(EmailSender.java:104)
	at teammates.logic.core.EmailSender.sendEmailWithLogging(EmailSender.java:93)
	at teammates.logic.core.InstructorsLogic.sendJoinLinkToNewInstructor(InstructorsLogic.java:307)
	... 40 more`
```

**Comment by damithc** [comment]
Are you using the latest master? If yes, refer to recent PSA post my @wkurniawan07 regarding email service configuration. This can happen if you leave out some required properties (newly added) in the `build.properties` file.

**Comment by damithc** [comment]
@tarun14110 can you take this up?

**Comment by damithc** [comment]
Sorry, didn't realize you are working on this already.
