### ISSUE TITLE
Exception in instructorFeedbackQuestionvisibilityMessage (live server): Null recipient type

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5727]
Null recipient type

```
Actual user abc
Request Method POST 
User Agent Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0 
Request Url https://teammatesv4.appspot.com/page/instructorFeedbackQuestionvisibilityMessage 
Request Path /page 
Request Parameters {showresponsesto::INSTRUCTORS, constSumPointsPerOption::false, constSumPoints::100, showrecipientto::INSTRUCTORS, rubricNumCols::4, rubricNumRows::2, questiontext::, numofrecipientstype::max, rubricChoice-3::Strongly Agree, mcqOption-1::, rubricDesc-0-3::Initiates discussions frequently, and engages the team., constSumOption-1::, constSumToRecipients::false, isNotSureAllowedCheck::on, rubricChoice-0::Strongly Disagree, showgiverto::INSTRUCTORS, rubricDesc-0-2::Takes part in discussions and sometimes initiates discussions., constSumOption-0::, mcqOption-0::, rubricDesc-0-1::Occasionally responds, but never initiates discussions., rubricChoice-2::Agree, rubricDesc-0-0::Rarely or never responds., rubricChoice-1::Disagree, generatedOptions::NONE//NONE//NONE, questionnum::9//9, rubricSubQn-0::This student participates well in online discussions., courseid::16Sp-04ElevatorSpeech, rubricSubQn-1::This student completes assigned tasks on time., noofchoicecreated::2//2//2//2, rubricDesc-1-3::Tasks are always completed before the deadline., numofrecipients::1, numscalestep::1, rankOption-1::, rubricWeight-3::0, rankOption-0::, rubricDesc-1-0::Rarely or never completes tasks., rubricWeight-2::0, rubricDesc-1-1::Often misses deadlines., rubricWeight-1::0, rubricDesc-1-2::Occasionally misses deadlines., rubricWeight-0::0, numscalemin::1, fsname::16SP-22FirstGroup, msqOption-0::, msqOption-1::, questiontype::RUBRIC, numscalemax::5, givertype::STUDENTS, user::abc} 
Stack Trace


java.lang.AssertionError: Null recipient type
    at teammates.common.util.Assumption.fail(Assumption.java:61)
    at teammates.common.util.Assumption.assertTrue(Assumption.java:29)
    at teammates.common.util.Assumption.assertNotNull(Assumption.java:271)
    at teammates.ui.controller.InstructorFeedbackQuestionVisibilityMessageAction.extractFeedbackQuestionData(InstructorFeedbackQuestionVisibilityMessageAction.java:47)
    at teammates.ui.controller.InstructorFeedbackQuestionVisibilityMessageAction.execute(InstructorFeedbackQuestionVisibilityMessageAction.java:18)
    at teammates.ui.controller.Action.executeAndPostProcess(Action.java:344)
    at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:64)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:29)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:148)
    at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:469)
    at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:439)
    at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:446)
    at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:256)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:310)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:302)
    at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:443)
    at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by damithc** [comment]
@wkurniawan07  can you assign the dev working in this part of the code recently to investigate?

**Comment by wkurniawan07** [comment]
The Java file for this has not been modified since mid-2015, so it might have something to do with the front-end.

**Comment by YongJieYongJie** [comment]
@damithc It should have been fixed by #5717, can I check if the exception is still being thrown?

**Comment by damithc** [comment]
I see. We'll only know after deploying V5.81

**Comment by damithc** [comment]
No recent recurrences.
