### ISSUE TITLE
InstructorFeedbackResultsPageUiTest fails on live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5735]
Failing at V5.81

java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:41)
	at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:49)
	at teammates.test.cases.BaseTestCase.assertFalse(BaseTestCase.java:131)
	at teammates.test.cases.ui.browsertests.InstructorFeedbackResultsPageUiTest.testIndicateMissingResponses(InstructorFeedbackResultsPageUiTest.java:553)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)

**Comment by damithc** [comment]
Possibly due to live server being slower than dev server.

**Comment by damithc** [comment]
@kanghj from recent changes done by @rclakmal ?

**Comment by rclakmal** [comment]
Strange.....certainly a delay. Fails at 
`        assertFalse(resultsPage.verifyMissingResponsesVisibility());`

We do the same check at the start of the checkbox before un-ticking the checkbox and this is just a re-verification after ticking it back. 
Shall I introduce a wait ?

**Comment by damithc** [comment]
@wkurniawan07 what's the appropriate way to deal with this delay?

**Comment by wkurniawan07** [comment]
Oops sorry I missed this. I can't say for sure; it depends on the source of delay. Is it waiting for some ajax load, element (dis)appearance, or something else?

**Comment by rclakmal** [comment]
@wkurniawan07 It checks the "Indicate Missing Checkboxes" call and validates whether "No Responses" rows are back. Once the checkbox is ticked, a page refresh happens.

**Comment by chowyb** [comment]
It might be possible to use `waitForPageToLoad()` in `AppPage.java` within the click method of `InstructorFeedbackResultsPage.java` for this, but I'm not too sure on this.

As a note, when the checkbox is ticked, a page refresh occurs, and upon page load (`$(document).ready()`), the page uses JS to automatically send several ajax requests to load the responses for each question, by attaching click event handlers and simulating clicks events.

**Comment by kanghj** [comment]
Yes, looks like `waitForPageToLoad` should solve this problem.

**Comment by damithc** [comment]
Failing at V5.82. 
On a related note, this issue seems to be moving too slow.

**Comment by kanghj** [comment]
@rclakmal, will you be submitting a pull request for this?

**Comment by rclakmal** [comment]
@damithc @kanghj Yes. I will work on this today.
