### ISSUE TITLE
MailGun cannot send emails on live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5737]
com.sun.jersey.core.spi.component.ProviderFactory __getComponentProvider: The provider class, class com.sun.jersey.multipart.impl.MultiPartReaderClientSide, could not be instantiated. Processing will continue but the class will not be utilized
java.lang.SecurityException: Unable to create temporary file
	at java.io.File.checkAndCreate(File.java:2083)
	at java.io.File.createTempFile(File.java:2198)
	at java.io.File.createTempFile(File.java:2244)
	at com.sun.jersey.multipart.impl.MultiPartReaderClientSide.createMimeConfig(MultiPartReaderClientSide.java:121)
	at com.sun.jersey.multipart.impl.MultiPartReaderClientSide.<init>(MultiPartReaderClientSide.java:109)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:46)
	at com.sun.jersey.core.spi.component.ComponentConstructor._getInstance(ComponentConstructor.java:210)
	at com.sun.jersey.core.spi.component.ComponentConstructor.getInstance(ComponentConstructor.java:180)
	at com.sun.jersey.core.spi.component.ProviderFactory.__getComponentProvider(ProviderFactory.java:166)
	at com.sun.jersey.core.spi.component.ProviderFactory.getComponentProvider(ProviderFactory.java:137)
	at com.sun.jersey.core.spi.component.ProviderServices.getComponent(ProviderServices.java:283)
	at com.sun.jersey.core.spi.component.ProviderServices.getServices(ProviderServices.java:163)
	at com.sun.jersey.core.spi.factory.MessageBodyFactory.initReaders(MessageBodyFactory.java:176)
	at com.sun.jersey.core.spi.factory.MessageBodyFactory.init(MessageBodyFactory.java:162)
	at com.sun.jersey.api.client.Client.init(Client.java:343)
	at com.sun.jersey.api.client.Client.access$000(Client.java:119)
	at com.sun.jersey.api.client.Client$1.f(Client.java:192)
	at com.sun.jersey.api.client.Client$1.f(Client.java:188)
	at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
	at com.sun.jersey.api.client.Client.<init>(Client.java:188)
	at com.sun.jersey.api.client.Client.<init>(Client.java:160)
	at com.sun.jersey.api.client.Client.create(Client.java:673)
	at teammates.logic.core.MailgunService.sendEmailWithService(MailgunService.java:48)
	at teammates.logic.core.EmailSenderService.sendEmail(EmailSenderService.java:31)
	at teammates.logic.core.EmailSender.sendEmail(EmailSender.java:105)
	at teammates.logic.core.EmailSender.sendEmailWithLogging(EmailSender.java:94)
	at teammates.logic.automated.SendEmailWorkerServlet.doGet(SendEmailWorkerServlet.java:46)
	at teammates.logic.automated.WorkerServlet.doPost(WorkerServlet.java:31)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:29)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:439)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:446)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:256)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:310)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:302)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:443)
	at java.lang.Thread.run(Thread.java:745)

**Comment by damithc** [comment]
@wkurniawan07 see if you can reproduce this on the live server

**Comment by wkurniawan07** [comment]
Hmmm how do I test it on live server? On my staging server all is working.
Similar issue is reported [here](https://java.net/jira/browse/JERSEY-2279) but it's due to an older version of the library used, which is not the case here.

**Comment by damithc** [comment]
live == staging
So it should work on live server as well.

**Comment by wkurniawan07** [comment]
I'll try to replicate the solution given [here](http://stackoverflow.com/questions/6301973/multipart-file-upload-on-google-appengine-using-jersey-1-7), but I can't guarantee that it will get rid of the problem since it doesn't exist in my environment.

**Comment by damithc** [comment]
We can do it in the next release. I switch back to sendgrid for this release.

**Comment by damithc** [comment]
In the meantime, I can deploy a temp version to check if your fix works.
