### ISSUE TITLE
AdminHomePageUiTest: fix failure against live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5866]
Happened during live server testing. Confirmed after multiple runs.

```
java.lang.AssertionError: expected:<Instructor AHPUiT Instrúctör has been successfully created with join link:
https://teammatesv4.appspot.com/page/instructorCourseJoin?key=dsdsdsds127CAAD2437093B7618C9BBABC12BA67285F585424365A64D7988430BB14C548C6038E135B1734B0BCF7BD236D8F7D77464C5C3718E062531EA7FD&instructorinstitution=TEAMMATES+Test+Institute+1> but was:<Instructor AHPUiT Instrúctör has been successfully created with join link:
https://teammatesv4.appspot.com/page/instructorCourseJoin?key=fdfsdfdfsdfsd437093B7618C9BBABC12BA67285F585424365A64D79884BEBBF31301DA5DA6B0F4D5676C9875B059EACECD374619CCEDED2A50DC673D51&instructorinstitution=TEAMMATES+Test+Institute+1>
    at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
    at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
    at teammates.test.cases.BaseTestCase.assertEquals(BaseTestCase.java:172)
    at teammates.test.cases.ui.browsertests.AdminHomePageUiTest.testCreateInstructorAction(AdminHomePageUiTest.java:102)
    at teammates.test.cases.ui.browsertests.AdminHomePageUiTest.testAll(AdminHomePageUiTest.java:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at org.testng.TestRunner.privateRun(TestRunner.java:767)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
    at org.testng.SuiteRunner.run(SuiteRunner.java:240)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
    at org.testng.TestNG.run(TestNG.java:1057)
    at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
```

**Comment by damithc** [comment]
I'm using FF 46

**Comment by wkurniawan07** [comment]
Hmmmm how does this cause Firefox to crash? It looks like just an assertion error (not that it's not a problem).

**Comment by damithc** [comment]
Also happened for StudentFeedbackSubmitPageUiTest. Seems to be non-deterministic. Switching to FF 38 to see if that helps.

**Comment by damithc** [comment]
In both tests that caused the FF crash, the join page is involved though.

**Comment by damithc** [comment]
No more FF crash when using FF 38. But the test still fail (looks like it's a timing issue; creating an instructor takes a very long time on the live server).
I'll open a separate issue for FF 46 crash.

**Comment by damithc** [comment]
Fails at V5.85.01
```
java.lang.AssertionError: expected:<Instructor AHPUiT Instrúctör has been successfully created with join link:
https://teammatesv4.appspot.com/page/instructorCourseJoin?key=%5BBACKDOOR_STATUS_FAILURE%5Dteammates.common.exception.EntityDoesNotExistException%3A+Instructor+AHPUiT.instr1%40gmail.tmt+does+not+belong+to+course+AHPUiT.instr1.gma-demo%09at+teammates.logic.core.InstructorsLogic.verifyIsEmailOfInstructorOfCourse%28InstructorsLogic.java%3A176%29%09at+teammates.logic.core.InstructorsLogic.getEncryptedKeyForInstructor%28InstructorsLogic.java%3A126%29%09at+teammates.logic.api.Logic.getEncryptedKeyForInstructor%28Logic.java%3A447%29%09at+teammates.logic.backdoor.BackDoorServlet.executeBackendAction%28BackDoorServlet.java%3A184%29%09at+teammates.logic.backdoor.BackDoorServlet.doPost%28BackDoorServlet.java%3A119%29%09at+javax.servlet.http.HttpServlet.service%28HttpServlet.java%3A637%29%09at+javax.servlet.http.HttpServlet.service%28HttpServlet.java%3A717%29%09at+org.mortbay.jetty.servlet.ServletHolder.handle%28ServletHolder.java%3A511%29%09at+org.mortbay.jetty.servlet.ServletHandler%24CachedChain.doFilter%28ServletHandler.java%3A1166%29%09at+teammates.storage.datastore.DatastoreFilter.doFilter%28DatastoreFilter.java%3A29%29%09at+org.mortbay.jetty.servlet.ServletHandler%24CachedChain.doFilter%28ServletHandler.java%3A1157%29%09at+com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter%28ParseBlobUploadFilter.java%3A125%29%09at+org.mortbay.jetty.servlet.ServletHandler%24CachedChain.doFilter%28ServletHandler.java%3A1157%29%09at+com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter%28SaveSessionFilter.java%3A37%29%09at+org.mortbay.jetty.servlet.ServletHandler%24CachedChain.doFilter%28ServletHandler.java%3A1157%29%09at+com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter%28JdbcMySqlConnectionCleanupFilter.java%3A60%29%09at+org.mortbay.jetty.servlet.ServletHandler%24CachedChain.doFilter%28ServletHandler.java%3A1157%29%09at+com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter%28TransactionCleanupFilter.java%3A50%29%09at+org.mortbay.jetty.servlet.ServletHandler%24CachedChain.doFilter%28ServletHandler.java%3A1157%29%09at+org.mortbay.jetty.servlet.ServletHandler.handle%28ServletHandler.java%3A388%29%09at+org.mortbay.jetty.security.SecurityHandler.handle%28SecurityHandler.java%3A216%29%09at+org.mortbay.jetty.servlet.SessionHandler.handle%28SessionHandler.java%3A182%29%09at+org.mortbay.jetty.handler.ContextHandler.handle%28ContextHandler.java%3A765%29%09at+org.mortbay.jetty.webapp.WebAppContext.handle%28WebAppContext.java%3A418%29%09at+com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle%28AppVersionHandlerMap.java%3A260%29%09at+org.mortbay.jetty.handler.HandlerWrapper.handle%28HandlerWrapper.java%3A152%29%09at+org.mortbay.jetty.Server.handle%28Server.java%3A326%29%09at+org.mortbay.jetty.HttpConnection.handleRequest%28HttpConnection.java%3A542%29%09at+org.mortbay.jetty.HttpConnection%24RequestHandler.headerComplete%28HttpConnection.java%3A923%29%09at+com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable%28RpcRequestParser.java%3A78%29%09at+org.mortbay.jetty.HttpConnection.handle%28HttpConnection.java%3A404%29%09at+com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest%28JettyServletEngineAdapter.java%3A148%29%09at+com.google.apphosting.runtime.JavaRuntime%24RequestRunnable.run%28JavaRuntime.java%3A504%29%09at+com.google.tracing.TraceContext%24TraceContextRunnable.runInContext%28TraceContext.java%3A446%29%09at+com.google.tracing.TraceContext%24TraceContextRunnable%241.run%28TraceContext.java%3A453%29%09at+com.google.tracing.CurrentContext.runInContext%28CurrentContext.java%3A276%29%09at+com.google.tracing.TraceContext%24AbstractTraceContextCallback.runInInheritedContextNoUnref%28TraceContext.java%3A312%29%09at+com.google.tracing.TraceContext%24AbstractTraceContextCallback.runInInheritedContext%28TraceContext.java%3A304%29%09at+com.google.tracing.TraceContext%24TraceContextRunnable.run%28TraceContext.java%3A450%29%09at+com.google.apphosting.runtime.ThreadGroupPool%24PoolEntry.run%28ThreadGroupPool.java%3A235%29%09at+java.lang.Thread.run%28Thread.java%3A745%29&instructorinstitution=TEAMMATES+Test+Institute+1> but was:<Instructor AHPUiT Instrúctör has been successfully created with join link:
https://teammatesv4.appspot.com/page/instructorCourseJoin?key=8DFB869586127CAAD2437093B7618C9BBABC12BA67285F585424365A64D79884788A2CC27847D28754A974C2578353AEBAE4F374B719F843E7989E7A5BDDA1B5&instructorinstitution=TEAMMATES+Test+Institute+1>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at teammates.test.cases.BaseTestCase.assertEquals(BaseTestCase.java:172)
	at teammates.test.cases.ui.browsertests.AdminHomePageUiTest.testCreateInstructorAction(AdminHomePageUiTest.java:122)
	at teammates.test.cases.ui.browsertests.AdminHomePageUiTest.testAll(AdminHomePageUiTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
```

**Comment by damithc** [comment]
Fails at V5.87

**Comment by damithc** [comment]
Fails at v5.95

**Comment by damithc** [comment]
still failing at v5.98

**Comment by whipermr5** [comment]
@damithc What's the latest error message? The issue might be with the test itself as the expected link contains a `BACKDOOR_STATUS_FAILURE` while the actual link is correct in the last error message [above](https://github.com/TEAMMATES/teammates/issues/5866#issuecomment-235789824).

**Comment by damithc** [comment]
I was trying to run the test again to check, but ran into https://github.com/TEAMMATES/teammates/issues/7247 :-p

**Comment by damithc** [comment]
The error now is,
```
java.lang.NullPointerException
	at teammates.test.cases.browsertests.AdminHomePageUiTest.testCreateInstructorAction(AdminHomePageUiTest.java:102)
	at teammates.test.cases.browsertests.AdminHomePageUiTest.testAll(AdminHomePageUiTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by whipermr5** [comment]
👌 #7255 handles that one too
