### ISSUE TITLE
admin activity log: number format exception

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5956]
This used to happen often with the dev server, but now it's happening in live server as well. It's an intermittent thing. Hard to reproduce. Hope we can make the code immune to it.

```
For input string: "Unknown"





Actual user
damith



Request Method
GET



User Agent
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36



Request Url
https://teammatesv4.appspot.com/admin/adminActivityLogPage



Request Path
/admin



Request Parameters
{}



Stack Trace




java.lang.NumberFormatException: For input string: "Unknown"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:441)
	at java.lang.Long.parseLong(Long.java:483)
	at teammates.common.util.ActivityLogEntry.initUsingAppLogMessage(ActivityLogEntry.java:241)
	at teammates.common.util.ActivityLogEntry.(ActivityLogEntry.java:108)
	at teammates.ui.controller.AdminActivityLogPageAction.filterLogsForActivityLogPage(AdminActivityLogPageAction.java:262)
	at teammates.ui.controller.AdminActivityLogPageAction.searchLogsWithTimeIncrement(AdminActivityLogPageAction.java:226)
	at teammates.ui.controller.AdminActivityLogPageAction.execute(AdminActivityLogPageAction.java:104)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:344)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:64)
	at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:43)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:29)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:148)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:504)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:446)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:453)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:276)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:312)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:304)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:450)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
	at java.lang.Thread.run(Thread.java:745)


|||/admin/adminActivityLogPage|||damith%20160803183142981

**Comment by damithc** [comment]
Possibly the range of our data type is too small to handle the value given.

**Comment by wkurniawan07** [comment]
This is not new (not that it's not a problem): #5198.

**Comment by wkurniawan07** [comment]
This is dependent on how GAE constructs the log from their side. I can't fix it just yet, but I can make it such that more information will be logged should this error pop out again.
