### ISSUE TITLE
Travis test failure: component-tests->teammates.test.cases.logic.EmailGeneratorTest->testSystemCrashReportEmailContent

### ISSUE THREAD

**Issue by peterdfinn** [TEAMMATES/teammates#5970]
I'm trying to set up my local TEAMMATES development environment, and I encountered 15 Travis test failures, including the test `component-tests->teammates.test.cases.logic.EmailGeneratorTest->testSystemCrashReportEmailContent`.

I'm in Step 3 of "Running the Test Suite" in devdocs/settingUp.md.

I'm running OS X 10.11.6.

The error message is: 
java.lang.AssertionError:
at teammates.test.cases.logic.EmailGeneratorTest.testSystemCrashReportEmailContent(EmailGeneratorTest.java:263)
at teammates.test.cases.logic.EmailGeneratorTest.testSystemCrashReportEmailContent(EmailGeneratorTest.java:263)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
at teammates.test.driver.EmailChecker.verifyEmailContent(EmailChecker.java:36)
at teammates.test.cases.logic.EmailGeneratorTest.verifyEmail(EmailGeneratorTest.java: 356)
at teammates.test.cases.logic.EmailGeneratorTest.testSystemCrashReportEmailContent(EmailGeneratorTest.java:285)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

Attached is a screenshot of the diff result:
![screen shot 2016-08-09 at 1 33 53 pm](https://cloud.githubusercontent.com/assets/6372465/17526690/52c7fdde-5e36-11e6-8c3a-1ae1a419c931.png)

I'm hoping to become a contributor after I complete all the stages in the Orientation Task List — is this the kind of thing I should attempt to resolve on my own, or should that wait until after I've completed the Orientation?  I haven't delved into the code to try to address the issue because I wasn't sure about that.

**Comment by wkurniawan07** [comment]
Hi @peterdfinn,
If this test and a limited number of other tests fail, likely the cause is wrong Java version (Java 7 is the requirement, not the latest Java 8). Could you check if you're using the correct Java version when building and running the dev server?

**Comment by peterdfinn** [comment]
That was it.  I had gone into Eclipse's Project Properties and changed the compiler compliance level to 1.7, but I hadn't changed the Run Configurations to use Java 7.

Thanks!
