### ISSUE TITLE
NPE in InstructorFeedbackCopyAction

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5981]
Got this from the live server.

```
java.lang.NullPointerException





Actual user 
abc@pearson.com 



Request Method 
POST 



User Agent 
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36 



Request Url 
https://teammatesv4.appspot.com/page/instructorFeedbackCopy 



Request Path 
/page 



Request Parameters 
{copiedcourseid::SCNF221-2016-Late, copiedfsname::Assignment Part A Team Evaluation-Late, user::abc@pearson.com, courseid::SCNF221-2016PI, fsname::Assignment Part A Team Evaluation Late} 



Stack Trace 



java.lang.NullPointerException
    at teammates.logic.core.FeedbackSessionsLogic.copyFeedbackSession(FeedbackSessionsLogic.java:140)
    at teammates.logic.api.Logic.copyFeedbackSession(Logic.java:1341)
    at teammates.ui.controller.InstructorFeedbackCopyAction.execute(InstructorFeedbackCopyAction.java:38)
    at teammates.ui.controller.Action.executeAndPostProcess(Action.java:344)
    at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:64)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:29)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
|||/page/instructorFeedbackCopy|||mia.beyleveld@pearson.com%2016081220081552
```

**Comment by damithc** [comment]
No recent recurrences. closing.
