### ISSUE TITLE
InstructorCourseEnrollPageUiTest: fix failure when a non-English language setting is used

### ISSUE THREAD

**Issue by mun711** [TEAMMATES/teammates#6049]
The test fails assertion

```
java.lang.AssertionError: expected:<Course Enroll Sample Spreadsheet - Google Sheets> but was:<Course Enroll Sample Spreadsheet - Foi de calcul Google>
    at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
    at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
    at teammates.test.pageobjects.AppPage.verifyTitle(AppPage.java:873)
    at teammates.test.cases.ui.browsertests.InstructorCourseEnrollPageUiTest.testSampleLink(InstructorCourseEnrollPageUiTest.java:65)
    at teammates.test.cases.ui.browsertests.InstructorCourseEnrollPageUiTest.testInstructorCourseEnrollPage(InstructorCourseEnrollPageUiTest.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at org.testng.TestRunner.privateRun(TestRunner.java:767)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
    at org.testng.SuiteRunner.run(SuiteRunner.java:240)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
    at org.testng.TestNG.run(TestNG.java:1057)
    at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)

```

The page title assertion assumes English language but the actual title is in Romanian, so maybe the language preferences for docs.google.com should be set.

**Comment by mohamed-moanis** [comment]
This shows up with me, cause the default of my browser is Arabic language.

I tried in `teammates.test.pageobjects.Browser.java` to set the properties of the firefox test browser, to set language preference to English, but it is not working. I works with any other language other than English.

`
FirefoxProfile profile = new FirefoxProfile();
profile.setPreference("intl.accept_languages", "en");
`

**Comment by damithc** [comment]
@mohamed-moanis did you manage to resolve this issue?

**Comment by mohamed-moanis** [comment]
@damithc  no not with English. When a browser is set to English, google products re translate their pages depending on your IP location. I found some "GET" request parameters that could change that but that doesn't work with the "sheets" app.

I guess a change in the test case itself would be more appropriate.
