### ISSUE TITLE
Some students cannot access profile pic

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6067]
Some students seem to encounter this error when they try to view team.

```
ervlet Action failure in page<br>class teammates.common.exception.UnauthorizedAccessException:  (ControllerServlet.java:91)
teammates.common.exception.UnauthorizedAccessException: User is not instructor of the course that student belongs to
    at teammates.logic.api.GateKeeper.verifyAccessibleForCurrentUserAsInstructor(GateKeeper.java:353)
    at teammates.ui.controller.StudentProfilePictureAction.handleRequestWithEmailAndCourse(StudentProfilePictureAction.java:51)
    at teammates.ui.controller.StudentProfilePictureAction.execute(StudentProfilePictureAction.java:31)
    at teammates.ui.controller.Action.executeAndPostProcess(Action.java:344)
    at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:64)
    at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:43)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:29)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:148)
    at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:504)
    at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:446)
    at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:453)
    at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:276)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:312)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:304)
    at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:450)
    at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by damithc** [comment]
Some other students don't face this problem them.

**Comment by wkurniawan07** [comment]
This is experienced by an instructor, not a student. Are there more details on this?

**Comment by damithc** [comment]
It was a student, but the code thought it is an instructor. I confirmed it just now.

**Comment by thyageshm** [comment]
Sir are you sure ANY of the students are able to view their team's profile pictures? According to the code none of the students should be able to view their team members' profile pictures

**Comment by thyageshm** [comment]
![image](https://cloud.githubusercontent.com/assets/5160137/18740469/729d6cc0-80dc-11e6-98d6-58c40eeea4fb.png)
The highlighted line only allows instructors to view the student's profile picture. This has to be updated to "both instructors and team members of the student can view the picture"

**Comment by damithc** [comment]
Looks like no student can see the pictures. When I masquerade as a student in my own course, I can see the pictures. That means not only it's checking wrong level permissions, it's also not taking into account the masquerading. I shouldn't be able to see pictures if I'm masquerading as the student.

**Comment by damithc** [comment]
Looks like this feature was not tested properly.

**Comment by damithc** [comment]
@tarun14110 can you fix this?
