### ISSUE TITLE
Instructor: edit question visibility: fix assertion error

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6094]
```
teammates.ui.controller.InstructorFeedbackQuestionEditAction validateQuestionGiverRecipientVisibility:  (InstructorFeedbackQuestionEditAction.java:136)
java.lang.reflect.InvocationTargetException
    at com.google.appengine.runtime.Request.process-e60877bf1213698c(Request.java)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:44)
    at teammates.ui.controller.InstructorFeedbackQuestionEditAction.validateQuestionGiverRecipientVisibility(InstructorFeedbackQuestionEditAction.java:132)
    at teammates.ui.controller.InstructorFeedbackQuestionEditAction.editQuestion(InstructorFeedbackQuestionEditAction.java:80)
    at teammates.ui.controller.InstructorFeedbackQuestionEditAction.execute(InstructorFeedbackQuestionEditAction.java:52)
    at teammates.ui.controller.Action.executeAndPostProcess(Action.java:344)
    at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:64)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:29)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:446)
    at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:453)
    at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:276)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:312)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:304)
    at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:450)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: Contrib Qn Invalid visibility options
    at teammates.common.util.Assumption.fail(Assumption.java:61)
    at teammates.common.util.Assumption.assertTrue(Assumption.java:29)
    at teammates.common.datatransfer.FeedbackContributionQuestionDetails.validateGiverRecipientVisibility(FeedbackContributionQuestionDetails.java:755)
    ... 36 more
```

**Comment by damithc** [comment]
Looks like the UI is sending invalid visibility options

**Comment by mohamed-moanis** [comment]
I tried editing the visibility options for many question types, but can't reproduce the error!
Is there a specific type that is not working or any hints about how to reproduce the issue?

**Comment by damithc** [comment]
It happens occasionally, but not common. So it must be some special combination of factors causing the problem. Perhaps we can try to log more info when the failure happens?

**Comment by mohamed-moanis** [comment]
I traced the stack trace to this check. 
```JavaScript
Assumption.assertTrue("Contrib Qn Invalid visibility options",
                feedbackQuestionAttributes.showResponsesTo.contains(FeedbackParticipantType.RECEIVER)
                == feedbackQuestionAttributes.showResponsesTo.contains(FeedbackParticipantType.RECEIVER_TEAM_MEMBERS)
                && feedbackQuestionAttributes.showResponsesTo.contains(FeedbackParticipantType.RECEIVER_TEAM_MEMBERS)
                == feedbackQuestionAttributes.showResponsesTo.contains(FeedbackParticipantType.OWN_TEAM_MEMBERS));
```

I tried different visibility options in the contribution question type, but I couldn't reproduce that error.

The page JS code enforces that the `Recipient(s)` checkbox is always the same value of the `Giver's Team Members` checkbox - both are checked or unchecked - which satisfies the assertion check.

The only way I was able to reproduce this error is by directly manipulating the `DOM` object and only check one of the two check boxes without the other which caused the problem.

I guess we can fix this, by changing the `Assumption.assertTrue` to if conditions and return error to the user that this combination is not valid.

**Comment by damithc** [comment]
If the error happens once or twice, it's likely a user trying to be clever and manipulating the DOM. This error happens more often than that, at different times. So there is something that causes the problem other than manual DOM manipulation, possibly an oddball browser version or something like that. Next time this happens, I'll try to find more information. We can leave it open for now. 
BTW, thanks for investigating the problem @mohamed-moanis 👍

**Comment by leelunn** [comment]
@damithc seems like you have keen intuition on these things! I'm able to reproduce this error, and I'm looking into a fix.

In the meantime, could you explain why it is required for Recipient(s) and Giver's team members to both be either checked or unchecked?

**Comment by damithc** [comment]
@leelunn can you give a screenshot of the question (including visibility and feedback path) that reproduces the error?

**Comment by leelunn** [comment]
@damithc I can do better than that.  Steps to reproduce:

1. Navigate to a feedback session that contains a Team Contribution Question
2. Enter edit mode for the Contribution Question
3. Using the common visibility options choose any of: Shown anonymously to recipient and instructors, Shown anonymously to recipient, visible to instructors, or Visible to recipient and instructors.
4. Click Save Changes

The assertion in question fails because the showResponsesTo list is not populated with the correct (or without the correct) entries.  I haven't had to time to investigate if this just an issue with the javaScript code not checking or unchecking the correct checkboxes, or if there is a larger problem on the java side of things.

One other important thing that I noticed.  If you save the visibility using common visibility options to "Visible to instructors only" and then edit the question again, only Recipient(s) is selected, which is apparently not suppose to be possible.

I do not know the reason that both of these boxes must be either selected or not selected as a pair.

**Comment by damithc** [comment]
@mohamed-moanis team contribution questions are 'special' in that they have limited flexibility in visibility. Either students can see responses anonymously, or they can't see responses at all. That's basically the only flexibility allowed. If students can see responses, then team members should be able to see them as well because seeing the rating you received is not useful unless you can compare it to team members (it's a relative measure). Most likely the UI doesn't enforce this limited flexibility properly, resulting in a combination the backend considers to be invalid.

**Comment by leelunn** [comment]
@damitch Ok.  To confirm that I understand the expected behaviour, for contribution questions, using the image below as reference, the visibility states should be?

1. Anonymously to recipient and instructors: The visibility options should be: 

Can see answer: Recipient, Giver's Team Members, Instructors 
Can see giver's name: None
Can see recipient's name: Recipient, Giver's Team Members, Instructors

2. Show anonymous to recipient, visible to instructors:

Can see answer: Recipient, Giver's Team Members, Instructors 
Can see giver's name: Instructors
Can see recipient's name: Recipient, Giver's Team Members, Instructors

Visible to instructors only:

Can see answer: Instructors 
Can see giver's name: Instructors
Can see recipient's name: Instructors


4. Visible to recipient and instructors: **Not a valid option for contribution**

![image](https://cloud.githubusercontent.com/assets/5169630/21266444/a808a46e-c37c-11e6-8938-f6c4b5d50fb9.png)

**Comment by damithc** [comment]
@mohamed-moanis 
I think we should limit it to options 2 and 3 only.
* Show anonymous to recipient, visible to instructors
* Visible to instructors only

We can also remove 'custom visibility' from this type of questions.

@YongJieYongJie any input?

**Comment by mohamed-moanis** [comment]
I reproduced the error according to @leelunn  :+1: 

Now option 1, 2, 4 causes the error to show up, while custom visibility and visible to instructor only works fine.

**Comment by mohamed-moanis** [comment]
@damithc 
I agree with what you say, only the contribution question has this restrictions in the backend checks which aren't enforced by the UI.

I have a question, in the current implementation, the "Show anonymous to recipient, visible to instructors" option sends "RECEIVER" and "INSTRUCTOR" as those who can see the responses.
My question is this behavior is wrong? it should be to the team members also?

**Comment by damithc** [comment]
@mohamed-moanis Let's see if @YongJieYongJie can shed any light on that. He is the one who worked with this part of the code most recently.
Also, @JosephineKwa any insights?

**Comment by leelunn** [comment]
@mohamed-moanis Are you working to resolve this issue or can I take this on?

**Comment by damitch** [comment]
I think my email address was added by mistake.

**Comment by damithc** [comment]
@damitch yes it's a typo (your username is one letter away from mine). Please unsubscribe from this issue to stop receiving emails from this issue.

**Comment by mohamed-moanis** [comment]
@leelunn  as @damithc said, we are waiting for input from @YongJieYongJie .

Or we can start making a PR

**Comment by mohamed-moanis** [comment]
@damithc  I can do a hot fix for all the options for now to silence the error. Then we can open another issue about which options should be valid for this type of question?

**Comment by damithc** [comment]
@leelunn go ahead with the PR

**Comment by leelunn** [comment]
@damithc Roger.  Working on it.

**Comment by whipermr5** [comment]
This looks like the same issue as #6619; I'm hoping #6669 has already fixed it. Have there been any occurrences since 16 March?

**Comment by damithc** [comment]
Last occurrence was March 15th. Closing.
