### ISSUE TITLE
Local tests failing

### ISSUE THREAD

**Issue by AnaghHegde** [TEAMMATES/teammates#6285]
This is what i am getting after the local test.I dont know why its saying unable to connect to localhost because the dev server is in running state.

[=============================teammates.test.cases.ui.browsertests.MashupPageUiTest=============================]
Initializing Selenium: Using Firefox.
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
XPCOMGlueLoad error for file /opt/firefox/libmozgtk.so:
libgtk-3.so.0: cannot open shared object file: No such file or directory
Couldn't load XPCOM.

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:124)
	at teammates.test.pageobjects.Browser.createWebDriver(Browser.java:87)
	at teammates.test.pageobjects.Browser.<init>(Browser.java:37)
	at teammates.test.pageobjects.BrowserPool.requestInstance(BrowserPool.java:94)
	at teammates.test.pageobjects.BrowserPool.getBrowser(BrowserPool.java:40)
	at teammates.test.cases.ui.browsertests.MashupPageUiTest.classSetup(MashupPageUiTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

local-tests
Total tests run: 1, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 1

**Comment by chowyb** [comment]
Are you using a version of Firefox between 38.0.5 and 46.0.1?

On another note, are you getting similar errors when running `Travis tests`?

**Comment by AnaghHegde** [comment]
@chowyb yes my firefox version is 46.0 .No i am not getting the same error

**Comment by damithc** [comment]
Is this helpful? https://support.mozilla.org/en-US/questions/1121133

**Comment by AnaghHegde** [comment]
@damithc My firefox is working fine and  localhost:8888 is also working fine/I dont know why its saying unable to connect to localhost

**Comment by damithc** [comment]
Tests need to connect to Firefox using the WebDriver. Just because the FF works for normal manual access doesn't mean tests will work.

**Comment by AnaghHegde** [comment]
@damithc so then the problem is with FF only?

**Comment by damithc** [comment]
@AnaghHegde the error specifically mentions `firefox`, so I suspect it is.

**Comment by AnaghHegde** [comment]
@damithc ok i ll try to fix it

**Comment by wkurniawan07** [comment]
From this error message section:
```
XPCOMGlueLoad error for file /opt/firefox/libmozgtk.so:
libgtk-3.so.0: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```
I suspect it is a Linux-specific error, but I'm afraid I cannot help since I'm not a Linux-based developer.

**Comment by AnaghHegde** [comment]
@wkurniawan07 its ok. Now i have switched from linux to windows environment.Thanks for the help.

**Comment by wkurniawan07** [comment]
@AnaghHegde noted on that, so closing the issue.
