### ISSUE TITLE
Exception thrown trying to retrieve CourseStudent: IllegalBlockSizeException

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6562]
Found in the log of the live server V5.94

```
Error Message: teammates.common.util.Logger severe: Exception thrown trying to retrieve CourseStudent

java.lang.RuntimeException: javax.crypto.IllegalBlockSizeException: Input length must be multiple of 16 when decrypting with padded cipher
at teammates.common.util.StringHelper.decrypt(StringHelper.java:147)
at teammates.storage.api.StudentsDb.getStudentForRegistrationKey(StudentsDb.java:190)
at teammates.logic.core.StudentsLogic.getStudentForRegistrationKey(StudentsLogic.java:93)
at teammates.logic.api.Logic.getStudentForRegistrationKey(Logic.java:815)
at teammates.ui.controller.Action.authenticateNotLoggedInUser(Action.java:196)
at teammates.ui.controller.Action.authenticateAndGetActualUser(Action.java:144)
at teammates.ui.controller.Action.authenticateUser(Action.java:125)
at teammates.ui.controller.Action.init(Action.java:89)
at teammates.ui.controller.ActionFactory.getAction(ActionFactory.java:150)
at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:64)
Caused by: javax.crypto.IllegalBlockSizeException: Input length must be multiple of 16 when decrypting with padded cipher
at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:750)
at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:676)
at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:313)
at javax.crypto.Cipher.doFinal(Cipher.java:2131)
at teammates.common.util.StringHelper.decrypt(StringHelper.java:144)
```

**Comment by damithc** [comment]
I wonder if this can be triggered by a bot trying to guess the join key e.g.
`/page/studentCourseJoinAuthentication?key=RANDOMKEY`
