### ISSUE TITLE
 Failed to instantiate Feedback*QuestionDetails instance for CONTRIB question type

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6619]
v5.95
Found in log (and also reported by user). It's odd that the error message mentions two message types: CONTRIB and rubric

```
0. Error Type: ERROR

Error Message: teammates.common.util.Logger severe: 
java.lang.reflect.InvocationTargetException
at com.google.appengine.runtime.Request.process-73b769498349bb3a(Request.java)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:42)
at teammates.ui.controller.InstructorFeedbackQuestionEditAction.validateQuestionGiverRecipientVisibility(InstructorFeedbackQuestionEditAction.java:129)
at teammates.ui.controller.InstructorFeedbackQuestionAddAction.validateQuestionGiverRecipientVisibility(InstructorFeedbackQuestionAddAction.java:76)
at teammates.ui.controller.InstructorFeedbackQuestionAddAction.execute(InstructorFeedbackQuestionAddAction.java:51)
at teammates.ui.controller.Action.executeAndPostProcess(Action.java:365)
at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:66)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at org.mortbay.jetty.Server.handle(Server.java:326)
at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: Contrib Qn Invalid visibility options
at teammates.common.util.Assumption.fail(Assumption.java:61)
at teammates.common.util.Assumption.assertTrue(Assumption.java:29)
at teammates.common.datatransfer.FeedbackContributionQuestionDetails.validateGiverRecipientVisibility(FeedbackContributionQuestionDetails.java:755)
... 34 more


1. Error Type: ERROR

Error Message: teammates.common.util.Logger severe: TEAMMATESLOG|||page|||System Error Report|||true|||Unknown|||Unknown|||synthese|||Unknown|||TEAMMATES (5.95.02): New System Exception: Failed to instantiate Feedback*QuestionDetails instance for CONTRIB question type.
Show/Hide Details >>
Error Message 

        Failed to instantiate Feedback*QuestionDetails instance for CONTRIB question type.

    



Actual user 

synthese 



Request Method 

POST 



User Agent 

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 



Request Url 

https://teammatesv4.appspot.com/page/instructorFeedbackQuestionAdd 



Request Path 

/page 



Request Parameters 

{showresponsesto::RECEIVER,INSTRUCTORS, constSumPointsPerOption::false, rubricNumRows::2, rubricChoice-3::Strongly Agree, numofrecipientstype::max, rubricChoice-0::Strongly Disagree, constSumToRecipients::false, constSumOption-1::, rubricDesc-0-3::Initiates discussions frequently, and engages the team., constSumOption-0::, rubricDesc-0-2::Takes part in discussions and sometimes initiates discussions., rubricChoice-2::Agree, rubricDesc-0-1::Occasionally responds, but never initiates discussions., rubricChoice-1::Disagree, rubricDesc-0-0::Rarely or never responds., generatedOptions::NONE//NONE//NONE, numscalestep::1, numofrecipients::1, recipienttype::OWN_TEAM_MEMBERS_INCLUDING_SELF, constSumPointsForEachOption::100, constSumPoints::100, showrecipientto::RECEIVER,INSTRUCTORS, rubricNumCols::4, questiontext::L'étudiant démontre une capacité de synthèse lorsqu'il présente sa recherche lors des rencontres d’équipe., mcqOption-1::, questiondescription::

Identifier les informations nécessaires, ne pas s'éterniser sur des détails, sélectionner les informations utiles, formuler des hypothèses lors de l’analyse initiale du problème.

, showgiverto::INSTRUCTORS, mcqOption-0::, questionnum::1//1, rubricSubQn-0::This student participates well in online discussions., courseid::101-111-AH, recommendedlength::, rubricSubQn-1::This student completes assigned tasks on time., noofchoicecreated::2//2//2//2, constSumPointsForEachRecipient::100, rubricDesc-1-3::Tasks are always completed before the deadline., rubricWeight-3::0, rankOption-1::, rubricWeight-2::0, rubricDesc-1-0::Rarely or never completes tasks., rankOption-0::, rubricWeight-1::0, rubricDesc-1-1::Often misses deadlines., rubricWeight-0::0, rubricDesc-1-2::Occasionally misses deadlines., numscalemin::1, fsname::Évaluation par les pairs Étape 1, msqOption-0::, msqOption-1::, receiverLeaderCheckbox::RECEIVER, questiontype::CONTRIB, numscalemax::5, givertype::STUDENTS, user::synthese} 


Stack Trace 



java.lang.AssertionError: Failed to instantiate Feedback*QuestionDetails instance for CONTRIB question type.
	at teammates.common.util.Assumption.fail(Assumption.java:61)
	at teammates.ui.controller.InstructorFeedbackQuestionEditAction.validateQuestionGiverRecipientVisibility(InstructorFeedbackQuestionEditAction.java:135)
	at teammates.ui.controller.InstructorFeedbackQuestionAddAction.validateQuestionGiverRecipientVisibility(InstructorFeedbackQuestionAddAction.java:76)
	at teammates.ui.controller.InstructorFeedbackQuestionAddAction.execute(InstructorFeedbackQuestionAddAction.java:51)

	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:365)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:66)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:145)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:559)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:519)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:489)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:238)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by wkurniawan07** [comment]
@whipermr5 do you want to explore this? You don't have to be the one to eventually fix it.

**Comment by whipermr5** [comment]
Okay!

**Comment by whipermr5** [comment]
Notes to self as I figure it out [WIP]

What the log is saying:

`AssertTrue` on this condition is failing:
`feedbackQuestionAttributes.showResponsesTo.contains(FeedbackParticipantType.RECEIVER) == feedbackQuestionAttributes.showResponsesTo.contains(FeedbackParticipantType.RECEIVER_TEAM_MEMBERS)
&&
feedbackQuestionAttributes.showResponsesTo.contains(FeedbackParticipantType.RECEIVER_TEAM_MEMBERS) == feedbackQuestionAttributes.showResponsesTo.contains(FeedbackParticipantType.OWN_TEAM_MEMBERS)`

Value of `showresponsesto`: `RECEIVER,INSTRUCTORS`

This does not contain `RECEIVER_TEAM_MEMBERS` nor `OWN_TEAM_MEMBERS` even though it contains `RECEIVER`, thus failing the assert.

Deeper issue:

A `RUBRIC` question is being submitted as a `CONTRIB`, therefore it's failing the `CONTRIB` `validateGiverRecipientVisibility` test (this test does not need to be run on `RUBRIC` questions). This is another instance of invalid POST data submitted by client browsers. Will need to investigate the frontend code further.

**Comment by damithc** [comment]
To give some context, this user encountered the same error several times when he was trying to add the first question to an empty session. After few tries, he gave up and emailed me.

**Comment by damithc** [comment]
Another case, this time session already has some questions and the user was trying to add a team contribution question. When I tried it (for the same session), i was able to add without a problem, but the use may have used different settings for the question. Could it be a case of UI allowing settings that are not acceptable to the question type?

```
0. Error Type: ERROR

Error Message: teammates.common.util.Logger severe:
java.lang.reflect.InvocationTargetException
at com.google.appengine.runtime.Request.process-d8c5b3cde9d9ef65(Request.java)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:42)
at teammates.ui.controller.InstructorFeedbackQuestionEditAction.validateQuestionGiverRecipientVisibility(InstructorFeedbackQuestionEditAction.java:129)
at teammates.ui.controller.InstructorFeedbackQuestionAddAction.validateQuestionGiverRecipientVisibility(InstructorFeedbackQuestionAddAction.java:76)
at teammates.ui.controller.InstructorFeedbackQuestionAddAction.execute(InstructorFeedbackQuestionAddAction.java:51)
at teammates.ui.controller.Action.executeAndPostProcess(Action.java:365)
at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:66)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at org.mortbay.jetty.Server.handle(Server.java:326)
at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: Contrib Qn Invalid visibility options
at teammates.common.util.Assumption.fail(Assumption.java:61)
at teammates.common.util.Assumption.assertTrue(Assumption.java:29)
at teammates.common.datatransfer.questions.FeedbackContributionQuestionDetails.validateGiverRecipientVisibility(FeedbackContributionQuestionDetails.java:761)
... 34 more

1. Error Type: ERROR

Error Message: teammates.common.util.Logger severe: TEAMMATESLOG|||page|||System Error Report|||true|||Unknown|||Unknown|||usergoogleidremoved|||Unknown|||TEAMMATES (5.96.01): New System Exception: Failed to instantiate Feedback*QuestionDetails instance for CONTRIB question type.
Show/Hide Details >>

Error Message


        Failed to instantiate Feedback*QuestionDetails instance for CONTRIB question type.

    




Actual user

usergoogleidremoved


Request Method

POST


User Agent

Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36


Request Url

https://teammatesv4.appspot.com/page/instructorFeedbackQuestionAdd


Request Path

/page


Request Parameters

{showresponsesto::RECEIVER,INSTRUCTORS, constSumPointsPerOption::false, rubricNumRows::2, rubricChoice-3::Strongly Agree, numofrecipientstype::max, rubricChoice-0::Strongly Disagree, constSumToRecipients::false, constSumOption-1::, rubricDesc-0-3::Initiates discussions frequently, and engages the team., constSumOption-0::, rubricDesc-0-2::Takes part in discussions and sometimes initiates discussions., rubricChoice-2::Agree, rubricDesc-0-1::Occasionally responds, but never initiates discussions., rubricChoice-1::Disagree, rubricDesc-0-0::Rarely or never responds., generatedOptions::NONE//NONE//NONE, numscalestep::1, numofrecipients::1, recipienttype::OWN_TEAM_MEMBERS_INCLUDING_SELF, constSumPointsForEachOption::100, constSumPoints::100, showrecipientto::RECEIVER,INSTRUCTORS, rubricNumCols::4, questiontext::Rank each individual team member using a scale of 1-10. Explain your reasons for the assigned rankings and provide at least two BETs and one BEAR that will help this team member with the next team project., mcqOption-1::, questiondescription::, showgiverto::INSTRUCTORS, mcqOption-0::, questionnum::25//25, rubricSubQn-0::This student participates well in online discussions., courseid::SP17MGT4161, recommendedlength::, rubricSubQn-1::This student completes assigned tasks on time., noofchoicecreated::2//2//2//2, constSumPointsForEachRecipient::100, rubricDesc-1-3::Tasks are always completed before the deadline., rubricWeight-3::0, rankOption-1::, rubricWeight-2::0, rubricDesc-1-0::Rarely or never completes tasks., rankOption-0::, rubricWeight-1::0, rubricDesc-1-1::Often misses deadlines., rubricWeight-0::0, rubricDesc-1-2::Occasionally misses deadlines., numscalemin::1, fsname::Team 1 Learning Module Peer Evaluation, msqOption-0::, msqOption-1::, receiverLeaderCheckbox::RECEIVER, questiontype::CONTRIB, numscalemax::5, givertype::STUDENTS, user::usergoogleidremoved}


Stack Trace


java.lang.AssertionError: Failed to instantiate Feedback*QuestionDetails instance for CONTRIB question type.
	at teammates.common.util.Assumption.fail(Assumption.java:61)
	at teammates.ui.controller.InstructorFeedbackQuestionEditAction.validateQuestionGiverRecipientVisibility(InstructorFeedbackQuestionEditAction.java:135)
	at teammates.ui.controller.InstructorFeedbackQuestionAddAction.validateQuestionGiverRecipientVisibility(InstructorFeedbackQuestionAddAction.java:76)
	at teammates.ui.controller.InstructorFeedbackQuestionAddAction.execute(InstructorFeedbackQuestionAddAction.java:51)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:365)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:66)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:145)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:559)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:519)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:489)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:238)
	at java.lang.Thread.run(Thread.java:745)


|||/page/instructorFeedbackQuestionAdd|||usergoogleidremoved%20170222102032372
```

**Comment by whipermr5** [comment]
Ohh it's much more reproducible than I thought. Just need to add a new (or edit an existing) team contrib question and change the visibility to any of the predefined options other than `Visible to instructors only` and save.

**Comment by whipermr5** [comment]
I'm trying to figure out the logic behind the [condition](https://github.com/TEAMMATES/teammates/blob/9940d89dde675b7e17e84311cbd83aa7a337863e/src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java#L761) that's failing in the validity check - why must `RECEIVER` imply `RECEIVER_TEAM_MEMBERS` and ``RECEIVER_TEAM_MEMBERS`` imply `OWN_TEAM_MEMBERS `?

**Comment by whipermr5** [comment]
Also, changing visibility automatically unchecks `Allow response giver to select 'Not Sure' as the answer`, which looks like another bug.

**Comment by damithc** [comment]
Contribution questions should allows only two visibility settings: 
1. Instructors can see everything. Students see their own and other team member values anonymously.
2. Instructors can see everything. Students cannot see anything.

Any other setting will fail the validation. Probably the front-end is not enforcing this correctly.

**Comment by whipermr5** [comment]
I see. Out of the 4 available predefined options:

1. Shown anonymously to recipient and instructors
2. Shown anonymously to recipient, visible to instructors
3. Visible to instructors only
4. Visible to recipient and instructors

we need to hide the first and last ones then. The second one also has to be fixed as it's not generating `RECEIVER_TEAM_MEMBERS`. The `fixContribQnGiverRecipient` method looks handy for this.

**Comment by damithc** [comment]
I'm ok to go straight to custom too (i.e. not allow any predefined options).

**Comment by whipermr5** [comment]
Would it not be better to disable custom instead, since there are only exactly two valid settings? The custom options allow other settings, e.g. instructors cannot see anything, other students can see everything. Showing only the two valid settings in the dropdown would be clearer. (On a side note, these other settings seem to be allowed by the backend; I guess this is a bug?)

**Comment by damithc** [comment]
> Would it not be better to disable custom instead, since there are only exactly two valid settings? The custom options allow other settings, e.g. instructors cannot see anything, other students can see everything. Showing only the two valid settings in the dropdown would be clearer.

Yes, that's true. The ideal is to show just the two options that are permitted.


> (On a side note, these other settings seem to be allowed by the backend; I guess this is a bug? Or are these allowed? If they are, straight to custom would be good.)

Yes, probably a bug.
