### ISSUE TITLE
InstructorStudentListPageUiTest failing on live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6620]
v5.96

```
java.lang.AssertionError: expected:<CCSDetailsUiT.alice.tmms@gmail.tmt
benny.c.tmms@gmail.tmt
hugh.i.tmms@gmail.tmt
ivan.j.tmms@gmail.tmt
jack.k.tmms@gmail.tmt
CCSDetailsUiT.charlie.tmms@gmail.tmt
denny.c.tmms@gmail.tmt> but was:<CCSDetailsUiT.alice.tmms@gmail.tmt
benny.c.tmms@gmail.tmt
hugh.i.tmms@gmail.tmt
ivan.j.tmms@gmail.tmt
jack.k.tmms@gmail.tmt
CCSDetailsUiT.charlie.tmms@gmail.tmt
denny.c.tmms@gmail.tmt>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at teammates.test.cases.BaseTestCase.assertEquals(BaseTestCase.java:133)
	at teammates.test.cases.browsertests.InstructorStudentListPageUiTest.testContent(InstructorStudentListPageUiTest.java:110)
	at teammates.test.cases.browsertests.InstructorStudentListPageUiTest.testAll(InstructorStudentListPageUiTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

```

**Comment by damithc** [comment]
@xpdavid can have a look? Looks like it's related to the new 'copy emails to clipboard' function.

**Comment by damithc** [comment]
Looks like AppVeyor is also failing on the same test, so it could be a Windows vs Unix thing.

**Comment by xpdavid** [comment]
@damithc I guess it's the whitespace thing. Let's me find a Windows machine to try.

**Comment by damithc** [comment]
@xpdavid this still seems to be failing on the live server.

**Comment by xpdavid** [comment]
hmm, Appveyor shows `passing`. Same error message?

**Comment by damithc** [comment]
Yes. Note that I'm running tests on a Windows box while the live server is running in a Linux/Unix box. Not sure if that has any effect.

**Comment by damithc** [comment]
@xpdavid Hang on, I may have deployed an older version of the code.

**Comment by wkurniawan07** [comment]
Deployment should not be a reason because the fix for the issue only concerns test code.

The issue, of course, could be that the test code that was run is the version before the fix.

**Comment by damithc** [comment]
> Deployment should not be a reason because the fix for the issue only concerns test code.

My whole code base was v5.96 instead of at v5.97, so the tests were outdated too.

**Comment by damithc** [comment]
The test is passing with the latest code. Apologies for the false alarm @xpdavid
