### ISSUE TITLE
Help Request: CI test incomplete

### ISSUE THREAD

**Issue by keenandubois** [TEAMMATES/teammates#6798]
- **Operating System: macOS Yosemite 10.10.5**
- **JDK Version: Java 1.7**
- **Eclipse: Luna 4.4.1**
- **Firefox 46.0.1**

**Errors occurring during CI tests**
Reached Phase B, step 2 of setup.  In running testNG cases, my setup passes all local tests.  However, when running CI tests I get console output:
![screen shot 2017-03-12 at 8 17 22 pm](https://cloud.githubusercontent.com/assets/5413618/23837657/063613f4-0762-11e7-9004-913c7e6718d4.png)
No tests explicitly fail, nor do they pass or skip, they just seem to stop.

**Attempts to resolve the problem**
Refresh and clean project, resync with master branch, reconfigure path to Firefox executable, doublecheck that Java 7 SDK is linked in current Eclipse build.

New to the project and excited to get it up and running – any & all help appreciated :)

**Comment by damithc** [comment]
@keenandubois I have no answer, but it might help to post the full stack trace (preferably as text) so that we know where the exception originated (that part is cut off in your screenshot).

**Comment by keenandubois** [comment]
@damithc Certainly.  Here's the full trace – my apologies for the truncated version in the original post:

Mar 13, 2017 1:21:25 PM org.datanucleus.plugin.NonManagedPluginRegistry resolveConstraints
INFO: Bundle "org.datanucleus.jpa" has an optional dependency to "org.datanucleus.enhancer" but it cannot be resolved
Mar 13, 2017 1:21:25 PM org.datanucleus.plugin.NonManagedPluginRegistry resolveConstraints
INFO: Bundle "org.datanucleus" has an optional dependency to "org.eclipse.equinox.registry" but it cannot be resolved
Mar 13, 2017 1:21:25 PM org.datanucleus.plugin.NonManagedPluginRegistry resolveConstraints
INFO: Bundle "org.datanucleus" has an optional dependency to "org.eclipse.core.runtime" but it cannot be resolved
Mar 13, 2017 1:21:25 PM org.datanucleus.PersistenceConfiguration setProperty
INFO: Property datanucleus.rdbms.stringDefaultLength unknown - will be ignored
Mar 13, 2017 1:21:25 PM org.datanucleus.PersistenceConfiguration setProperty
INFO: Property datanucleus.rdbms.sql.allowAllSQLStatements unknown - will be ignored
Mar 13, 2017 1:21:25 PM org.datanucleus.PersistenceConfiguration setProperty
INFO: Property datanucleus.appengine.autoCreateDatastoreTxns unknown - will be ignored
Mar 13, 2017 1:21:25 PM org.datanucleus.ObjectManagerFactoryImpl logConfiguration
INFO: ================= Persistence Configuration ===============
Mar 13, 2017 1:21:25 PM org.datanucleus.ObjectManagerFactoryImpl logConfiguration
INFO: DataNucleus Persistence Factory - Vendor: "DataNucleus"  Version: "1.1.5"
Mar 13, 2017 1:21:25 PM org.datanucleus.ObjectManagerFactoryImpl logConfiguration
INFO: DataNucleus Persistence Factory initialised for datastore URL="appengine" driver="" userName=""
Mar 13, 2017 1:21:25 PM org.datanucleus.ObjectManagerFactoryImpl logConfiguration
INFO: ===========================================================
Mar 13, 2017 1:21:25 PM org.datanucleus.PersistenceConfiguration setProperty
INFO: Property datanucleus.query.cached unknown - will be ignored
org.testng.TestNGException: 
An error occurred while instantiating class teammates.test.cases.action.AllActionsAccessControlTest: null
	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:401)
	at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:302)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:118)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:183)
	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:128)
	at org.testng.TestRunner.initMethods(TestRunner.java:413)
	at org.testng.TestRunner.init(TestRunner.java:239)
	at org.testng.TestRunner.init(TestRunner.java:209)
	at org.testng.TestRunner.<init>(TestRunner.java:164)
	at org.testng.remote.support.RemoteTestNG6_5$1.newTestRunner(RemoteTestNG6_5.java:27)
	at org.testng.remote.support.RemoteTestNG6_5$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_5.java:63)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:584)
	at org.testng.SuiteRunner.init(SuiteRunner.java:159)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:113)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1274)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1261)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.ExceptionInInitializerError
	at teammates.common.util.StringHelper.encrypt(StringHelper.java:127)
	at teammates.test.cases.action.AllActionsAccessControlTest.<clinit>(AllActionsAccessControlTest.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:29)
	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:389)
	... 20 more
Caused by: java.lang.NullPointerException
	at teammates.common.util.Url.trimTrailingSlash(Url.java:78)
	at teammates.common.util.Config.<clinit>(Config.java:69)
	... 28 more

**Comment by xpdavid** [comment]
> Caused by: java.lang.NullPointerException
at teammates.common.util.Url.trimTrailingSlash(Url.java:78)
at teammates.common.util.Config.(Config.java:69)

Seems like the configuration file is not set up properly.

**Comment by keenandubois** [comment]
I thought I had, but it looks like I'll need to redo the setup.  Thanks for the catch!

**Comment by xpdavid** [comment]
Solved.
