### ISSUE TITLE
GAE Deployment Error

### ISSUE THREAD

**Issue by angelosdmg** [TEAMMATES/teammates#7006]
Hello everybody,
I'm trying to deploy the app but I get this error.

I'd be grateful if you could help me.

![2017-03-31 1](https://cloud.githubusercontent.com/assets/15040082/24558819/303f7fae-1645-11e7-9080-70806e153e6a.png)

error logfile:
Unable to update:
com.google.appengine.tools.admin.HttpIoException: Error posting to URL: https://appengine.google.com/api/queue/update?app_id=teammates-angeldmg&version=4-18&
400 Bad Request
Invalid queue configuration. Must be fewer than or equal to 10 non-default entries

	at com.google.appengine.tools.admin.AbstractServerConnection.send1(AbstractServerConnection.java:343)
	at com.google.appengine.tools.admin.AbstractServerConnection.send(AbstractServerConnection.java:289)
	at com.google.appengine.tools.admin.AbstractServerConnection.post(AbstractServerConnection.java:268)
	at com.google.appengine.tools.admin.NoLoggingClientDeploySender.send(NoLoggingClientDeploySender.java:35)
	at com.google.appengine.tools.admin.AppVersionUpload.send(AppVersionUpload.java:1168)
	at com.google.appengine.tools.admin.AppVersionUpload.updateQueue(AppVersionUpload.java:551)
	at com.google.appengine.tools.admin.AppVersionUpload.doUpload(AppVersionUpload.java:207)
	at com.google.appengine.tools.admin.AppAdminImpl.doUpdate(AppAdminImpl.java:572)
	at com.google.appengine.tools.admin.AppAdminImpl.update(AppAdminImpl.java:58)
	at com.google.appengine.tools.admin.AppCfg$UpdateAction.execute(AppCfg.java:1443)
	at com.google.appengine.tools.admin.AppCfg.executeAction(AppCfg.java:348)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:222)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:126)
	at com.google.appengine.tools.admin.AppCfg.main(AppCfg.java:122)
com.google.appengine.tools.admin.AdminException: Unable to update app: Error posting to URL: https://appengine.google.com/api/queue/update?app_id=teammates-angeldmg&version=4-18&
400 Bad Request
Invalid queue configuration. Must be fewer than or equal to 10 non-default entries

	at com.google.appengine.tools.admin.AppAdminImpl.doUpdate(AppAdminImpl.java:578)
	at com.google.appengine.tools.admin.AppAdminImpl.update(AppAdminImpl.java:58)
	at com.google.appengine.tools.admin.AppCfg$UpdateAction.execute(AppCfg.java:1443)
	at com.google.appengine.tools.admin.AppCfg.executeAction(AppCfg.java:348)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:222)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:126)
	at com.google.appengine.tools.admin.AppCfg.main(AppCfg.java:122)
Caused by: com.google.appengine.tools.admin.HttpIoException: Error posting to URL: https://appengine.google.com/api/queue/update?app_id=teammates-angeldmg&version=4-18&
400 Bad Request
Invalid queue configuration. Must be fewer than or equal to 10 non-default entries

	at com.google.appengine.tools.admin.AbstractServerConnection.send1(AbstractServerConnection.java:343)
	at com.google.appengine.tools.admin.AbstractServerConnection.send(AbstractServerConnection.java:289)
	at com.google.appengine.tools.admin.AbstractServerConnection.post(AbstractServerConnection.java:268)
	at com.google.appengine.tools.admin.NoLoggingClientDeploySender.send(NoLoggingClientDeploySender.java:35)
	at com.google.appengine.tools.admin.AppVersionUpload.send(AppVersionUpload.java:1168)
	at com.google.appengine.tools.admin.AppVersionUpload.updateQueue(AppVersionUpload.java:551)
	at com.google.appengine.tools.admin.AppVersionUpload.doUpload(AppVersionUpload.java:207)
	at com.google.appengine.tools.admin.AppAdminImpl.doUpdate(AppAdminImpl.java:572)
	... 6 more

**Comment by shrut1996** [comment]
@angelosdmg  Try Enable billing and try again and also set your spending limit to zero if you don't want to be charged. It worked for me atleast after the same error :)

**Comment by HirdayGupta** [comment]
@shrut1996 thanks this seems to solve the problem!
