### ISSUE TITLE
InstructorFeedbackResultsPageUiTest unstable on local dev server

### ISSUE THREAD

**Issue by samsontmr** [TEAMMATES/teammates#7064]
**Environment**

`master` branch from commit 90b40c0e1 onwards

**Trace**
```
org.openqa.selenium.TimeoutException: Timed out after 15 seconds waiting for visibility of [[FirefoxDriver: firefox on WINDOWS (c7774121-8c0c-4cec-9426-8ff7a40e4faa)] -> css selector: .panel-heading+.panel-collapse]
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'DESKTOP-L2LIUI1', ip: '192.168.2.4', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.7.0_80'
Session ID: c7774121-8c0c-4cec-9426-8ff7a40e4faa
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=46.0.1}]

	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:261)
	at teammates.test.pageobjects.AppPage.waitForElementVisibility(AppPage.java:218)
	at teammates.test.pageobjects.InstructorFeedbackResultsPage.waitForPanelsToExpand(InstructorFeedbackResultsPage.java:282)
	at teammates.test.pageobjects.InstructorFeedbackResultsPage.waitForPageToLoad(InstructorFeedbackResultsPage.java:64)
	at teammates.test.pageobjects.InstructorFeedbackResultsPage.expandPanels(InstructorFeedbackResultsPage.java:152)
	at teammates.test.cases.browsertests.InstructorFeedbackResultsPageUiTest.loginToInstructorFeedbackResultsPage(InstructorFeedbackResultsPageUiTest.java:710)
	at teammates.test.cases.browsertests.InstructorFeedbackResultsPageUiTest.refreshTestData(InstructorFeedbackResultsPageUiTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:601)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```
@leeyimin is encountering this as well.

**Comment by boxin-yang** [comment]
Hi @samsontmr @leeyimin , this problem can be solved by running npm run build . There's been some update and refactoring on js files and U need to update it with npm run build. (The commit that refactored the js code is [Move all document.ready functions to just one file per page #7002 ](https://github.com/TEAMMATES/teammates/pull/7004/commits/0e3d9d7adb9eae4dec4a80ab46cacc77c4b99f11)

**Comment by samsontmr** [comment]
Great, thanks @boxin-yang! Marking this issue as resolved.
