### ISSUE TITLE
Unable to pass all tests. (help) 

### ISSUE THREAD

**Issue by basitsattar** [TEAMMATES/teammates#7075]
- MacOs Sierra
- jdk : 1.70.80
- Eclipse Neon 3
- Firefox 45.0

**What I was trying to do / What I need help with**

I have set up teammates locally on my computer and have solved a few issues but some tests are failing. I have also tried with the default branch which has no changes but these two tests are failing in that branch too.

Here is the stack trace from my ./gradlew appengineRun ciTests

`org.gradle.messaging.remote.internal.PlaceholderException: Unable to locate element: {"method":"class name","selector":"bootbox-close-button"}
Command duration or timeout: 235 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'Abduls-MacBook-Pro.local', ip: '10.99.21.50', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.3', java.version: '1.7.0_80'
*** Element info: {Using=class name, value=bootbox-close-button}
Session ID: 1856d731-ff27-784c-a7f1-e3695bb5dc80
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=33.0}]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java:-2)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
        at org.openqa.selenium.remote.RemoteWebDriver.findElementByClassName(RemoteWebDriver.java:477)
        at org.openqa.selenium.By$ByClassName.findElement(By.java:391)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
        at teammates.test.pageobjects.AppPage.waitForModalPresence(AppPage.java:296)
        at teammates.test.pageobjects.AppPage.clickAndConfirmWithoutWaitingForModalDisappearance(AppPage.java:662)
        at teammates.test.pageobjects.InstructorCourseStudentDetailsEditPage.fillStudentDetailsForm(InstructorCourseStudentDetailsEditPage.java:84)
        at teammates.test.pageobjects.InstructorCourseStudentDetailsEditPage.submitUnsuccessfully(InstructorCourseStudentDetailsEditPage.java:54)
        at teammates.test.cases.browsertests.InstructorCourseStudentDetailsEditPageUiTest.testInputValidation(InstructorCourseStudentDetailsEditPageUiTest.java:74)
        at teammates.test.cases.browsertests.InstructorCourseStudentDetailsEditPageUiTest.testAll(InstructorCourseStudentDetailsEditPageUiTest.java:29)
        ...

Failed suite [Failed suite [Failed suite [ci-tests]]] > parallel-ui-tests(failed)(failed)(failed) > teammates.test.cases.browsertests.InstructorCourseStudentDetailsEditPageUiTest.testAll                                                     FAILED
    org.openqa.selenium.NoSuchElementException at InstructorCourseStudentDetailsEditPageUiTest.java:74
        Caused by: org.openqa.selenium.NoSuchElementException

org.gradle.messaging.remote.internal.PlaceholderException: document.getElementsByClassName(...)[0].getElementsByTagName(...)[0] is undefined
Command duration or timeout: 7 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'Abduls-MacBook-Pro.local', ip: '10.99.21.50', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.3', java.version: '1.7.0_80'
Session ID: 5a4e7be1-a7c3-e84b-97cb-492b465be58d
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=33.0}]
   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java:-2)
   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
   at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
   at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
   at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
   at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:577)
   at teammates.test.pageobjects.AppPage.executeScript(AppPage.java:347)
   at teammates.test.pageobjects.InstructorFeedbackResultsPage.hoverClickAndViewPhotoOnTableCell(InstructorFeedbackResultsPage.java:422)
   at teammates.test.pageobjects.InstructorFeedbackResultsPage.hoverClickAndViewRecipientPhotoOnTableCell(InstructorFeedbackResultsPage.java:442)
   at teammates.test.cases.browsertests.InstructorFeedbackResultsPageUiTest.testViewPhotoAndAjaxForLargeScaledSession(InstructorFeedbackResultsPageUiTest.java:364)
   ...

Failed suite [Failed suite [Failed suite [ci-tests]]] > parallel-ui-tests(failed)(failed)(failed) > teammates.test.cases.browsertests.InstructorFeedbackResultsPageUiTest.testViewPhotoAndAjaxForLargeScaledSession                            FAILED
    org.openqa.selenium.WebDriverException at InstructorFeedbackResultsPageUiTest.java:364
        Caused by: org.openqa.selenium.WebDriverException`

**Attempts to resolve the problem**

I have tried with the master branch which is same as the upstream master branch and have also tried by cloning the teammates repository separately but these two tests are failing in that branch too.

**Comment by whipermr5** [comment]
Hey @basitsattar! Even though it's less than ideal, it's normal behaviour haha. The first one can probably be resolved by retrying a few more times. The second one too (with a lot more retries), though it's currently being made more stable in #7068. In our CI build, tests are retried up to four times before failing.

**Comment by basitsattar** [comment]
@whipermr5 
I have tried running the tests multiple times. In my first test run, there were 5 failed tests, which were reduced to 3 in the second run. One of them passed in third run and one in 5th run and now the only failed test is InstructorFeedbackResultsPageUiTest.testViewPhotoAndAjaxForLargeScaledSession. 

You can also see the log in [travis ci here.](https://travis-ci.org/TEAMMATES/teammates/builds/220026763)

**Comment by whipermr5** [comment]
👍 Wait for #7068 to get merged. In the meantime, it's okay to ignore the failing test.

**Comment by basitsattar** [comment]
ok. Thanks :)
