### ISSUE TITLE
I am getting error while running tests. What is issue here ?

### ISSUE THREAD

**Issue by Devmassnk** [TEAMMATES/teammates#7119]
[TestNG] Running:
  /tmp/testng-eclipse-1868599205/testng-customsuite.xml

[=============================teammates.test.cases.browsertests.InstructorHomePageUiTest=============================]
Re-trying removeAndRestoreDataBundle - 
java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8888/backdoor
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1676)
	at teammates.test.driver.BackDoor.readResponse(BackDoor.java:432)
	at teammates.test.driver.BackDoor.makePostRequest(BackDoor.java:424)
	at teammates.test.driver.BackDoor.removeAndRestoreDataBundle(BackDoor.java:77)
	at teammates.test.cases.BaseTestCaseWithDatastoreAccess.doRemoveAndRestoreDataBundle(BaseTestCaseWithDatastoreAccess.java:283)
	at teammates.test.cases.BaseTestCaseWithDatastoreAccess.removeAndRestoreDataBundle(BaseTestCaseWithDatastoreAccess.java:272)
	at teammates.test.cases.browsertests.InstructorHomePageUiTest.prepareTestData(InstructorHomePageUiTest.java:37)
	at teammates.test.cases.browsertests.BaseUiTestCase.baseClassSetup(BaseUiTestCase.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)

Re-trying removeAndRestoreDataBundle - 
java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8888/backdoor
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1676)
	at teammates.test.driver.BackDoor.readResponse(BackDoor.java:432)
	at teammates.test.driver.BackDoor.makePostRequest(BackDoor.java:424)
	at teammates.test.driver.BackDoor.removeAndRestoreDataBundle(BackDoor.java:77)
	at teammates.test.cases.BaseTestCaseWithDatastoreAccess.doRemoveAndRestoreDataBundle(BaseTestCaseWithDatastoreAccess.java:283)
	at teammates.test.cases.BaseTestCaseWithDatastoreAccess.removeAndRestoreDataBundle(BaseTestCaseWithDatastoreAccess.java:277)
	at teammates.test.cases.browsertests.InstructorHomePageUiTest.prepareTestData(InstructorHomePageUiTest.java:37)
	at teammates.test.cases.browsertests.BaseUiTestCase.baseClassSetup(BaseUiTestCase.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)

Re-trying removeAndRestoreDataBundle - 
java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8888/backdoor
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1676)
	at teammates.test.driver.BackDoor.readResponse(BackDoor.java:432)
	at teammates.test.driver.BackDoor.makePostRequest(BackDoor.java:424)
	at teammates.test.driver.BackDoor.removeAndRestoreDataBundle(BackDoor.java:77)
	at teammates.test.cases.BaseTestCaseWithDatastoreAccess.doRemoveAndRestoreDataBundle(BaseTestCaseWithDatastoreAccess.java:283)
	at teammates.test.cases.BaseTestCaseWithDatastoreAccess.removeAndRestoreDataBundle(BaseTestCaseWithDatastoreAccess.java:277)
	at teammates.test.cases.browsertests.InstructorHomePageUiTest.prepareTestData(InstructorHomePageUiTest.java:37)
	at teammates.test.cases.browsertests.BaseUiTestCase.baseClassSetup(BaseUiTestCase.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)

Re-trying removeAndRestoreDataBundle - 
java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8888/backdoor
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1676)
	at teammates.test.driver.BackDoor.readResponse(BackDoor.java:432)
	at teammates.test.driver.BackDoor.makePostRequest(BackDoor.java:424)
	at teammates.test.driver.BackDoor.removeAndRestoreDataBundle(BackDoor.java:77)
	at teammates.test.cases.BaseTestCaseWithDatastoreAccess.doRemoveAndRestoreDataBundle(BaseTestCaseWithDatastoreAccess.java:283)
	at teammates.test.cases.BaseTestCaseWithDatastoreAccess.removeAndRestoreDataBundle(BaseTestCaseWithDatastoreAccess.java:277)
	at teammates.test.cases.browsertests.InstructorHomePageUiTest.prepareTestData(InstructorHomePageUiTest.java:37)
	at teammates.test.cases.browsertests.BaseUiTestCase.baseClassSetup(BaseUiTestCase.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)

Re-trying removeAndRestoreDataBundle - 
java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8888/backdoor
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1676)
	at teammates.test.driver.BackDoor.readResponse(BackDoor.java:432)
	at teammates.test.driver.BackDoor.makePostRequest(BackDoor.java:424)
	at teammates.test.driver.BackDoor.removeAndRestoreDataBundle(BackDoor.java:77)
	at teammates.test.cases.BaseTestCaseWithDatastoreAccess.doRemoveAndRestoreDataBundle(BaseTestCaseWithDatastoreAccess.java:283)
	at teammates.test.cases.BaseTestCaseWithDatastoreAccess.removeAndRestoreDataBundle(BaseTestCaseWithDatastoreAccess.java:277)
	at teammates.test.cases.browsertests.InstructorHomePageUiTest.prepareTestData(InstructorHomePageUiTest.java:37)
	at teammates.test.cases.browsertests.BaseUiTestCase.baseClassSetup(BaseUiTestCase.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)

FAILED CONFIGURATION: @BeforeClass baseClassSetup
java.lang.AssertionError: expected:<[BACKDOOR_STATUS_SUCCESS]> but was:<
java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8888/backdoor
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1676)
	at teammates.test.driver.BackDoor.readResponse(BackDoor.java:432)
	at teammates.test.driver.BackDoor.makePostRequest(BackDoor.java:424)
	at teammates.test.driver.BackDoor.removeAndRestoreDataBundle(BackDoor.java:77)
	at teammates.test.cases.BaseTestCaseWithDatastoreAccess.doRemoveAndRestoreDataBundle(BaseTestCaseWithDatastoreAccess.java:283)
	at teammates.test.cases.BaseTestCaseWithDatastoreAccess.removeAndRestoreDataBundle(BaseTestCaseWithDatastoreAccess.java:277)
	at teammates.test.cases.browsertests.InstructorHomePageUiTest.prepareTestData(InstructorHomePageUiTest.java:37)
	at teammates.test.cases.browsertests.BaseUiTestCase.baseClassSetup(BaseUiTestCase.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at teammates.test.cases.BaseTestCase.assertEquals(BaseTestCase.java:133)
	at teammates.test.cases.BaseTestCaseWithDatastoreAccess.removeAndRestoreDataBundle(BaseTestCaseWithDatastoreAccess.java:279)
	at teammates.test.cases.browsertests.InstructorHomePageUiTest.prepareTestData(InstructorHomePageUiTest.java:37)
	at teammates.test.cases.browsertests.BaseUiTestCase.baseClassSetup(BaseUiTestCase.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)

SKIPPED CONFIGURATION: @AfterClass baseClassTearDown
SKIPPED CONFIGURATION: @AfterClass printTestClassFooter
SKIPPED: allTests

===============================================
    Default test
    Tests run: 1, Failures: 0, Skips: 1
    Configuration Failures: 1, Skips: 2
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 2
===============================================

[TestNG] Time taken by org.testng.reporters.jq.Main@2dc68dc6: 35 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@adf7236: 7 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@72871d3e: 5 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 4 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@4df4a45d: 7 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@77aa2b26: 9 ms

dou.txt

**Comment by wkurniawan07** [comment]
@Devmassnk 

- Is your dev server running when you're running this test?
- I checked your fork and it looks like you're using a very old version. Have you updated to the latest one?

**Comment by Devmassnk** [comment]
I pulled the latest code. I am getting below error in project.
![17949955_1311204088966526_1066038535_o](https://cloud.githubusercontent.com/assets/16254475/25059897/62542eea-21ad-11e7-8eed-b1b63a096340.png)

**Comment by VamsiSangam** [comment]
It is an XML Problem. You need to follow the project specific settings in [ide-usage.md](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-usage.md). It is mentioned -

> Validation: We do not validate HTML, JSP, and XML.

So, if you follow the project specific settings there and Clean your project again, those errors shouldn't pop up. :smiley:

**Comment by wkurniawan07** [comment]
Closing due to inactivity. @Devmassnk if you still face problems related to this issue, feel free to reopen.
