### ISSUE TITLE
Intellij: Fix CI tests failing due to duplicate files

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7158]
'CI Tests' run configuration fails with the following error:

```
org.testng.TestNGException: 
An error occurred while instantiating class teammates.test.cases.logic.StudentsLogicTest: null
	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:401)
	at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:302)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:118)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:183)
	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:128)
	at org.testng.TestRunner.initMethods(TestRunner.java:413)
	at org.testng.TestRunner.init(TestRunner.java:239)
	at org.testng.TestRunner.init(TestRunner.java:209)
	at org.testng.TestRunner.<init>(TestRunner.java:157)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:546)
	at org.testng.SuiteRunner.init(SuiteRunner.java:159)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:113)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1274)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1261)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ExceptionInInitializerError
	at teammates.logic.core.AccountsLogic.<clinit>(AccountsLogic.java:32)
	at teammates.logic.api.Logic.<clinit>(Logic.java:68)
	at teammates.test.cases.BaseComponentTestCase.<clinit>(BaseComponentTestCase.java:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:29)
	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:389)
	... 22 more
Caused by: javax.jdo.JDOFatalUserException: Duplicate PMF name "transactions-optional" found in file:/C:/TEAMMATES-sandbox/teammates-intellij/build/resources/main/META-INF/jdoconfig.xml and file:/C:/TEAMMATES-sandbox/teammates-intellij/out/production/teammates-intellij/META-INF/jdoconfig.xml.
	at javax.jdo.JDOHelper.getNamedPMFProperties(JDOHelper.java:1300)
	at javax.jdo.JDOHelper.getPropertiesFromJdoconfig(JDOHelper.java:1232)
	at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:1079)
	at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:914)
	at teammates.storage.api.EntitiesDb.<clinit>(EntitiesDb.java:50)
	... 31 more
```

**Comment by wkurniawan07** [comment]
I'm not an IntelliJ user, but based on:
```
Caused by: javax.jdo.JDOFatalUserException: Duplicate PMF name "transactions-optional" found in file:/C:/TEAMMATES-sandbox/teammates-intellij/build/resources/main/META-INF/jdoconfig.xml and file:/C:/TEAMMATES-sandbox/teammates-intellij/out/production/teammates-intellij/META-INF/jdoconfig.xml.
```
It seems a problem of duplicate "output" folder, or the "output" folder not well-defined, or simply IntelliJ is not capable of filtering such duplicates.

While I don't know the root cause, I know the remedy: running `./gradlew clean` will remove the copy in `build/resources` folder.

**Comment by samsontmr** [comment]
The fix I currently use is indeed running `./gradlew clean`.

**Comment by damithc** [comment]
If there is no cleaner solutions (e.g. add `clean` to build steps), we can document this in the troubleshooting guide.
