### ISSUE TITLE
InstructorCourseEnrollPageUiTest and AdminHomePageUiTest failing on local dev server 

### ISSUE THREAD

**Issue by rchliu** [TEAMMATES/teammates#7183]
**Environment**
`master` branch, with the latest commit being cfa2aefeee7c601fea689aaaa5786cb72a67435c.

**Trace for InstructorCourseEnrollPageUiTest**
The specific test case that fails is `testInstructorCourseEnrollPage`. 

> org.openqa.selenium.TimeoutException: Timed out after 15 seconds waiting for teammates.test.pageobjects.AppPage$1@4bec9adc
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'DESKTOP-1999U85', ip: '192.168.0.147', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.7.0_80'
Session ID: c48ff997-d5a7-4d5d-ae0c-837177d05405
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=46.0}]
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:261)
	at teammates.test.pageobjects.AppPage.waitForPageToLoad(AppPage.java:180)
	at teammates.test.pageobjects.InstructorCourseEnrollPage.clickSpreadsheetLink(InstructorCourseEnrollPage.java:40)
	at teammates.test.cases.browsertests.InstructorCourseEnrollPageUiTest.testSampleLink(InstructorCourseEnrollPageUiTest.java:50)
	at teammates.test.cases.browsertests.InstructorCourseEnrollPageUiTest.testInstructorCourseEnrollPage(InstructorCourseEnrollPageUiTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Trace for AdminHomePageUiTest**

> org.openqa.selenium.TimeoutException: Timed out after 15 seconds waiting for element to be clickable: [[FirefoxDriver: firefox on WINDOWS (5278feb2-82a2-42df-9f0d-729baef1ee58)] -> id: btnAddInstructorDetailsSingleLineForm]
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'DESKTOP-1999U85', ip: '192.168.0.147', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.7.0_80'
Session ID: 5278feb2-82a2-42df-9f0d-729baef1ee58
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=46.0}]
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:261)
	at teammates.test.pageobjects.AppPage.waitForElementToBeClickable(AppPage.java:224)
	at teammates.test.pageobjects.AdminHomePage.createInstructorByInstructorDetailsSingleLineForm(AdminHomePage.java:67)
	at teammates.test.cases.browsertests.AdminHomePageUiTest.testCreateInstructorAction(AdminHomePageUiTest.java:88)
	at teammates.test.cases.browsertests.AdminHomePageUiTest.testAll(AdminHomePageUiTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by damithc** [comment]
@rchliu If these are the only two tests failing, you can ignore them for now until someone has some helpful inputs for you.

**Comment by wkurniawan07** [comment]
Hi @rchliu, this failure could be due to the timeout value being too short. Can you try setting the `test.timeout` value in `test.properties` file to something like 30 and re-running just these two tests?

Actually, before even changing the mentioned value, can you try re-running these two tests? Usually tests run faster when run in isolation.

**Comment by rchliu** [comment]
Thanks for your help, @wkurniawan07. After a few more retries `AdminHomePageUiTest` succeeded, but I had to change the timeout to 30s for `InstructorCourseEnrollPageUiTest` to pass.
