### ISSUE TITLE
Help Request: Babel error while building JS files

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7187]
- **Operating System:** Windows 10
- **JDK Version:** 1.7
- **Eclipse / IntelliJ Version (if applicable):** Kepler Service Release 2

**What I was trying to do / What I need help with**

I was building JS files as per instructions in [development.md](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md). When I ran `npm run build` this is what I got -

```
E:\teammates>npm run build

> @ build E:\teammates
> npm run build:src && npm run build:test


> @ build:src E:\teammates
> babel src/main/webapp/js/ -x ".es6" -d src/main/webapp/js/

'babel' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:src"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ build:src: `babel src/main/webapp/js/ -x ".es6" -d src/main/webapp/js/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build:src script 'babel src/main/webapp/js/ -x ".es6" -d src/main/webapp/js/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel src/main/webapp/js/ -x ".es6" -d src/main/webapp/js/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     E:\teammates\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ build: `npm run build:src && npm run build:test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script 'npm run build:src && npm run build:test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:src && npm run build:test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     E:\teammates\npm-debug.log
```

Then I installed babel by running `npm install --save-dev babel-cli` as given in [babeljs.io](https://babeljs.io/docs/usage/cli/). That caused a change in `package.json`, but when I tried `npm run build` I getting this -

```
E:\teammates>npm run build

> @ build E:\teammates
> npm run build:src && npm run build:test


> @ build:src E:\teammates
> babel src/main/webapp/js/ -x ".es6" -d src/main/webapp/js/

Error: Couldn't find preset "env" relative to directory "E:\\teammates"
    at E:\teammates\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (E:\teammates\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (E:\teammates\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (E:\teammates\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (E:\teammates\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\teammates\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (E:\teammates\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (E:\teammates\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transform (E:\teammates\node_modules\babel-cli\lib\babel\util.js:50:22)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:src"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ build:src: `babel src/main/webapp/js/ -x ".es6" -d src/main/webapp/js/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build:src script 'babel src/main/webapp/js/ -x ".es6" -d src/main/webapp/js/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel src/main/webapp/js/ -x ".es6" -d src/main/webapp/js/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\teammates\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ build: `npm run build:src && npm run build:test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script 'npm run build:src && npm run build:test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:src && npm run build:test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\teammates\npm-debug.log
```

How do I install babel correctly for using the application?

**Comment by AnaghHegde** [comment]
@VamsiSangam Its because the npm version you are using is less than 4. Upgrade it to 4.X or above it will work fine.

**Comment by wkurniawan07** [comment]
@VamsiSangam have you run `npm install` to get all the tools?
On an unrelated note, you're using Eclipse Kepler, which we do not really provide support on. You can choose to still use it, but I'd suggest you upgrade to newer ones like Luna, Mars, or Neon.

@AnaghHegde the Node version is fine. We don't have an explicit requirement on NPM version. Take note that they are two different items.

**Comment by AnaghHegde** [comment]
@VamsiSangam @wkurniawan07 I had the similar issue back once and upgrading the npm helped me. That is the reason i mentioned it.

**Comment by VamsiSangam** [comment]
Thanks @wkurniawan07 and @AnaghHegde . I didn't run `npm install` :sweat_smile: . So babel compiles the `.es6` files to `.js` files right? So where are the compiled `.js` files stored?

**Comment by AnaghHegde** [comment]
In the same directory where the .es6 files will be stored.

**Comment by VamsiSangam** [comment]
Then why don't I see them in eclipse? :stuck_out_tongue:

**Comment by AnaghHegde** [comment]
Hm. May be [this](http://stackoverflow.com/a/98634/6181189) will help you.

**Comment by VamsiSangam** [comment]
Oh thanks for the link. I don't use eclipse very often. But the files are still not displayed in my eclipse. However I simply used the File Explorer to check out the folder and found the .js files. I understand everything now. Thanks for the help :smile: 

@wkurniawan07 wouldn't the docs be more user friendly if we added about `npm install` in `development.md` or the troubleshooting guide?

**Comment by AnaghHegde** [comment]
@VamsiSangam It's there in docs, [here.](https://github.com/TEAMMATES/teammates/blob/master/docs/settingUp.md#step-3-set-up-project-specific-settings-and-dependencies). Take a look at it.

**Comment by VamsiSangam** [comment]
Oh missed it completely. Thanks a lot @AnaghHegde . Closing issue now :smile:
