### ISSUE TITLE
Dev Server's Problem

### ISSUE THREAD

**Issue by nikiforosbotis** [TEAMMATES/teammates#7210]
Dear All,

I set up the dev server, as shown in the instructions, 2 months ago. Every time I was trying to connect to TEAMMATES via localhost:8888, I could easily use all its features through the dev server. However, from yesterday I am getting this message when I am trying to do specific things (move to the "Request a Free Instructor Account" page):
![2](https://cloud.githubusercontent.com/assets/9116253/25563078/9f21ca80-2d9c-11e7-8317-595cdc4252ee.png)

 Does anyone have any idea on what to do in order to be able to use the dev server properly?

Thank you in advance!

**Comment by damithc** [comment]
@nikiforosbotis It might help if you post the error message shown in the dev server console.

**Comment by nikiforosbotis** [comment]
Dear @damithc , thank you for your time.
These are two screenshots from the dev server console:
If you have any idea, please let me know.

![1](https://cloud.githubusercontent.com/assets/9116253/25563194/848ac142-2d9f-11e7-9e57-5dd9d623728d.png)

![2](https://cloud.githubusercontent.com/assets/9116253/25563195/89412866-2d9f-11e7-8f23-d901b364b2ca.png)

**Comment by AnaghHegde** [comment]
@nikiforosbotis Look's like the sdk is not pointing to the proper location from the warning can you check and confirm if it's pointing to a valid location ?. If it's so try cleaning the project and check.

**Comment by nikiforosbotis** [comment]
@AnaghHegde : update: 
I fixed the request instructor account page (it was my fault) but I still have problems with the "Student Login" and the "Instructor Login" buttons.

**The stack trace for this buttons is as follows:**

Apr 30, 2017 10:21:51 AM com.google.apphosting.utils.jetty.JettyLogger warn
WARNING: /login
javax.jdo.JDOUserException: Exception converting Account("test@example.com") to an internal key.
	at org.datanucleus.store.appengine.jdo.DatastoreJDOPersistenceManager.getObjectById(DatastoreJDOPersistenceManager.java:70)
	at teammates.storage.api.AccountsDb.getAccountEntity(AccountsDb.java:215)
	at teammates.storage.api.AccountsDb.getAccount(AccountsDb.java:94)
	at teammates.storage.api.AccountsDb.getAccount(AccountsDb.java:105)
	at teammates.logic.core.AccountsLogic.isAccountAnInstructor(AccountsLogic.java:72)
	at teammates.logic.api.GateKeeper.isInstructor(GateKeeper.java:316)
	at teammates.logic.api.GateKeeper.getCurrentUser(GateKeeper.java:49)
	at teammates.ui.controller.LoginServlet.doPost(LoginServlet.java:27)
	at teammates.ui.controller.LoginServlet.doGet(LoginServlet.java:21)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:128)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:509)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
NestedThrowablesStackTrace:
Persistent class "Class teammates.storage.entity.Account does not seem to have been enhanced.  You may want to rerun the enhancer and check for errors in the output." has no table in the database, but the operation requires it. Please check the specification of the MetaData for this class.
org.datanucleus.store.exceptions.NoTableManagedException: Persistent class "Class teammates.storage.entity.Account does not seem to have been enhanced.  You may want to rerun the enhancer and check for errors in the output." has no table in the database, but the operation requires it. Please check the specification of the MetaData for this class.
	at org.datanucleus.store.appengine.DatastoreManager.getDatastoreClass(DatastoreManager.java:778)
	at org.datanucleus.store.appengine.DatastoreManager.getDatastoreClass(DatastoreManager.java:88)
	at org.datanucleus.store.appengine.EntityUtils.determineKind(EntityUtils.java:98)
	at org.datanucleus.store.appengine.EntityUtils.determineKind(EntityUtils.java:94)
	at org.datanucleus.store.appengine.EntityUtils.idToInternalKey(EntityUtils.java:124)
	at org.datanucleus.store.appengine.jdo.DatastoreJDOPersistenceManager.getObjectById(DatastoreJDOPersistenceManager.java:63)
	at teammates.storage.api.AccountsDb.getAccountEntity(AccountsDb.java:215)
	at teammates.storage.api.AccountsDb.getAccount(AccountsDb.java:94)
	at teammates.storage.api.AccountsDb.getAccount(AccountsDb.java:105)
	at teammates.logic.core.AccountsLogic.isAccountAnInstructor(AccountsLogic.java:72)
	at teammates.logic.api.GateKeeper.isInstructor(GateKeeper.java:316)
	at teammates.logic.api.GateKeeper.getCurrentUser(GateKeeper.java:49)
	at teammates.ui.controller.LoginServlet.doPost(LoginServlet.java:27)
	at teammates.ui.controller.LoginServlet.doGet(LoginServlet.java:21)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:128)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:509)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

**Comment by VamsiSangam** [comment]
Hi @nikiforosbotis ! That error seems familiar, it should get removed if you follow the instructions in [ide-usage.md](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-usage.md). Please check if you have all the project-specific properties (point 4 in the doc) set up as mentioned in the doc. Specifically please check if you have `Datanucleus version` setting and `ORM Enhancement` setting as mentioned in the doc because the above error is caused due to the Datanucleus enhancer.

**Comment by AnaghHegde** [comment]
@nikiforosbotis 

>Persistent class "Class teammates.storage.entity.Account does not seem to have been enhanced.

I think its the reason of cause. Can you post a screen shot of the `Project` Properties and ORM in APp Engine.

**Comment by nikiforosbotis** [comment]
@AnaghHegde this is the screenshot you asked for. Am I supposed to change anything here?

![1](https://cloud.githubusercontent.com/assets/9116253/25563849/a473e908-2dad-11e7-86a9-ede1c97e2b0a.png)

**Comment by VamsiSangam** [comment]
@nikiforosbotis you are supposed to remove all those entries in ORM and add a single entry `src/main/java/teammates/storage/entity/*.java` . Then clean your project and you should be good to go :smile: .

**Comment by VamsiSangam** [comment]
ORM setting correction should set things right, but I strongly recommend checking if all your settings are as per [ide-usage.md](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-usage.md). It may seem bothersome but it will prevent a bunch of weird errors and save you a lot of time. :smile:

**Comment by nikiforosbotis** [comment]
@VamsiSangam I just read your message and I fixed the problem. Thank you very much for your help!
