### ISSUE TITLE
Technical Issue in deploying to staging server.

### ISSUE THREAD

**Issue by nijoey** [TEAMMATES/teammates#7306]
Operating System: Windows 10 
JDK Version: 1.7
Eclipse: Luna

What I need help with: 
I am able to successfully run the code in the dev environment and I am successful in deploying on my local server. 
I am not getting the step after that. Making the tinker branch and  deploying it on the staging server. Another thing is how to get a link to the app? I am not getting how to get some app link like https://myName-teammates.appspot.com. 

Attempts to resolve: 
I can already see a tinker branch on my git !! How am I supposed to create a new one ?

**Comment by VamsiSangam** [comment]
Hi @nijoey ! Did you create an account in [Google App Engine](https://cloud.google.com/appengine/)? If yes, then you need to create a project of name `teammates-yourname`. You should be able to see your project on your dashboard, similar to this -

![capture](https://cloud.githubusercontent.com/assets/11662001/26070391/19c933e6-39c2-11e7-9a20-5dc3370b26e4.JPG)

And then follow the steps mentioned under `Deploying to a staging server` in [development.md](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md). Let me know if you face any further issues 😄

**Comment by nijoey** [comment]
Hi @VamsiSangam . Thank you very much for your reply.
I had no idea that we need a Google App Engine account. I was able to get that account with the project name. I am all set on that one. But now I am facing some other problem, sorry for bothering you again on this one. When I try and go to the admin page, and register with any name I get the following exception 

java.lang.UnsupportedClassVersionError: com/google/common/collect/ImmutableSet : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at com.google.appengine.tools.development.IsolatedAppClassLoader.loadClass(IsolatedAppClassLoader.java:199)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.owasp.html.HtmlPolicyBuilder.<clinit>(HtmlPolicyBuilder.java:163)
	at teammates.common.util.Sanitizer.<clinit>(Sanitizer.java:24)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at com.google.appengine.tools.development.agent.runtime.RuntimeHelper.checkRestricted(RuntimeHelper.java:70)
	at com.google.appengine.tools.development.agent.runtime.Runtime.checkRestricted(Runtime.java:65)
	at teammates.common.util.Url.addParamToUrl(Url.java:74)
	at teammates.ui.controller.ActionResult.appendParameters(ActionResult.java:101)
	at teammates.ui.controller.ActionResult.getDestinationWithParams(ActionResult.java:89)
	at teammates.ui.controller.ShowPageResult.send(ShowPageResult.java:54)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:65)
	at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:43)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:29)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:128)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:509)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

I googled this exception and everywhere I found that this is a version problem. The compile time and runtime versions differ. I went through all the setup process for Eclipse (Luna) and made sure that all the versions were correct. 
Can you think of anything that I might be missing on this ?
thanks 
nitesh.

**Comment by VamsiSangam** [comment]
> java.lang.UnsupportedClassVersionError: com/google/common/collect/ImmutableSet : Unsupported major.minor version 52.0

52 refers to Java 8. You need to use Java 7 for compiling and running. Have a look at the steps mentioned in [the docs](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-usage.md) for setting up JDK. Let me know if they match up 😄
