### ISSUE TITLE
StudentFeedbackSubmitPageUiTest: fix failure against live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7335]
```
java.lang.AssertionError:  


	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at teammates.test.driver.HtmlHelper.assertSameHtml(HtmlHelper.java:85)
	at teammates.test.driver.HtmlHelper.assertSameHtml(HtmlHelper.java:53)
	at teammates.test.pageobjects.AppPage.verifyHtmlPart(AppPage.java:850)
	at teammates.test.pageobjects.AppPage.verifyHtml(AppPage.java:824)
	at teammates.test.cases.browsertests.StudentFeedbackSubmitPageUiTest.testContent(StudentFeedbackSubmitPageUiTest.java:74)
	at teammates.test.cases.browsertests.StudentFeedbackSubmitPageUiTest.testAll(StudentFeedbackSubmitPageUiTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

teammates.test.cases.browsertests.StudentFeedbackSubmitPageUiTest completed
```
![image](https://cloud.githubusercontent.com/assets/1673303/26235141/d53b62a8-3c9b-11e7-82cf-0548f076c6d0.png)

**Comment by VamsiSangam** [comment]
The cause of that would be me. Please look at #7327 . That block was supposed to be there, which was accidentally removed by me. But my latest merge #6095 should have solved it. @wkurniawan07 your thoughts on this?

**Comment by wkurniawan07** [comment]
@VamsiSangam is right. It would be corrected by now, sadly it did not make it to the V5.104 release.

**Comment by damithc** [comment]
Got it. Closing.
