### ISSUE TITLE
Fix HtmlHelperTest test failure on dev server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7483]
v5.106

HtmlHelperTest failing against dev server for multiple tries, Windows 7, Intellij

```
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at teammates.test.driver.HtmlHelper.assertSameHtml(HtmlHelper.java:89)
	at teammates.test.driver.HtmlHelper.assertSameHtml(HtmlHelper.java:57)
	at teammates.test.cases.testdriver.HtmlHelperTest.testConvertToStandardHtmlPart(HtmlHelperTest.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```
![image](https://user-images.githubusercontent.com/1673303/26964566-b5a41e3c-4d24-11e7-9af4-2b5db44bf0b0.png)

**Comment by LiHaoTan** [comment]
I looked into it a little and suspect the problem comes from a different jSoup library used in IntelliJ IDEA.

<img width="1440" alt="htmlhelpertest" src="https://user-images.githubusercontent.com/13617389/27000566-0170349a-4de8-11e7-812c-1f1a5629b9a8.png">

It can be fixed by forcing the jsoup version used in the project to be the version we want.

We just need to add
`force "org.jsoup:jsoup:1.10.2"`
to the line after
`force "com.google.appengine:appengine-api-1.0-sdk:${appengineVersion}"`.

As to why IntelliJ IDEA is resolving the dependencies differently from Gradle on CLI, I am not very sure and did not check. It might be the particular version of Gradle used by IntelliJ IDEA to resolve dependencies is different. Either way, we should only be using a particular version of jsoup.

The way in which Gradle resolve dependencies is pretty complicated and I am not fully sure as well.

---
Alternatively, the problem may be that the HTML we give is malformed and jsoup (in app-engine-stubs) fail to parse it in the way we wanted, but the version does. I know jsoup handles malformed  HTMLs, but I do not know what they consider malformed or don’t even care altogether, but according to their documentation, `jsoup implements the WHATWG HTML5 specification, and parses HTML to the same DOM as modern browsers do.` Based on the HTML5 specification, the noscript tag in the head is invalid.

Here's the excerpt
>When scripting is disabled, in a head element: in any order, zero or more link elements, zero or more style elements, and zero or more meta elements.
When scripting is disabled, not in a head element: transparent, but there must be no noscript element descendants.

Source: https://www.w3.org/TR/html5/scripting-1.html#the-noscript-element


So if we take the test that is failing, `sampleExpected.html` has the `noscript` element in the `head` while `sampleActualPart`.html has it in the `body`. And if we move all the `noscript` elements to the body the test will pass.

**Summary**
In this case, I would say that there is no easy way to tell where the problem really lies without doing a lot of work understanding the jsoup parser, finding out what version of Gradle IntelliJ IDEA is using and how it differs from Gradle `3.5`, but I think two things should be fixed:
1. We always want v1.10.2 of jsoup so we should force it, to avoid the conflict with the embedded `appengine-api-stubs`.
2. The noscript element should be placed in the body to obey the HTML spec.

Either of them will make the test pass, but both of them are real problems that can hurt us in the future.

**Comment by damithc** [comment]
Good sleuthing @LiHaoTan :+1:
I have no objections to fixing both.

**Comment by whipermr5** [comment]
Strange - my IntelliJ now resolves to the correct jsoup version and the test passes. It's pretty unpredictable.

**Comment by LiHaoTan** [comment]
Yea I guess I forgot to mention that it is unpredictable.
