### ISSUE TITLE
InstructorCourseDetailsPageUiTest: use Gmail API

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7492]
v5.106
```
java.lang.NullPointerException
	at javax.mail.internet.ParameterList.set(ParameterList.java:165)
	at com.sun.mail.imap.protocol.BODYSTRUCTURE.parseParameters(BODYSTRUCTURE.java:404)
	at com.sun.mail.imap.protocol.BODYSTRUCTURE.<init>(BODYSTRUCTURE.java:224)
	at com.sun.mail.imap.protocol.BODYSTRUCTURE.<init>(BODYSTRUCTURE.java:109)
	at com.sun.mail.imap.protocol.FetchResponse.parseItem(FetchResponse.java:198)
	at com.sun.mail.imap.protocol.FetchResponse.parse(FetchResponse.java:164)
	at com.sun.mail.imap.protocol.FetchResponse.<init>(FetchResponse.java:92)
	at com.sun.mail.imap.protocol.IMAPProtocol.readResponse(IMAPProtocol.java:288)
	at com.sun.mail.iap.Protocol.command(Protocol.java:313)
	at com.sun.mail.imap.protocol.IMAPProtocol.fetch(IMAPProtocol.java:1543)
	at com.sun.mail.imap.protocol.IMAPProtocol.fetch(IMAPProtocol.java:1535)
	at com.sun.mail.imap.protocol.IMAPProtocol.fetchBodyStructure(IMAPProtocol.java:1235)
	at com.sun.mail.imap.IMAPMessage.loadBODYSTRUCTURE(IMAPMessage.java:1294)
	at com.sun.mail.imap.IMAPMessage.getDataHandler(IMAPMessage.java:639)
	at javax.mail.internet.MimeMessage.getContent(MimeMessage.java:927)
	at teammates.test.driver.EmailAccount.getEmailBody(EmailAccount.java:88)
	at teammates.test.driver.EmailAccount.getRegistrationKeyFromGmail(EmailAccount.java:45)
	at teammates.test.cases.browsertests.InstructorCourseDetailsPageUiTest.didStudentReceiveReminder(InstructorCourseDetailsPageUiTest.java:248)
	at teammates.test.cases.browsertests.InstructorCourseDetailsPageUiTest.testRemindAction(InstructorCourseDetailsPageUiTest.java:171)
	at teammates.test.cases.browsertests.InstructorCourseDetailsPageUiTest.allTests(InstructorCourseDetailsPageUiTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
```

**Comment by whipermr5** [comment]
This might just be slow email delivery. I can't reproduce it on my staging server.

**Comment by damithc** [comment]
I increased to 30,000 but still fails. BTW, the test fails at a 'click and cancel' scenario. An email is not supposed to be delivered anyway.

**Comment by whipermr5** [comment]
Oh I see. I didn't get the `NullPointerException`, but initially I did get an error message about using the browser to login. I had to turn on the `Allow less secure apps` option at https://myaccount.google.com/security?pli=1#connectedapps for the test account for the test to access the email inbox. Is that option already turned on for your test accounts?

**Comment by damithc** [comment]
Yes, that option is already set.
This may be related https://stackoverflow.com/questions/13251467/javamail-null-pointer-exeception-in-bodystructure-parseparameters-is-it-a-bug
I'm using Intellij and this is a fresh setup. I remember we had a similar issue in eclipse and we had to put java.mail library at a specific location to get around it. May be @LiHaoTan can help?

**Comment by damithc** [comment]
FWIW, the test fails the same way even if I run it in CLI.

**Comment by whipermr5** [comment]
Confirmed failing on CLI and IntelliJ while passing on Eclipse.
