### ISSUE TITLE
InstructorCourseDetailsPageUiTest: fix failure against live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7629]
v5.108, on Windows, using Intellij

```
Jun 28, 2017 10:55:01 AM com.google.api.client.util.store.FileDataStoreFactory setPermissionsToOwnerOnly
WARNING: unable to change permissions for everybody: C:\TEAMMATES-sandbox\teammates-2017June\src\test\resources\gmail-api
Jun 28, 2017 10:55:01 AM com.google.api.client.util.store.FileDataStoreFactory setPermissionsToOwnerOnly
WARNING: unable to change permissions for owner: C:\TEAMMATES-sandbox\teammates-2017June\src\test\resources\gmail-api

java.lang.ClassCastException: javax.mail.internet.MimeMessage cannot be cast to javax.mail.Multipart

	at teammates.test.driver.EmailAccount.getTextFromPart(EmailAccount.java:134)
	at teammates.test.driver.EmailAccount.getTextFromEmail(EmailAccount.java:128)
	at teammates.test.driver.EmailAccount.getRegistrationKeyFromGmail(EmailAccount.java:78)
	at teammates.test.cases.browsertests.InstructorCourseDetailsPageUiTest.hasStudentReceivedReminder(InstructorCourseDetailsPageUiTest.java:274)
	at teammates.test.cases.browsertests.InstructorCourseDetailsPageUiTest.testRemindAction(InstructorCourseDetailsPageUiTest.java:173)
	at teammates.test.cases.browsertests.InstructorCourseDetailsPageUiTest.allTests(InstructorCourseDetailsPageUiTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

teammates.test.cases.browsertests.InstructorCourseDetailsPageUiTest completed
```

**Comment by damithc** [comment]
Seem to be related to the new Gmail api, so may be @LiHaoTan can help.
On the positive side, this is the only test now failing against the live server, although some requires multiple tries :+1:

**Comment by LiHaoTan** [comment]
Oops sorry after I refactored some methods I passed in the wrong argument.
