### ISSUE TITLE
Fix error reported in live server: Empty question text

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7796]
v5.109

```
Error Message: teammates.common.util.Logger severe: Unexpected exception caught by ControllerServlet : 
java.lang.AssertionError: Empty question text
at teammates.common.util.Assumption.fail(Assumption.java:61)
at teammates.common.util.Assumption.assertTrue(Assumption.java:29)
at teammates.common.util.Assumption.assertFalse(Assumption.java:46)
at teammates.common.util.Assumption.assertNotEmpty(Assumption.java:380)
at teammates.common.datatransfer.questions.FeedbackQuestionDetails.createQuestionDetails(FeedbackQuestionDetails.java:169)
at teammates.ui.controller.InstructorFeedbackQuestionAddAction.extractFeedbackQuestionData(InstructorFeedbackQuestionAddAction.java:129)
at teammates.ui.controller.InstructorFeedbackQuestionAddAction.execute(InstructorFeedbackQuestionAddAction.java:32)
at teammates.ui.controller.Action.executeAndPostProcess(Action.java:474)
at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:75)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
at teammates.ui.controller.AppstatsFilter.doFilter(AppstatsFilter.java:41)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at org.mortbay.jetty.Server.handle(Server.java:326)
at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:657)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:619)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:589)
at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)
at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:263)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by damithc** [comment]
I've never seen this error before.
```
teammates.common.util.Logger info: Request received : [POST] https://teammatesv4.appspot.com/page/instructorFeedbackQuestionAdd:{showresponsesto::RECEIVER,INSTRUCTORS, constSumPointsPerOption::false, rubricNumRows::2, rubricChoice-3::Strongly Agree, numofrecipientstype::max, rubricChoice-0::Strongly Disagree, constSumToRecipients::false, constSumOption-1::, rubricDesc-0-3::Initiates discussions frequently, and engages the team., constSumOption-0::, rubricDesc-0-2::Takes part in discussions and sometimes initiates discussions., rubricChoice-2::Agree, rubricDesc-0-1::Occasionally responds, but never initiates discussions., rubricChoice-1::Disagree, rubricDesc-0-0::Rarely or never responds., generatedOptions::NONE//NONE//NONE, questiondescription--1::, numscalestep::1, numofrecipients::1, recipienttype::SELF, constSumPointsForEachOption::100, constSumPoints::100, showrecipientto::RECEIVER,INSTRUCTORS, rubricNumCols::4, questiontext::, mcqOption-1::, questiondescription::, isNotSureAllowedCheck::on, token::189F2F1278D562A6321A6144DAC8CCEC, showgiverto::RECEIVER,INSTRUCTORS, mcqOption-0::, questionnum::1//1, rubricSubQn-0::This student participates well in online discussions., courseid::CP2302, recommendedlength::, rubricSubQn-1::This student completes assigned tasks on time., noofchoicecreated::2//2//2//2, constSumPointsForEachRecipient::100, rubricDesc-1-3::Tasks are always completed before the deadline., rubricWeight-3::0, rankOption-1::, rubricWeight-2::0, rubricDesc-1-0::Rarely or never completes tasks., rankOption-0::, rubricWeight-1::0, rubricDesc-1-1::Often misses deadlines., rubricWeight-0::0, rubricDesc-1-2::Occasionally misses deadlines., numscalemin::1, fsname::Independent Exercise - peer evaluation, msqOption-0::, receiverLeaderCheckbox::RECEIVER, msqOption-1::, questiontype::CONSTSUM_OPTION, numscalemax::5, givertype::SELF, user::abc}
```

**Comment by damithc** [comment]
Related to #7784?

**Comment by damithc** [comment]
Seems user is using IE and the problem went away when she switched to Chrome. Anyway, here are the steps she took:
```
I’ll summarise what I did and maybe you can trace how the error came about.
1.       Created a numerical scale question.
2.       Then in the Description field, I typed what each number was to represent (eg. 1 = not at all; 5 = extremely well)
3.       Then I clicked on Add New Question.
4.       When I checked on my Question 1, I realised that my Description field was empty. I was also not able to delete the question.

5.       So I created a second numerical scale question; but this time, I tried adding the explanation (eg. 1 = not at all, 2 = poorly etc.) to the question field. However, I can only see the first one. Can’t scroll down to see the rest of the question.
6.       Similarly, I can’t delete or edit this question.
```

**Comment by whipermr5** [comment]
Might be outdated JavaScript files cached in her browser. Could she help verify by clearing her IE cache and trying the same steps again?

**Comment by damithc** [comment]
> Might be outdated JavaScript files cached in her browser.

For that to hold, she should have accessed TEAMMATES within the last 24 hours but before V5.109 was deployed, am I right?

**Comment by whipermr5** [comment]
Might be any time period. Do we set cache control headers?

**Comment by whipermr5** [comment]
Seems like they're set to 10 minutes; I'm not sure how many browsers respect that though (I have especially low confidence for old versions of IE).

![screenshot_20170719-183436](https://user-images.githubusercontent.com/6811428/28363063-8a2f356e-6cb1-11e7-8e23-48b2d54ff2de.png)

**Comment by whipermr5** [comment]
We might need to look into build hashes for our js files, as it's the only reliable way to defeat browser caching.

**Comment by damithc** [comment]
There is no urgency anymore because the user is able to get the work done. In the meantime we can think of a solution and also wait to see if there are recurrences.

**Comment by whipermr5** [comment]
Have there been any recurrences of this?

**Comment by damithc** [comment]
Happened once more (4 days ago) since Jul 19.

**Comment by LiHaoTan** [comment]
I wonder if this error is a caching problem, I tried checking and it seems that since IE6 `max-age` is working. (And TEAMMATES only support IE >= 8).

> All of them will cache responses that have freshness information (i.e., Expires and Cache-Control: max-age headers). Likewise, all of them know that they’re private caches, and therefore will still cache something with Cache-Control: private. That’s very handy, because it allows you to target the browser cache separately from intermediary caches.

https://www.mnot.net/blog/2006/05/11/browser_caching

Can't find a better source than a blog but I suppose MDN Web Docs can be considered an accurate source. They also mentioned that IE supports the header. 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

However, they did not indicate the version number when `cache-control` is supported in IE.
> Supported, but version unknown:

https://github.com/mdn/browser-compat-data/blob/master/compat-data-schema.md


@whipermr5 could it not be a caching issue then? maybe we should test whether `max-age` works on the particular browser itself?

**Comment by whipermr5** [comment]
It may not be a caching issue at all; I'm just not sure what might be the cause of the total JavaScript failure the user experienced: https://github.com/TEAMMATES/teammates/issues/7796#issuecomment-316331643

**Comment by damithc** [comment]
Still happening at v6.0.1

**Comment by damithc** [comment]
Last reported Jan 23, 2018

**Comment by damithc** [comment]
Happened once today.
