### ISSUE TITLE
CourseJoinAuthenticatedAbstractAction: fix NullPointerException in live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7950]
v5.110
Getting quite a few of these:

```
Error Message: teammates.common.util.Logger severe: Unexpected exception caught by ControllerServlet : 
java.lang.NullPointerException
at teammates.ui.template.FeedbackSessionsForm.getFormForNewFs(FeedbackSessionsForm.java:129)
at teammates.ui.pagedata.InstructorFeedbackSessionsPageData.buildBasicForm(InstructorFeedbackSessionsPageData.java:152)
at teammates.ui.pagedata.InstructorFeedbackSessionsPageData.buildNewForm(InstructorFeedbackSessionsPageData.java:134)
at teammates.ui.pagedata.InstructorFeedbackSessionsPageData.init(InstructorFeedbackSessionsPageData.java:56)
at teammates.ui.pagedata.InstructorFeedbackSessionsPageData.initWithoutHighlightedRow(InstructorFeedbackSessionsPageData.java:72)
at teammates.ui.controller.InstructorFeedbackAddAction.execute(InstructorFeedbackAddAction.java:103)
at teammates.ui.controller.Action.executeAndPostProcess(Action.java:474)
at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:75)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
at teammates.ui.controller.AppstatsFilter.doFilter(AppstatsFilter.java:41)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at org.mortbay.jetty.Server.handle(Server.java:326)
at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:657)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:619)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:589)
at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)
at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:263)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by whipermr5** [comment]
I was able to reproduce this when my staging server was in a weird state (locally hosted js libraries but with missing fonts). I tried adding a new distribute points among recipients question to an existing session (the `Second team feedback session` of the sample course). In the new question frame, I noticed that the question text field was disabled but with the default placeholder text. There was no way to edit it. Submitting it in this state resulted in the error as the question text was not passed in the POST parameters. However, after redeploying, I'm unable to reproduce the error. It seems to be bad js files?

@damithc Can you try adding a distribute points among recipients question to an existing session on the live server? If it fails, might need to redo `npm run build` and redeploy.

**Comment by damithc** [comment]
> @damithc Can you try adding a distribute points among recipients question to an existing session on the live server? If it fails, might need to redo npm run build and redeploy.

Did not reproduce the error. I did an `npm run build` before the current deployment anyway. Note that this error happened during the CDN downtime.

**Comment by whipermr5** [comment]
Any further occurrences of this?

**Comment by damithc** [comment]
Not recently. There were a few other `java.lang.NullPointerException` but coming from different locations.

**Comment by damithc** [comment]
Another NPE for a different place. 
```
Error Message: teammates.common.util.Logger severe: Unexpected exception caught by ControllerServlet : 
java.lang.NullPointerException
at teammates.logic.api.EmailGenerator.generateUserCourseRegisterEmail(EmailGenerator.java:583)
at teammates.ui.controller.CourseJoinAuthenticatedAbstractAction.sendCourseRegisteredEmail(CourseJoinAuthenticatedAbstractAction.java:16)
at teammates.ui.controller.InstructorCourseJoinAuthenticatedAction.execute(InstructorCourseJoinAuthenticatedAction.java:66)
at teammates.ui.controller.Action.executeAndPostProcess(Action.java:474)
at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:76)
at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:51)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
at teammates.ui.controller.AppstatsFilter.doFilter(AppstatsFilter.java:41)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at org.mortbay.jetty.Server.handle(Server.java:326)
at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:650)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:612)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:582)
at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:454)
at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:461)
at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:297)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:320)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:312)
at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:458)
at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:263)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by damithc** [comment]
Getting more of NPE from `generateUserCourseRegisterEmail`

**Comment by whipermr5** [comment]
Related to #7902. Still investigating.

**Comment by whipermr5** [comment]
Due to the `Account` entity not existing yet when the user clicks on join course. The current mechanism calls the database for the `Account` entity and reads information from it to generate the email. However, all the information needed is already available in `(Instructor|Student)CourseJoinAuthenticatedAction`, and we simply need to pass the info (user's name, Google ID, email, and whether the user is an instructor) directly to `EmailGenerator`, saving database calls and avoiding this situation.
