### ISSUE TITLE
Instructor: edit students: improve efficiency of 'delete all students' 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8011]
v5.110

I noticed that an instructor is trying to 'delete all students' of a course with 500+ students and constantly running into a 'task cancelled' error.

```
teammates.common.util.Logger severe: Unexpected exception caught by ControllerServlet :  (Logger.java:52)
java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1170)
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:492)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:402)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:89)
	at com.google.appengine.tools.development.TimedFuture.get(TimedFuture.java:42)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:62)
	at com.google.appengine.tools.appstats.RecordingFuture.get(RecordingFuture.java:108)
	at com.google.appengine.tools.appstats.RecordingFuture.get(RecordingFuture.java:20)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:89)
	at com.google.appengine.api.datastore.AsyncDatastoreServiceImpl$7.get(AsyncDatastoreServiceImpl.java:406)
	at com.google.appengine.api.datastore.AsyncDatastoreServiceImpl$7.get(AsyncDatastoreServiceImpl.java:402)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:89)
	at com.googlecode.objectify.impl.ResultAdapter.now(ResultAdapter.java:34)
	at com.googlecode.objectify.util.ResultWrapper.translate(ResultWrapper.java:22)
	at com.googlecode.objectify.util.ResultWrapper.translate(ResultWrapper.java:10)
	at com.googlecode.objectify.util.ResultTranslator.nowUncached(ResultTranslator.java:21)
	at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
	at teammates.storage.api.EntitiesDb.deleteEntity(EntitiesDb.java:216)
	at teammates.logic.core.FeedbackResponsesLogic.deleteFeedbackResponseAndCascade(FeedbackResponsesLogic.java:682)
	at teammates.logic.core.FeedbackResponsesLogic.deleteFeedbackResponsesForStudentAndCascade(FeedbackResponsesLogic.java:746)
	at teammates.logic.core.StudentsLogic.deleteStudentCascade(StudentsLogic.java:476)
	at teammates.logic.core.StudentsLogic.deleteStudentCascade(StudentsLogic.java:467)
	at teammates.logic.core.StudentsLogic.deleteAllStudentsInCourse(StudentsLogic.java:462)
	at teammates.logic.api.Logic.deleteAllStudentsInCourse(Logic.java:1033)
	at teammates.ui.controller.InstructorCourseStudentDeleteAllAction.execute(InstructorCourseStudentDeleteAllAction.java:21)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:474)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:75)
	at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:50)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
	at teammates.ui.controller.AppstatsFilter.doFilter(AppstatsFilter.java:41)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:657)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:619)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:589)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:263)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by damithc** [comment]
Feedback from the user
>I noticed it would delete about 50-60 students at a time, but once it fell below 100 students the feature worked properly.

**Comment by jnisky** [comment]
This task cancelled error is a result of a timeout due to the inefficiency of the delete all students functionality right?

**Comment by jnisky** [comment]
Nvm. I've dived down the rabbit hole here for an hour and I see that this functionality might need to be handled outside the user request through a push task queue. This is occurring because GAE has a built in 30 second timeout on user requests. I see @whipermr5  has self assigned this issue. If it's ok with you John, I am going to see if I can implement a push queue. I'll let you know if I come up with anything. This is still your issue obv but I am curious about finding the bottom of this particular rabbit hole. So I will try fix it on my own and maybe learn a thing or two along the way. :)

**Comment by damithc** [comment]
@jnisky it is less risky if you attempt issues labelled as `d.Contributors` because they are the ones we have confirmed to be within the reach of a contributor who is relatively new to the codebase. All issues without `d.*` labels are potential rabbit holes. :-p

**Comment by jnisky** [comment]
Ok. Do you think I'm on the right path anyways? 
This is the line of code doing the actual deleting: ofy().delete().keys(getCourseStudentForEmailQuery(courseId, email).keys()).now();
found on line 440 in StudentsDb.java. 
and the solution is to implement a task queue with a worker class like this example: 
public class Worker extends HttpServlet {

  private static final Logger log = Logger.getLogger(Worker.class.getName());

  protected void doPost(HttpServletRequest request, HttpServletResponse response)
      throws ServletException, IOException {
    String key = request.getParameter("key");

    // Do something with key.
    // ...
  }
}
This example and the full documentation for java task queues can be found at this link: 
https://cloud.google.com/appengine/docs/standard/java/taskqueue/push/example

Thanks

**Comment by jnisky** [comment]
I got to line 440 of StudentsDb by chasing the deleteallstudents methods.

**Comment by whipermr5** [comment]
@jnisky Thanks for your suggestion! However, I believe the better way would be to queue deletion of multiple entities and delete them all at once, rather than calling `deleteStudent` multiple times (whether in a task or within the user request).

**Comment by xpdavid** [comment]
Sadly, V7 does not solve the problem. Batch deletion might help.

**Comment by wkurniawan07** [comment]
Batch deletion might help, but also observe that all entities with referential integrity (in particular feedback responses) will need to be deleted first in order to prevent dangling objects.

The best way moving forward should be:
1. User clicks "delete all students" for a given course
1. For each feedback session in the course, delete all feedback responses with batch deletion. This can either be sequential or parallel, and either way we can show progress bar to user as for how many sessions have been cleaned.
1. After all feedback responses are cleaned, delete all students with batch deletion. At this stage this will be very fast as there is no more cascade deletion necessary.
1. Show to user that all has been done

The back-end definitely cannot assume that (2) will be done before (3) so the cascade deletion logic needs to stay, however without anything to be cascade-deleted the process will be much faster.

**Comment by moziliar** [comment]
Regarding this issue, is it possible to mark the students as virtually deleted and run period task to cleanup? Would this be a better way to perform deletion than a blocking delete?

**Comment by rrtheonlyone** [comment]
> Regarding this issue, is it possible to mark the students as virtually deleted and run period task to cleanup? Would this be a better way to perform deletion than a blocking delete?

This will then require a modification to all our GET methods since we now need to check if the student is marked for deleted or not. It is possible but there are considerations.

**Comment by moziliar** [comment]
@rrtheonlyone noted. In a long run, it might amortize many things if we put delete tag in all objects; in short term, the shift has a large impact

**Comment by josiahkhoo** [comment]
Hello, is it okay if I work on this issue? 😀

**Comment by daongochieu2810** [comment]
@josiahkhoo sure please go ahead

**Comment by moziliar** [comment]
@daongochieu2810 @josiahkhoo I have a feeling this is pretty involved a topic, bearing in mind that we didn't proceed with the fix last semester due to the need to refactor the cascading deletion (per entity). Perhaps we can discuss more here first? 

This might interest you @rrtheonlyone
