### ISSUE TITLE
StudentFeedbackResultsPageUiTest: fix failure on live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8171]
Failed multiple times.
v6.0.1rc
Win10, Chrome

```
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at teammates.test.driver.HtmlHelper.assertSameHtml(HtmlHelper.java:95)
	at teammates.test.driver.HtmlHelper.assertSameHtml(HtmlHelper.java:63)
	at teammates.test.pageobjects.AppPage.verifyHtmlPart(AppPage.java:864)
	at teammates.test.pageobjects.AppPage.verifyHtmlMainContent(AppPage.java:916)
	at teammates.test.cases.browsertests.StudentFeedbackResultsPageUiTest.testAll(StudentFeedbackResultsPageUiTest.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```
![image](https://user-images.githubusercontent.com/1673303/33062125-285b3006-ced9-11e7-8ef8-625769661550.png)

**Comment by wkurniawan07** [comment]
Does this happen on the Java 8 version?

**Comment by damithc** [comment]
No, this is the v6.0.1rc version.

**Comment by wkurniawan07** [comment]
My concern was actually on whether the Java 8 version gives problems when tested against the live server. I presume it has not been tried yet?

**Comment by damithc** [comment]
> My concern was actually on whether the Java 8 version gives problems when tested against the live server. I presume it has not been tried yet?

Not yet. I need to set up the new project environment first. Will do over this weekend.

**Comment by damithc** [comment]
Also failing on v6.0.1 (java 8 version)

**Comment by damithc** [comment]
Did not fail at v6.3

**Comment by tshradheya** [comment]
Is this issue still relevant? The test is stable on development server

**Comment by damithc** [comment]
Looks like not failing anymore. Closing
