### ISSUE TITLE
Address regression in Cloud SDK 188.0.0

### ISSUE THREAD

**Issue by sukanta-27** [TEAMMATES/teammates#8414]
- **Operating System:** Windows 8.1
- **JDK Version:** 1.8
- **Eclipse / IntelliJ Version (if applicable):** Eclipse Oxygen 4.7
- **Firefox / Chrome Version (where applicable):** 

**What I was trying to do / What I need help with**

While working on #8408 I pushed a commit to the PR, and the Travis CI build failed with a error. (The full error message is given below in the comments)

**Attempts to resolve the problem:** ]closed and reopened the PR for Travis to run again, but it failed.
Also reverted the changes to check if it was due to the changes I recently made, but even after reverting the changes the build failed.

**Add:** I ran `npm run lint` and `gradlew.bat lint` on my local machine, both ran successfully.

**Comment by sukanta-27** [comment]
**The full message :**

```
Welcome to the Google Cloud SDK!
This will install all the core command line tools necessary for working with
the Google Cloud Platform.
Your current Cloud SDK version is: 188.0.0
Installing components from version: 188.0.0
┌────────────────────────────────────────────────────────────────────────────┐
│                    These components will be installed.                     │
├─────────────────────────────────────────────────────┬────────────┬─────────┤
│                         Name                        │  Version   │   Size  │
├─────────────────────────────────────────────────────┼────────────┼─────────┤
│ BigQuery Command Line Tool                          │     2.0.28 │ < 1 MiB │
│ BigQuery Command Line Tool (Platform Specific)      │     2.0.26 │ < 1 MiB │
│ Cloud SDK Core Libraries (Platform Specific)        │ 2017.09.15 │ < 1 MiB │
│ Cloud Storage Command Line Tool                     │       4.28 │ 3.3 MiB │
│ Cloud Storage Command Line Tool (Platform Specific) │       4.27 │ < 1 MiB │
│ Default set of gcloud commands                      │            │         │
│ gcloud cli dependencies                             │ 2017.10.20 │ 5.1 MiB │
└─────────────────────────────────────────────────────┴────────────┴─────────┘
For the latest full release notes, please visit:
  https://cloud.google.com/sdk/release_notes
╔════════════════════════════════════════════════════════════╗
╠═ Creating update staging area                             ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: BigQuery Command Line Tool                   ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: BigQuery Command Line Tool (Platform Spec... ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: Cloud SDK Core Libraries (Platform Specific) ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: Cloud Storage Command Line Tool              ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: Cloud Storage Command Line Tool (Platform... ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: Default set of gcloud commands               ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: gcloud cli dependencies                      ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Creating backup and activating new installation          ═╣
╚════════════════════════════════════════════════════════════╝
Performing post processing steps...failed.
Traceback (most recent call last):
  File "/home/travis/./google-cloud-sdk/bin/bootstrapping/install.py", line 214, in <module>
    main()
  File "/home/travis/./google-cloud-sdk/bin/bootstrapping/install.py", line 192, in main
    Install(pargs.override_components, pargs.additional_components)
  File "/home/travis/./google-cloud-sdk/bin/bootstrapping/install.py", line 134, in Install
    InstallOrUpdateComponents(to_install, update=update)
  File "/home/travis/./google-cloud-sdk/bin/bootstrapping/install.py", line 177, in InstallOrUpdateComponents
    ['--quiet', 'components', verb, '--allow-no-backup'] + component_ids)
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 823, in Execute
    self._HandleAllErrors(exc, command_path_string, specified_arg_names)
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 861, in _HandleAllErrors
    exceptions.HandleError(exc, command_path_string, self.__known_error_handler)
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 797, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 757, in Run
    resources = command_instance.Run(args)
  File "/home/travis/google-cloud-sdk/lib/surface/components/update.py", line 106, in Run
    version=args.version)
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 987, in Update
    self._PostProcess(snapshot=diff.latest)
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 1473, in _PostProcess
    err_func=log.file_only_logger.debug)
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/execution_utils.py", line 286, in Exec
    env = _GetToolEnv(env=env)
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/execution_utils.py", line 145, in _GetToolEnv
    env, p.EnvironmentName(), p.Get(required=False, validate=False))
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 1557, in Get
    required)
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 1856, in _GetProperty
    value = _GetPropertyWithoutDefault(prop, properties_file)
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 1894, in _GetPropertyWithoutDefault
    value = callback()
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 217, in GetAccount
    return c_gce.Metadata().DefaultAccount()
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce.py", line 85, in DefaultAccount
    http_errors_to_ignore=(404,))
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 289, in DecoratedFunction
    six.reraise(to_reraise[0], to_reraise[1], to_reraise[2])
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 159, in TryFunc
    return func(*args, **kwargs), None
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce.py", line 45, in _ReadNoProxyWithCleanFailures
    except urllib.request.HTTPError as e:
AttributeError: 'Module_six_moves_urllib_request' object has no attribute 'HTTPError'
The command "./google-cloud-sdk/install.sh --usage-reporting false --path-update false --command-completion false" failed and exited with 1 during .

Your build has been stopped.
```

**Comment by sukanta-27** [comment]
@damithc @wkurniawan07 @whipermr5 

I am not very familiar with build related issues as of now, but this error message states that `Your current Cloud SDK version is: 188.0.0` and the gcloud version on my system is `179.0.0`. Can an outdated sdk be the cause of this?

**Comment by whipermr5** [comment]
It seems to work now; perhaps there was a bug in the gcloud install script but it's been fixed.

**Comment by wkurniawan07** [comment]
It looks like some regression occurs in Cloud SDK 188.0.0 (<https://issuetracker.google.com/issues/73044966>). I'll do a quick fix for now and monitor that issue closely.
