### ISSUE TITLE
InstructorFeedbackResultsPageUiTest: fix failure against live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8429]
v6.2.0
Failed after repeated tries.
```
java.lang.AssertionError: Row expected to be missing found.

	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at teammates.test.pageobjects.InstructorFeedbackResultsPage.verifyRowMissing(InstructorFeedbackResultsPage.java:426)
	at teammates.test.cases.browsertests.InstructorFeedbackResultsPageUiTest.testFeedbackResponseCommentActions(InstructorFeedbackResultsPageUiTest.java:661)
	at teammates.test.cases.browsertests.InstructorFeedbackResultsPageUiTest.testBackEndActions(InstructorFeedbackResultsPageUiTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```

**Comment by sukanta-27** [comment]
Could not reproduce it locally. Is it something that is only occurs in staging server?

**Comment by damithc** [comment]
> Could not reproduce it locally. Is it something that is only occurs in staging server?

Yes, I believe so. Otherwise it should fail on Travis too.

**Comment by damithc** [comment]
Did not notice this at v6.3.0

**Comment by damithc** [comment]
Did not notice at v6.6.0
