### ISSUE TITLE
StudentHomePageUiTest: fix state leak

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8524]
v6.3.0, live server
StudentHomePageUiTest is failing due to a state leak from another test, most likely from StudentProfilePageUiTest.
Specifically, the course below is showing up in StudentHomePageUiTest

Taken from `StudentProfilePageUiTest.json`
```json
"SHomeUiT.CS2103": {
      "id": "SHomeUiT.CS2103",
      "name": "Software Engineering",
      "timeZone": "UTC"
    }
```
Location of the failure:
```
java.lang.AssertionError:  

	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at teammates.test.driver.HtmlHelper.assertSameHtml(HtmlHelper.java:95)
	at teammates.test.driver.HtmlHelper.assertSameHtml(HtmlHelper.java:63)
	at teammates.test.pageobjects.AppPage.verifyHtmlPart(AppPage.java:865)
	at teammates.test.pageobjects.AppPage.verifyHtmlMainContent(AppPage.java:917)
	at teammates.test.cases.browsertests.StudentHomePageUiTest.testContentAndLogin(StudentHomePageUiTest.java:86)
	at teammates.test.cases.browsertests.StudentHomePageUiTest.allTests(StudentHomePageUiTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```

![image](https://user-images.githubusercontent.com/1673303/36625788-2e95585c-1961-11e8-842e-abb79ce90908.png)

Probably the same student is used in both tests. May be delete courses of the student in concern during the setup phase?

On a related note, should not use the prefix `SHomeUiT.` in test data of `StudentProfilePageUiTest.json`. Instead, it should use something like `SProfileUiT.`

**Comment by wkurniawan07** [comment]
I have some spare time this weekend to look into this. If someone else wants to do it before me, please be welcome.

**Comment by tshradheya** [comment]
Ideally the `StudentProfilePageUiTest` and `StudentHomePageUiTest` should not have any state leak because the latter belongs to `sequential-ui-tests, right?

**Comment by damithc** [comment]
> Ideally the StudentProfilePageUiTest and StudentHomePageUiTest should not have any state leak because the latter belongs to sequential-ui-tests, right?

@tshradheya Ideally, no two tests should have any state leaks between them.  For sequential tests, it's enough if they clean up at the end so that no trace of it remains after the test is over. For parallel tests, whatever they do should not affect other tests even while the test is running.

In this case, you can start by running the two tests sequentially to see if one causes the other to fail.
