### ISSUE TITLE
Help Request: Configuration for rule "object-curly-newline" is invalid error

### ISSUE THREAD

**Issue by nidhi98gupta** [TEAMMATES/teammates#8616]
- **Commit SHA:** fa92b7fe8ed3abbd2dc7e029cc4fd2e60e5855fd
- **Operating System:** Ubuntu 17.10
- **JDK Version:** 1.8
- **Google Cloud SDK Version:** 186.0.0
- **Eclipse Version (if applicable):** 2017.3
- **Firefox Version (if applicable):** 46.0

**What I was trying to do / What I need help with**
I merged latest changes from master in #8550. As there were changes in static analysis test, CI tests resulted in failure. In order to pass CI tests, I fixed a minor lint error of my code related to curly braces and tried to run `npm run lint` which resulted in `Configuration for rule "object-curly-newline" is invalid:` error and build failure.

```

> @ lint /home/nidhi/teammates
> npm run lint:js && npm run lint:json && npm run lint:css && npm run lint:spaces


> @ lint:js /home/nidhi/teammates
> eslint *.js src/main/webapp/dev -c static-analysis/teammates-eslint.yml

/home/nidhi/teammates/static-analysis/teammates-eslint.yml:
	Configuration for rule "object-curly-newline" is invalid:
	Value {"ObjectExpression":{"minProperties":4,"multiline":true,"consistent":true},"ObjectPattern":{"minProperties":4,"multiline":true,"consistent":true},"ExportDeclaration":"always","ImportDeclaration":"always"} should be equal to one of the allowed values.
	Value {"ObjectExpression":{"minProperties":4,"multiline":true,"consistent":true},"ObjectPattern":{"minProperties":4,"multiline":true,"consistent":true},"ExportDeclaration":"always","ImportDeclaration":"always"} should NOT have additional properties.
	Value {"ObjectExpression":{"minProperties":4,"multiline":true,"consistent":true},"ObjectPattern":{"minProperties":4,"multiline":true,"consistent":true},"ExportDeclaration":"always","ImportDeclaration":"always"} should match exactly one schema in oneOf.
	Value {"ObjectExpression":{"minProperties":4,"multiline":true,"consistent":true},"ObjectPattern":{"minProperties":4,"multiline":true,"consistent":true},"ExportDeclaration":"always","ImportDeclaration":"always"} should NOT have additional properties.
	Value {"ObjectExpression":{"minProperties":4,"multiline":true,"consistent":true},"ObjectPattern":{"minProperties":4,"multiline":true,"consistent":true},"ExportDeclaration":"always","ImportDeclaration":"always"} should match exactly one schema in oneOf.

Error: /home/nidhi/teammates/static-analysis/teammates-eslint.yml:
	Configuration for rule "object-curly-newline" is invalid:
	Value {"ObjectExpression":{"minProperties":4,"multiline":true,"consistent":true},"ObjectPattern":{"minProperties":4,"multiline":true,"consistent":true},"ExportDeclaration":"always","ImportDeclaration":"always"} should be equal to one of the allowed values.
	Value {"ObjectExpression":{"minProperties":4,"multiline":true,"consistent":true},"ObjectPattern":{"minProperties":4,"multiline":true,"consistent":true},"ExportDeclaration":"always","ImportDeclaration":"always"} should NOT have additional properties.
	Value {"ObjectExpression":{"minProperties":4,"multiline":true,"consistent":true},"ObjectPattern":{"minProperties":4,"multiline":true,"consistent":true},"ExportDeclaration":"always","ImportDeclaration":"always"} should match exactly one schema in oneOf.
	Value {"ObjectExpression":{"minProperties":4,"multiline":true,"consistent":true},"ObjectPattern":{"minProperties":4,"multiline":true,"consistent":true},"ExportDeclaration":"always","ImportDeclaration":"always"} should NOT have additional properties.
	Value {"ObjectExpression":{"minProperties":4,"multiline":true,"consistent":true},"ObjectPattern":{"minProperties":4,"multiline":true,"consistent":true},"ExportDeclaration":"always","ImportDeclaration":"always"} should match exactly one schema in oneOf.

    at validateRuleOptions (/home/nidhi/teammates/node_modules/eslint/lib/config/config-validator.js:115:15)
    at Object.keys.forEach.id (/home/nidhi/teammates/node_modules/eslint/lib/config/config-validator.js:155:9)
    at Array.forEach (<anonymous>)
    at validateRules (/home/nidhi/teammates/node_modules/eslint/lib/config/config-validator.js:154:30)
    at Object.validate (/home/nidhi/teammates/node_modules/eslint/lib/config/config-validator.js:232:5)
    at loadFromDisk (/home/nidhi/teammates/node_modules/eslint/lib/config/config-file.js:507:19)
    at Object.load (/home/nidhi/teammates/node_modules/eslint/lib/config/config-file.js:550:20)
    at Config.loadSpecificConfig (/home/nidhi/teammates/node_modules/eslint/lib/config.js:139:46)
    at new Config (/home/nidhi/teammates/node_modules/eslint/lib/config.js:101:14)
    at new CLIEngine (/home/nidhi/teammates/node_modules/eslint/lib/cli-engine.js:420:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ lint:js: `eslint *.js src/main/webapp/dev -c static-analysis/teammates-eslint.yml`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ lint:js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nidhi/.npm/_logs/2018-03-09T11_28_08_961Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ lint: `npm run lint:js && npm run lint:json && npm run lint:css && npm run lint:spaces`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nidhi/.npm/_logs/2018-03-09T11_28_09_004Z-debug.log
``

**Comment by nidhi98gupta** [comment]
Update: This error occurs only on my system and not during Travis CI build. I tried updating npm but it didn't help.

**Comment by sukanta-27** [comment]
@nidhi98gupta Can you give the code snippet that you modified which lead to this error?

**Comment by sukanta-27** [comment]
@nidhi98gupta Did you follow [this](https://github.com/TEAMMATES/teammates/blob/master/docs/dependencies.md) after pulling the recent commits? I guess a `npm install` should solve this issue.

**Comment by nidhi98gupta** [comment]
@sukanta-27 I had previously tried `npm update` but that didn't work. `npm install` solved the issue. Thank you.:)
