### ISSUE TITLE
"Date in String is in wrong format" exception when running tests

### ISSUE THREAD

**Issue by Vaggelis-Malandrakis** [TEAMMATES/teammates#8644]
Hello,

I am a new contributor (at least I am trying) but I am facing a problem running the tests in Eclipse. I fixed the issue with the timezone format by putting `-Duser.timezone=UTC` at the run configurations but another one came up.

```
Cannot instantiate class teammates.test.cases.action.InstructorCourseStudentDetailsEditPageActionTest
at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:40)
at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:389)
at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:302)
at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:118)
at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:183)
at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:128)
at org.testng.TestRunner.initMethods(TestRunner.java:413)
at org.testng.TestRunner.init(TestRunner.java:239)
at org.testng.TestRunner.init(TestRunner.java:209)
at org.testng.TestRunner.<init>(TestRunner.java:164)
at org.testng.remote.support.RemoteTestNG6_5$1.newTestRunner(RemoteTestNG6_5.java:27)
at org.testng.remote.support.RemoteTestNG6_5$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_5.java:63)
at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:584)
at org.testng.SuiteRunner.init(SuiteRunner.java:159)
at org.testng.SuiteRunner.<init>(SuiteRunner.java:113)
at org.testng.TestNG.createSuiteRunner(TestNG.java:1274)
at org.testng.TestNG.createSuiteRunners(TestNG.java:1261)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1115)
at org.testng.TestNG.run(TestNG.java:1032)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:29)
... 21 more

Caused by: java.lang.RuntimeException: Failed to invoke teammates.common.datatransfer.attributes.StudentAttributes() with no args
at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:116)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
at com.google.gson.Gson.fromJson(Gson.java:888)
at com.google.gson.Gson.fromJson(Gson.java:853)
at com.google.gson.Gson.fromJson(Gson.java:802)
at teammates.common.util.JsonUtils.fromJson(JsonUtils.java:72)
at teammates.test.cases.BaseTestCase.loadDataBundle(BaseTestCase.java:69)
at teammates.test.cases.BaseTestCase.getTypicalDataBundle(BaseTestCase.java:61)
at teammates.test.cases.action.BaseActionTest.<init>(BaseActionTest.java:46)
at teammates.test.cases.action.InstructorCourseStudentDetailsEditPageActionTest.<init>(InstructorCourseStudentDetailsEditPageActionTest.java:16)
... 26 more

Caused by: java.lang.AssertionError: Date in String is in wrong format.
at teammates.common.util.Assumption.fail(Assumption.java:61)
at teammates.common.util.TimeHelper.parseInstant(TimeHelper.java:402)
at teammates.common.util.Const.<clinit>(Const.java:104)
at teammates.common.datatransfer.attributes.StudentAttributes.<init>(StudentAttributes.java:47)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:108)
... 40 more
```

Do you have any idea why is this happening?

Thank you for your time.

**Comment by darrenwee** [comment]
Hi! 

> I am a new contributor (at least I am trying) but I am facing a problem running the tests in Eclipse. I fixed the issue with the timezone format by putting "-Duser.timezone=UTC"

Can you remove the `-Duser.timezone="UTC"` and post the errors you get? Might be an issue similar to #8444.

Are you on Windows or Linux or Mac?

**Comment by Vaggelis-Malandrakis** [comment]
I removed it but the same error appears.

I am running on Windows and I pulled the latest commit.

I don't know if this helps but my system locale after typing this `systeminfo | findstr ;` command to cmd appears to be:
`System Locale:             el;Ελληνικά`
`Input Locale:                el;Ελληνικά`

**Comment by darrenwee** [comment]
I wasn't able to reproduce the issue by setting my system locale to Greek (`el_GR`), so it's probably not related to that. The failing tests I got were all different and due to comparison failures.

Did you follow the instructions for both [setting up dev environment](https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md), and [setting up eclipse](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-setup.md#eclipse-ide)?

Try running the tests using the gradle wrapper from a command prompt, and see if you get the same failures.
```bash
./gradlew.bat test --tests teammates.test.cases.action.*
# i'm not sure if you need to escape the asterisk on windows
./gradlew.bat test --tests teammates.test.cases.action.\*
```

**Comment by Vaggelis-Malandrakis** [comment]
I followed the instructions step by step and all my actions were the same as they were described.
I ran these command (they have the same result): Build failed

![build fails](https://user-images.githubusercontent.com/22797140/37472810-a056e24e-2875-11e8-9d7a-b534ff496bcd.jpg)

**Comment by tran-tien-dat** [comment]
Hi @Vaggelis-Malandrakis, can you try writing a Java program and execute the following (you will need to import the relevant packages):

```Java
ZonedDateTime.parse("1970-12-31 12:00 AM +0000", DateTimeFormatter.ofPattern("yyyy-MM-dd h:mm a Z"));
```

**Comment by Vaggelis-Malandrakis** [comment]
Hi @tran-tien-dat.

I did it and I am getting this exception:

`Exception in thread "main" java.time.format.DateTimeParseException: Text '1970-12-31 12:00 AM +0000' could not be parsed at index 17`
`at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)`
`at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)`
`at java.time.ZonedDateTime.parse(ZonedDateTime.java:597)`
`at maven.Test.main(Test.java:9)`

**Comment by tran-tien-dat** [comment]
I suppose that in your locale el;Ελληνικά, you don't use AM/PM to denote time in the before or after noon? @darrenwee is there a way to change Java's Locale to English?

**Comment by darrenwee** [comment]
I think specifying `-Duser.language=en` for the JVM should work. You can add this to the run config in eclipse.

@Vaggelis-Malandrakis try this snippet to confirm:
```
ZonedDateTime.parse("1970-12-31 12:00 AM +0000", DateTimeFormatter.ofPattern("yyyy-MM-dd h:mm a Z", new Locale("en", "US")));
```

**Comment by Vaggelis-Malandrakis** [comment]
Sorry for the delay.

I added these to the JVM and it worked!
Also the snippet runs.
All the tests were completed but I got 19 fails. Is this caused from this alteration to the JVM configuration?

![failed tests](https://user-images.githubusercontent.com/22797140/37486185-6e1a6956-2896-11e8-9b3b-254f965463d0.jpg)

**Comment by damithc** [comment]
Closing due to inactivity. Feel free to reopen.
