### ISSUE TITLE
Help Request: "Execution failed for task ':localTests'"

### ISSUE THREAD

**Issue by lowell1** [TEAMMATES/teammates#8699]
Hi,
I just installed teammates for the first time and I'm able to view the website by going to localhost:8080, but when I try to run the command  "sudo ./gradlew localTests", it fails a task and shows an error message. Sorry if I'm doing something wrong but this is my first time using this and I have no idea what this error means. Any help at all would be greatly appreciated. Here is the error:

> Task :localTests

teammates.test.cases.browsertests.MashupPageUiTest.baseClassSetup FAILED
    java.lang.ExceptionInInitializerError
        Caused by: org.openqa.selenium.WebDriverException

2 tests completed, 1 failed, 1 skipped

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':localTests'.
> There were failing tests

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
5 actionable tasks: 2 executed, 3 up-to-date
Problems handling incoming cache access requests.
java.lang.IllegalArgumentException: Unexpected protocol version 0 received in lock contention notification message
        at org.gradle.cache.internal.locklistener.FileLockCommunicator.decode(FileLockCommunicator.java:131)
        at org.gradle.cache.internal.locklistener.FileLockCommunicator.decodeLockId(FileLockCommunicator.java:91)
        at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler$1.doRun(DefaultFileLockContentionHandler.java:109)
        at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler$1.run(DefaultFileLockContentionHandler.java:94)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)

**Comment by craaaa** [comment]
Hi @lowell1, it appears that Selenium is unable to start. Have you followed our development guidelines and ensured that your `test.properties` file is correctly configured? You can refer [here](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#testing) for help.

**Comment by lowell1** [comment]
Thank you. I was able to make the error go away by using a virtual machine and the Eclipse IDE instead of Ubuntu on Windows and using chrome instead of firefox but now I'm getting another error: 

org.openqa.selenium.WebDriverException: unknown error: failed to change window state to maximized, current state is normal


My version of Chrome is Version 63.0.3239.108 (Official Build) (64-bit) and I'm using ChromeDriver 2.36. It seems strange because after it opens chrome it does change the window to maximized. Also, could it be a problem that I am trying to use a virtual machine for this? Thank you for your time!

**Comment by lowell1** [comment]
I'm using chromedriver on a virtual machine instead of bash on windows and it works now. Thank you for your time!
