### ISSUE TITLE
InstructorFeedbackAddAction: NullPointerException

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8788]
v6.5.0

Noticed this in the live server. Only one occurrence so far but may be worth looking into 

>Error Message: teammates.common.util.Logger severe: Unexpected exception caught by ControllerServlet : 
java.lang.NullPointerException
at teammates.common.datatransfer.attributes.FeedbackSessionAttributes.isPublished(FeedbackSessionAttributes.java:342)
at teammates.ui.pagedata.PageData.getInstructorPublishedStatusForFeedbackSession(PageData.java:632)
at teammates.ui.template.FeedbackSessionsForm.getFormForNewFs(FeedbackSessionsForm.java:169)
at teammates.ui.pagedata.InstructorFeedbackSessionsPageData.buildBasicForm(InstructorFeedbackSessionsPageData.java:155)
at teammates.ui.pagedata.InstructorFeedbackSessionsPageData.buildNewForm(InstructorFeedbackSessionsPageData.java:137)
at teammates.ui.pagedata.InstructorFeedbackSessionsPageData.init(InstructorFeedbackSessionsPageData.java:57)
at teammates.ui.pagedata.InstructorFeedbackSessionsPageData.initWithoutHighlightedRow(InstructorFeedbackSessionsPageData.java:75)
at teammates.ui.controller.InstructorFeedbackAddAction.execute(InstructorFeedbackAddAction.java:99)
at teammates.ui.controller.Action.executeAndPostProcess(Action.java:476)
at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:75)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)

**Comment by damithc** [comment]
More data of the request:
```
https://teammatesv4.appspot.com/page/instructorFeedbackAdd:{instructions::<p>asdf</p>, sessionVisibleFromButton::custom, endtime::24, visibletime::24, graceperiod::15, starttime::24, startdate::, fsname::, visibledate::asdf, token::A79643C3C78889228BB1785171302333, enddate::, sendreminderemail::FEEDBACK_CLOSING//FEEDBACK_PUBLISHED, publishtime::24, publishdate::asf, resultsVisibleFromButton::custom, courseid::CSC495, user::abc@ncsu.edu, fstype::TEAMEVALUATION}
```

**Comment by whipermr5** [comment]
Manifestation of #8597.

**Comment by whipermr5** [comment]
Upon further investigation, more related to #8293. The implementation did not take into account that when building a new form (to show the partially completed form), the feedback session attributes can contain invalid data.

**Comment by damithc** [comment]
How bad is it? Need an urgent hotfix?

**Comment by whipermr5** [comment]
It can only be triggered by manually entering an invalid date into the published date field (but yes, entering arbitrary strings into the input is now allowed because of #8332 so it's quite easy to do so).

**Comment by whipermr5** [comment]
Done. Released as [V6.5.1](https://github.com/TEAMMATES/teammates/releases/tag/V6.5.1).

**Comment by damithc** [comment]
Deployed
