### ISSUE TITLE
InstructorFeedbackResultsPageUiTest.testBackEndActions failing in live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8909]
v6.6.0

	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at teammates.test.driver.HtmlHelper.assertSameHtml(HtmlHelper.java:92)
	at teammates.test.driver.HtmlHelper.assertSameHtml(HtmlHelper.java:60)
	at teammates.test.pageobjects.AppPage.verifyHtmlPart(AppPage.java:1166)
	at teammates.test.pageobjects.AppPage.verifyHtmlMainContent(AppPage.java:1218)
	at teammates.test.cases.browsertests.InstructorFeedbackResultsPageUiTest.testFeedbackResponseCommentActions(InstructorFeedbackResultsPageUiTest.java:765)
	at teammates.test.cases.browsertests.InstructorFeedbackResultsPageUiTest.testBackEndActions(InstructorFeedbackResultsPageUiTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

![image](https://user-images.githubusercontent.com/1673303/41574044-5c5badc6-73b2-11e8-89a2-09a8736f98e3.png)

**Comment by xpdavid** [comment]
It seems that the callback function of the richTextEditor is not correctly triggered. The logic of the callback function is if the content is empty, then add `empty` class.

Cannot reproduce it in my own staging server. Not sure if it can be reproduced again in the LIVE staging server.

**Comment by tshradheya** [comment]
This test fails due to the extra `empty` class even on thr development server. But it happens very rarely and hence tough to duplicate and be sure of the reason

**Comment by damithc** [comment]
Still failing at v6.7.0, for the same reason

**Comment by damithc** [comment]
Did not fail at v6.11.0 when using chrome.

**Comment by damithc** [comment]
Did not fail at v6.16.0
