### ISSUE TITLE
InstructorCourseDetailsPageUiTest.testRemindAction failing on live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8957]
v6.7.0
Possibly a case of not using a real student account; error not caught by CI because email testing is omitted in dev server
>java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
	at teammates.test.cases.BaseTestCase.assertTrue(BaseTestCase.java:127)
	at teammates.test.cases.browsertests.InstructorCourseDetailsPageUiTest.testRemindAction(InstructorCourseDetailsPageUiTest.java:183)
	at teammates.test.cases.browsertests.InstructorCourseDetailsPageUiTest.allTests(InstructorCourseDetailsPageUiTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

**Comment by damithc** [comment]
> Possibly a case of not using a real student account; error not caught by CI because email testing is omitted in dev server

I could be wrong on this.

**Comment by tshradheya** [comment]
@LiHaoTan Could this be because now we changed to using `RetryManager` in #8862. I am assuming the `maxDelayInSeconds` which was set to `5` might be too less?

**Comment by damithc** [comment]
@tshradheya Can you get it to work on your staging server? I tried increasing the delay to 25 seconds, but still failed. Furthermore, the test doesn't seem to wait the specified seconds anyway; may be retry manager is not used for this case?

**Comment by damithc** [comment]
> @damithc would an arbitrarily large number work? I remember Sendgrid takes a very long time to send emails.

The test doesn't seem to wait at all. The email was received within a few seconds (I monitored the email account) but the test failed anyway, although I set the delay to be 25 seconds.

**Comment by damithc** [comment]
Just now I tried with 120 seconds (modified line 279 as follows), and the test failed within 57 seconds :-p

`RetryManager retryManager = new RetryManager(120);`

**Comment by tshradheya** [comment]
Investigating that whether its due to maybe the third party dependencies upgrade we did for 6.7.0

**Comment by damithc** [comment]
Still failing at v6.8.0

**Comment by damithc** [comment]
Failing at v6.9.0

**Comment by damithc** [comment]
Still failing at v6.10.0

**Comment by damithc** [comment]
Still failing at v6.11.0

**Comment by damithc** [comment]
Still failing at v6.12.1

**Comment by damithc** [comment]
failing at v6.13

**Comment by xpdavid** [comment]
Will be fixed in #9171 :)
