### ISSUE TITLE
ProfilesDbTest.testUpdateStudentProfile failing on live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8958]
v6.7.0

>java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
	at teammates.test.cases.BaseTestCase.assertTrue(BaseTestCase.java:127)
	at teammates.test.cases.storage.ProfilesDbTest.testUpdateProfileSuccessNoChangesToProfile(ProfilesDbTest.java:102)
	at teammates.test.cases.storage.ProfilesDbTest.testUpdateStudentProfile(ProfilesDbTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

**Comment by tshradheya** [comment]
Note:

https://github.com/TEAMMATES/teammates/blob/bc27ba33b60db40f900e59eca9d8fa8cabdb9dd0/src/test/java/teammates/test/cases/storage/ProfilesDbTest.java#L96-L103

The function `doesFileExistInGcs()` called in line 102 is returning false due to the BLOB_NOT_FOUND error returned by line 39 of the code below

https://github.com/TEAMMATES/teammates/blob/bc27ba33b60db40f900e59eca9d8fa8cabdb9dd0/src/main/java/teammates/common/util/GoogleCloudStorageHelper.java#L37-L44



The image(actually a .txt file) is stored in the bucket on gcp. While uploading and checking the image the `encoded_gs_key:...` value is the same.

**Comment by damithc** [comment]
Any idea why this started failing all of a sudden? We didn't have this failure in previous versions.

**Comment by tshradheya** [comment]
@TEAMMATES/seniordevs Need some input. 

When this test is run on the live server, is it supposed to create the profile picture on the specified bucket on GCP or is it just that the file is created on the `WEB-INF/appengine-generated`? 

On running the test between the commits, I noticed that after #8910 got merged, the image started to be saved in GCP bucket, which seems wrong for the test. (Before that commit it was stored in `WEB-INF/appengine-generated`.

I think its due to the fact that the environment is being set and hence causing to to be saved to GCP bucket. 

https://github.com/TEAMMATES/teammates/blob/bc27ba33b60db40f900e59eca9d8fa8cabdb9dd0/src/test/java/teammates/test/cases/BaseTestCaseWithMinimalGaeEnvironment.java#L23-L33

**Comment by tshradheya** [comment]
Ensured that https://github.com/TEAMMATES/teammates/issues/8958#issuecomment-404451309 is the reason for the test to fail.

Removing this function causes the test to pass.
https://github.com/TEAMMATES/teammates/blob/bc27ba33b60db40f900e59eca9d8fa8cabdb9dd0/src/test/java/teammates/test/cases/BaseTestCaseWithMinimalGaeEnvironment.java#L23-L33

However, we cannot remove the function because it ensures that our `isDevSever()` function works properly. 

I was thinking of some other way than `SystemProperty`  in which we can set the test to know the environment and so that it doesn't affect other tests. @xpdavid any suggestions?

**Comment by xpdavid** [comment]
Maybe we are in the wrong way -- Maybe we should not set the SystemProperty to Production.

When I look back to the original issue, I think the problem might be associated with the way we compare test.

For example here:
https://github.com/TEAMMATES/teammates/blob/05460192e9ca6f1626584d338838661486f5a7cf/src/test/java/teammates/test/driver/EmailChecker.java#L60-L62

We should inject `Config.APP_URL` instead.

Maybe for all test except end2end test, we shall use `Config.APP_URL` as the expected URL. For end2end test, using `TestProperties.TEAMMATES_URL` if necessary or just compare the params and path (Like in #8910).

**Comment by tshradheya** [comment]
> Maybe we should not set the SystemProperty to Production.

The main reason for this was for `isDevServer()` to work properly. 

https://github.com/TEAMMATES/teammates/blob/05460192e9ca6f1626584d338838661486f5a7cf/src/main/java/teammates/common/util/Config.java#L124-L126


Otherwise the `Config.APP_URL` will always be `http`

**Comment by xpdavid** [comment]
> Otherwise the Config.APP_URL will always be http

That's totally OK for integration test. So, I am saying when we compare the expected and actual result. We shall not use `TestProperties.TEAMMATES_URL` in the integration test. Use Config.APP_URL will pass the test.

**Comment by tshradheya** [comment]
@xpdavid  Are you suggesting a PR like this https://github.com/tshradheya/teammates/pull/6 ?

It works well on the Dev server as shown in travis.
I have run a few tests(EmailGenerator, AdminHomePageUiTest, ProfilesDbTest) on live server which failed in 6.6.0(and were fixed in 6.7.0) and they now pass on live server.

**Comment by xpdavid** [comment]
Yes :)
