### ISSUE TITLE
FeedbackResponseCommentSearchTest failing on live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9022]
java.lang.AssertionError: 
Expected :0
Actual   :1

	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)
	at teammates.test.cases.BaseTestCase.assertEquals(BaseTestCase.java:151)
	at teammates.test.cases.search.FeedbackResponseCommentSearchTest.verifySearchResults(FeedbackResponseCommentSearchTest.java:95)
	at teammates.test.cases.search.FeedbackResponseCommentSearchTest.allTests(FeedbackResponseCommentSearchTest.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

**Comment by xpdavid** [comment]
The test is not stable. Can pass after several run. Need investigation. @tshradheya

**Comment by xpdavid** [comment]
It seems that search index doesn't conform strong consistency. We could add `ThreadHelper.waitBriefly();` to wait briefly before issuing the verification query.

**Comment by damithc** [comment]
Did not fail at v6.11.0 when using chrome.

**Comment by xpdavid** [comment]
Will be fixed in #9104

**Comment by xpdavid** [comment]
Fixed in #9102
