### ISSUE TITLE
FeedbackConstSumOptionQuestionUiTest failing on live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9057]
v6.10.0

I'm running tests in Windows, against the live server

java.lang.AssertionError: 
Expected :["Choice 3","Choice 1","Choice 2","Choice 4"]
Actual   :["Choice 1","Choice 2","Choice 3","Choice 4"]
 <Click to see difference>

	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at teammates.test.cases.BaseTestCase.assertEquals(BaseTestCase.java:143)
	at teammates.test.cases.browsertests.FeedbackConstSumOptionQuestionUiTest.testReorderOptions(FeedbackConstSumOptionQuestionUiTest.java:285)
	at teammates.test.cases.browsertests.FeedbackConstSumOptionQuestionUiTest.testEditPage(FeedbackConstSumOptionQuestionUiTest.java:58)
	at teammates.test.cases.browsertests.FeedbackConstSumOptionQuestionUiTest.allTests(FeedbackConstSumOptionQuestionUiTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

**Comment by damithc** [comment]
And `FeedbackMsqQuestionUiTest`

**Comment by damithc** [comment]
One more: `FeedbackRankQuestionUiTest`

**Comment by mg14777** [comment]
@damithc Sir, this issue is probably due to the drag and drop action not being properly simulated in Selenium. The final technique I used was [this](https://github.com/TEAMMATES/teammates/pull/8889/commits/a12fe2adf39cc800a43ee4249fe6d638c59575e5) which seemed to work fine in Chrome on windows. Would you mind telling which browser you're using for this ?

**Comment by damithc** [comment]
> Would you mind telling which browser you're using for this ?

I'm using Firefox

**Comment by damithc** [comment]
I'll try FF v46.0.1 and failing that, Chrome.

**Comment by mg14777** [comment]
@damithc I just ran `FeedbackRankQuestionUiTest` and `FeedbackConstSumOptionQuestionUiTest` against my staging server https://teammates-mudit.appspot.com/ using Firefox v43.0.1 and the tests seem to pass. Are you able to drag the options manually ? If not can you do `npm run build` again and then try to ensure its picking up the changes ?

**Comment by damithc** [comment]
> Are you able to drag the options manually ?

Yes, it works when I try manually.

**Comment by xpdavid** [comment]
@mg14777 Maybe due to the resolution or layout of elements.

Guess: Extreme case, the menu bar overlay the target position and release doesn't work?
![image](https://user-images.githubusercontent.com/13977235/44297558-1d35da80-a306-11e8-91b9-f3bb902cb0a5.png)
![image](https://user-images.githubusercontent.com/13977235/44297577-73a31900-a306-11e8-90e3-25ed4d516f0c.png)


https://github.com/TEAMMATES/teammates/blob/56190f722d79c647e426db2a739d82f6fc6cd5b5/src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java#L1479-L1483

Maybe you should scroll the `draggedOptionElement` to the center before drag it?

If you resize the browser and you can reproduce the error.

**Comment by xpdavid** [comment]
Now these test also failing on master Appveyor build (I think for the same reason).

https://ci.appveyor.com/project/damithc/teammates/branch/master
