### ISSUE TITLE
InstructorSearch: Error searching terms found in deleted sessions

### ISSUE THREAD

**Issue by joanneong** [TEAMMATES/teammates#9146]
- **Environment**: `master` branch at commit f725f72 

**Steps to reproduce**
1. Create any feedback session
2. Add a response to the session
3. Comment on the response as an instructor
4. Try searching for keywords in the comment by checking the "Questions, responses, comments on responses" box
5. Search is successful
6. Delete the feedback session (either soft-delete or full delete)
7. Try searching again like step 4
8. See an error page

**Expected behaviour**
Either no results should be displayed, or results for other existing sessions should be displayed.

**Actual behaviour**
An error page appears instead. The log message states:
```
INFO: Query: courseId:(CS1000 OR CS4444 OR test.exa-demo) AND searchableText:("good")
Sep 22, 2018 2:29:39 AM teammates.common.util.Logger info
INFO: Trying to get non-existent Session: Test/CS1000
Sep 22, 2018 2:29:39 AM teammates.common.util.Logger info
INFO: Query: courseId:(CS1000 OR CS4444 OR test.exa-demo) AND searchableText:("good")
Sep 22, 2018 2:29:39 AM teammates.common.util.Logger severe
SEVERE: Unexpected exception caught by ControllerServlet : 
java.lang.NullPointerException
	at teammates.ui.pagedata.InstructorSearchPageData.createFeedbackSessionRows(InstructorSearchPageData.java:121)
	at teammates.ui.pagedata.InstructorSearchPageData.setSearchFeedbackSessionDataTables(InstructorSearchPageData.java:101)
	at teammates.ui.pagedata.InstructorSearchPageData.init(InstructorSearchPageData.java:64)
	at teammates.ui.controller.InstructorSearchPageAction.execute(InstructorSearchPageAction.java:72)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:476)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:75)
	at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:50)
        ...
```

**Additional info**
I was testing another feature on another branch prior to this, so that might have affected the data stored. Hence, it would be good if someone else can also test and verify this.

**Comment by damithc** [comment]
@dalessr can take a look?

**Comment by xpdavid** [comment]
Fixed in `release` and changes merged back to `master`
