### ISSUE TITLE
Exception occured while performing http://teammatesv4.appspot.com/auto/feedbackSessionClosedReminders

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9160]
v6.11.0 (6.12.1 deployed but not activated yet)
I'm getting a few of these from the live server
```
Error Message: teammates.common.util.Logger severe: Exception occured while performing http://teammatesv4.appspot.com/auto/feedbackSessionClosedReminders|||
java.lang.NullPointerException
at teammates.storage.entity.FeedbackSession.convertFieldsToUtcIfRequired(FeedbackSession.java:169)
at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)


at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.googlecode.objectify.impl.translate.LifecycleMethod.execute(LifecycleMethod.java:28)
at com.googlecode.objectify.impl.translate.ClassPopulator$2.run(ClassPopulator.java:128)
at com.googlecode.objectify.impl.translate.LoadContext.done(LoadContext.java:81)
at com.googlecode.objectify.impl.LoadEngine$1.postExecuteHook(LoadEngine.java:154)
at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:33)
at com.googlecode.objectify.impl.Round$1.nowUncached(Round.java:71)
at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
at com.googlecode.objectify.util.ResultNowFunction.apply(ResultNowFunction.java:20)
at com.googlecode.objectify.util.ResultNowFunction.apply(ResultNowFunction.java:9)
at com.google.common.collect.Iterators$5.transform(Iterators.java:757)
at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
at com.googlecode.objectify.impl.Chunk.next(Chunk.java:27)
at com.googlecode.objectify.impl.Chunk.next(Chunk.java:10)
at com.google.common.collect.MultitransformedIterator.next(MultitransformedIterator.java:66)
at com.google.common.collect.Iterators$PeekingImpl.peek(Iterators.java:1143)
at com.googlecode.objectify.impl.ChunkingIterator.hasNext(ChunkingIterator.java:52)
at com.google.common.collect.Iterators.addAll(Iterators.java:373)
at com.google.common.collect.Lists.newArrayList(Lists.java:165)
at com.googlecode.objectify.util.MakeListResult.translate(MakeListResult.java:22)
at com.googlecode.objectify.util.MakeListResult.translate(MakeListResult.java:12)
at com.googlecode.objectify.util.ResultTranslator.nowUncached(ResultTranslator.java:21)
at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
at com.googlecode.objectify.util.ResultProxy.invoke(ResultProxy.java:34)
at com.sun.proxy.$Proxy19.iterator(Unknown Source)
at teammates.storage.api.EntitiesDb.makeAttributes(EntitiesDb.java:300)
at teammates.storage.api.FeedbackSessionsDb.getFeedbackSessionsPossiblyNeedingClosedEmail(FeedbackSessionsDb.java:178)
at teammates.logic.core.FeedbackSessionsLogic.getFeedbackSessionsClosedWithinThePastHour(FeedbackSessionsLogic.java:1471)
at teammates.logic.api.Logic.getFeedbackSessionsClosedWithinThePastHour(Logic.java:2322)
at teammates.ui.automated.FeedbackSessionClosedRemindersAction.execute(FeedbackSessionClosedRemindersAction.java:30)

-----

Error Message: teammates.common.util.Logger severe: Exception occured while performing http://teammatesv4.appspot.com/auto/feedbackSessionClosedReminders|||

at teammates.storage.api.FeedbackSessionsDb.getFeedbackSessionsPossiblyNeedingClosedEmail(FeedbackSessionsDb.java:178)
at teammates.logic.core.FeedbackSessionsLogic.getFeedbackSessionsClosedWithinThePastHour(FeedbackSessionsLogic.java:1471)
at teammates.logic.api.Logic.getFeedbackSessionsClosedWithinThePastHour(Logic.java:2322)
at teammates.ui.automated.FeedbackSessionClosedRemindersAction.execute(FeedbackSessionClosedRemindersAction.java:30)
```

**Comment by wkurniawan07** [comment]
@xpdavid remnants of #9118?

@damithc that exception-invoking function (`convertFieldsToUtcIfRequired`) is decommissioned in the latest code, so it's very likely a case of improper handling of new data schema. But @xpdavid should confirm.

**Comment by xpdavid** [comment]
I guess the error occur after pre-deployment check of V6.12.1 (UI test has been run)?

If this is true, the error is as expected.

In the new code in V6.12.1, `isTimeStoredInUtc` is removed and test data will be stored in new format. Because V6.12.1 hasn't been rolled out yet, the new data is handled by the old code (for cron task and task queue) and this will cause error.

The impact is kind of big actually as all closed email won't be sent because of this error.

The fix is to roll out V6.12.1 or manually delete test data introduced in new format (more troublesome and tedious to do it).

**Comment by damithc** [comment]
I had to enable v6.12.1 although I haven't completed its live testing :-p No recurrence of the problem since then.
On a related note, v6.12.1 is a 'no going back' version i.e., cannot be rolled back. Such versions should be minimized. At the same time, we should avoid the possibility that live testing of an upcoming version breaks the current live system.

**Comment by xpdavid** [comment]
> On a related note, v6.12.1 is a 'no going back' version i.e., cannot be rolled back.

Will document properly in the `teammates-ops` on how to avoid this.

**Comment by wkurniawan07** [comment]
> On a related note, v6.12.1 is a 'no going back' version i.e., cannot be rolled back.

If the exception is caused by test data, it cannot really be said that it is a no-going-back version. It just means, as I said, "a case of improper handling of new data schema".

**Comment by damithc** [comment]
> If the exception is caused by test data, it cannot really be said that it is a no-going-back version. It just means, as I said, "a case of improper handling of new data schema".

I see. I assumed we cannot rollback to v6.11 once v6.12 has been used by some users. Isn't that the case? A change is data scheme usually result in such a no-going-back version; it's just that we need to minimize such versions.

**Comment by xpdavid** [comment]
> I assumed we cannot rollback to v6.11 once v6.12 has been used by some users. Isn't that the case?

Yes. However, we can put some efforts to make the adjacent versions "rollbackable"/interchangeable.

**Comment by xpdavid** [comment]
Data migration policy added in https://github.com/TEAMMATES/teammates-ops/blob/master/best-practices.md .
