### ISSUE TITLE
FeedbackRankQuestionUiTest failing on live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9167]
v6.12.1
Failing for both Firefox and Chrome, after multiple tries

java.lang.AssertionError: 
Expected :["Choice 3","Choice 1","Choice 2","Choice 4"]
Actual   :["Choice 1","Choice 2","Choice 3","Choice 4"]

	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at teammates.test.cases.BaseTestCase.assertEquals(BaseTestCase.java:143)
	at teammates.test.cases.browsertests.FeedbackRankQuestionUiTest.testReorderOptions(FeedbackRankQuestionUiTest.java:647)
	at teammates.test.cases.browsertests.FeedbackRankQuestionUiTest.testEditPage(FeedbackRankQuestionUiTest.java:318)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

teammates.test.cases.browsertests.FeedbackRankQuestionUiTest completed

**Comment by damithc** [comment]
And these too: FeedbackConstSumOptionQuestionUiTest, FeedbackMsqQuestionUiTest

**Comment by xpdavid** [comment]
@mg14777 Tests are not stable in LIVE testing.

**Comment by damithc** [comment]
Did not fail at v6.16.0
