### ISSUE TITLE
Admin, instructor and student page login error.

### ISSUE THREAD

**Issue by bhumisaxena0223** [TEAMMATES/teammates#9187]
* Operating System: MacBook Air
* JDK Version: 8
* Eclipse / IntelliJ Version (if applicable): Photon
* Firefox / Chrome Version (where applicable): FF 44.1

What I was trying to do / What I need help with?

I followed the guidelines to setup the project and I am now stuck with passing the tests.
I am working on the issue. But recently these errors came up. I tried many ways to solve them. But couldn’t find any answer.
I have tried these ways to solve it.
1. I uninstalled the FF version and downloaded the 44.0.1 version to run again and tried to stop and start server again.
2. Configure test.properties , web.xml, build.properties and checked all the dependencies.
3. Find the solution in existing issues but failed.

Error: May be the Current browser is not able to find the #Path or address.
There are 7 errors right now.
![screenshot 2018-10-11 11 46 15 png](https://user-images.githubusercontent.com/41126620/46822476-365c8400-cda9-11e8-9bbb-d9ede2a41fcc.png)

The errors :
1. teammates.test.cases.browsertests.AdminHomePageUiTest
       This is the Failure Exception:
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at teammates.test.pageobjects.AppPage.getNewPageInstance(AppPage.java:168)
	at teammates.test.pageobjects.AppPage.changePageType(AppPage.java:196)
	at teammates.test.pageobjects.InstructorHomePage.clickCourseEditLink(InstructorHomePage.java:113)
	at teammates.test.cases.browsertests.AdminHomePageUiTest.testCreateInstructorAction(AdminHomePageUiTest.java:193)
	at teammates.test.cases.browsertests.AdminHomePageUiTest.testAll(AdminHomePageUiTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at teammates.test.pageobjects.AppPage.getNewPageInstance(AppPage.java:164)
	... 24 more
Caused by: java.lang.IllegalStateException: Not in the correct page!
	at teammates.test.pageobjects.AppPage.<init>(AppPage.java:145)
	at teammates.test.pageobjects.InstructorCourseEditPage.<init>(InstructorCourseEditPage.java:73)
	... 29 more
 
2. teammates.test.cases.browsertests.StudentProfilePageUiTest
       This is the Failure Exception:  
       java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

3. teammates.test.cases.browsertests.InstructorCourseEditPageUiTest
        This is the Failure Exception:
	 java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

4. teammates.test.cases.browsertests.InstructorCoursesPageUiTest
	This is the Failure Exception:
  	java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

5. teammates.test.cases.browsertests.InstructorHomePageUiTest
	This is the Failure Exception:
	 java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

(In this 5 tests the error is same but not able to fine the solution.)

6. teammates.test.cases.browsertests.InstructorFeedbackResultsPageResponseCommentUiTest
	This is the Failure Exception:
	org.openqa.selenium.WebDriverException: e is undefined
Command duration or timeout: 14 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'apples-MacBook-Air.local', ip: '192.168.0.106', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_171'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=44.0.1, platform=MAC, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 24757994-8808-534e-873f-f3414171ff7a

7. teammates.test.cases.browsertests.InstructorStudentRecordsPageUiTest
	This is the Failure Exception:
	org.openqa.selenium.WebDriverException: e is undefined
Command duration or timeout: 14 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'apples-MacBook-Air.local', ip: '192.168.0.106', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_171'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=44.0.1, platform=MAC, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 24757994-8808-534e-873f-f3414171ff7a

Please help me I tried to solve using many source online and using project guidelines too. But couldn’t find the solution.

**Comment by bhumisaxena0223** [comment]
No, I tried to run each test individually and tried to login manually but same error every time.

**Comment by xpdavid** [comment]
What error do you see why you login it manually?

**Comment by bhumisaxena0223** [comment]
I run it manually, giving same error.

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at teammates.test.pageobjects.AppPage.getNewPageInstance(AppPage.java:168)
	at teammates.test.pageobjects.AppPage.changePageType(AppPage.java:196)
	at teammates.test.pageobjects.InstructorHomePage.clickCourseEditLink(InstructorHomePage.java:113)
	at teammates.test.cases.browsertests.AdminHomePageUiTest.testCreateInstructorAction(AdminHomePageUiTest.java:193)
	at teammates.test.cases.browsertests.AdminHomePageUiTest.testAll(AdminHomePageUiTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at teammates.test.pageobjects.AppPage.getNewPageInstance(AppPage.java:164)
	... 24 more
Caused by: java.lang.IllegalStateException: Not in the correct page!
	at teammates.test.pageobjects.AppPage.<init>(AppPage.java:145)
	at teammates.test.pageobjects.InstructorCourseEditPage.<init>(InstructorCourseEditPage.java:73)
	... 29 more

**Comment by xpdavid** [comment]
> Not in the correct page!

It says not in the correct page. So what page are you in?

**Comment by xpdavid** [comment]
>  InstructorCourseEditpage it gives error:

You can get the detailed error in the log. Can you post the log here also?

**Comment by bhumisaxena0223** [comment]
@xpdavid Thank you for telling this, I think I found the error, will try to solve it soon as I can.
I found the error why I am not in correct page. 
Here is the Error log:
![screenshot 2018-10-15 13 19 52](https://user-images.githubusercontent.com/41126620/46936621-89ba2500-d07c-11e8-9466-6f2141b93eb0.png)
