### ISSUE TITLE
teammatesv7: Unable to do set up project due to webpack issues

### ISSUE THREAD

**Issue by joanneong** [TEAMMATES/teammates#9270]
- **Operating System:** macOS Mojave (10.14.1)
- **JDK Version:** 1.8.0_144
- **Node.js Version:** v11.4.0
- **Google Cloud SDK Version:** 219.0.1
- **Eclipse / IntelliJ Version (if applicable):** Intellij IDEA Ultimate 2017.3

**What I was trying to do / What I need help with**
I am trying to get started with frontend migration on the `teammatesv7` branch. I have done the following:
- Set up a clean copy  of `teammates` locally
- Track the `teammatesv7` branch by default
- Follow the set up instructions in the [documentation](https://github.com/TEAMMATES/teammates/blob/teammatesv7/docs/setting-up.md)

However, I faced two problems:
1. Angular CLI framework was not automatically detected by Intellij
2. Running `npm run start` will give an error message:
```
Cannot find module 'webpack'
Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/Joanne/Documents/teammates/node_modules/@angular-devkit/build-webpack/src/webpack/index.js:6:17)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```

**Attempts to resolve the problem**
In fact, when I first ran `npm install`, I got the following message:
```
npm WARN @angular-devkit/build-webpack@0.8.8 requires a peer of webpack@^4.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN @fimbul/ymir@0.15.0 requires a peer of tsutils@>2.29.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@6.2.8 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.3 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.
npm WARN circular-dependency-plugin@5.0.2 requires a peer of webpack@>=4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN file-loader@1.1.11 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN html-webpack-plugin@3.2.0 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN istanbul-instrumenter-loader@3.0.1 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN less-loader@4.1.0 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mini-css-extract-plugin@0.4.4 requires a peer of webpack@^4.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@7.1.0 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stats-webpack-plugin@0.6.2 requires a peer of webpack@>=1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN uglifyjs-webpack-plugin@1.3.0 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN url-loader@1.1.2 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.4.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@3.1.10 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-subresource-integrity@1.1.0-rc.4 requires a peer of webpack@^1.12.11 || ~2 || ~3 || ~4 but none is installed. You must install peer dependencies yourself.
```

After running `npm run start` and seeing that message, I did `npm install webpack@4.16.4` (version from `package-lock.json`. Then, when I ran `npm run start`, I got another error message:
```
13% building modules 25/26 modules 1 active …Documents/teammates/src/web/styles.scss✖ ｢wdm｣: Error: No module factory available for dependency type: ContextElementDependency
    at addDependency (/Users/Joanne/Documents/teammates/node_modules/webpack/lib/Compilation.js:669:12)
    at iterationOfArrayCallback (/Users/Joanne/Documents/teammates/node_modules/webpack/lib/Compilation.js:186:3)
    at addDependenciesBlock (/Users/Joanne/Documents/teammates/node_modules/webpack/lib/Compilation.js:687:5)
    at iterationOfArrayCallback (/Users/Joanne/Documents/teammates/node_modules/webpack/lib/Compilation.js:186:3)
    at addDependenciesBlock (/Users/Joanne/Documents/teammates/node_modules/webpack/lib/Compilation.js:690:5)
    at Compilation.processModuleDependencies (/Users/Joanne/Documents/teammates/node_modules/webpack/lib/Compilation.js:698:4)
    at afterBuild (/Users/Joanne/Documents/teammates/node_modules/webpack/lib/Compilation.js:830:15)
    at buildModule.err (/Users/Joanne/Documents/teammates/node_modules/webpack/lib/Compilation.js:874:11)
    at callback (/Users/Joanne/Documents/teammates/node_modules/webpack/lib/Compilation.js:611:5)
    at module.build.error (/Users/Joanne/Documents/teammates/node_modules/webpack/lib/Compilation.js:651:12)
    at resolveDependencies (/Users/Joanne/Documents/teammates/node_modules/webpack/lib/ContextModule.js:282:4)
    at ContextModule.result.resolveDependencies (/Users/Joanne/Documents/teammates/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:504:25)
    at ContextModule.build (/Users/Joanne/Documents/teammates/node_modules/webpack/lib/ContextModule.js:203:8)
    at Compilation.buildModule (/Users/Joanne/Documents/teammates/node_modules/webpack/lib/Compilation.js:616:10)
    at factory.create (/Users/Joanne/Documents/teammates/node_modules/webpack/lib/Compilation.js:857:14)
    at hooks.afterResolve.callAsync (/Users/Joanne/Documents/teammates/node_modules/webpack/lib/ContextModuleFactory.js:163:16)
/Users/Joanne/Documents/teammates/node_modules/neo-async/async.js:14
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (/Users/Joanne/Documents/teammates/node_modules/neo-async/async.js:14:11)
    at /Users/Joanne/Documents/teammates/node_modules/neo-async/async.js:2813:7
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
```

[Googling the error message](https://stackoverflow.com/questions/46809626/angular-no-module-factory-available-for-dependency-type-contextelementdependenc), it seems like I should either modify `package.json` or adjust my `webpack` versions. But when I did `npm ls webpack`, I only see one version of `webpack`:
```
/Users/Joanne/Documents/teammates
├─┬ @angular-devkit/build-angular@0.8.8
│ └── webpack@4.16.4 
└── webpack@4.16.4
```

What could be the issue here? Sorry for being unable to make it for the meeting previously :(

**Comment by joanneong** [comment]
@wkurniawan07 suggested doing `npm install -D @angular-devkit/build-angular` and the matter has been resolved! Thanks!

**Comment by wkurniawan07** [comment]
Glad that it resolves the matter but it's still a curious case... you shouldn't need to do anything other than `npm install` to get all the necessary tools.

**Comment by LiHaoTan** [comment]
I didn't look at this issue in detail but I noticed that the IntelliJ version used is rather old, relative to Angular being much newer. I'm not sure if it actually affects anything since I didn't look at both IntelliJ and Angular's changelogs but that may be a possible reason why.
