### ISSUE TITLE
e2e tests failing

### ISSUE THREAD

**Issue by RonMosenzon** [TEAMMATES/teammates#9736]
Help Request: e2e tests failing (seems like they are trying to use Firefox even though I am using chrome?)

- **Commit SHA:** 2fec5bf8221e7a2a49beb54cb88f166373e68186
- **Operating System:** Windows 10
- **JDK Version:** 1.8.0_211
- **Node.js Version:** v10.15.3
- **Google Cloud SDK Version:** 246.0.0
- **Eclipse / IntelliJ Version (if applicable):** Oxygen.3a Release (4.7.3a)
- **Firefox / Chrome Version (if applicable):** chrome version 74.0.3729.169

Keep in mind I am new to programming and have no experience with any of this, so I could have made some really stupid mistake somewhere.

**What I was trying to do / What I need help with**
I am trying to run the tests from console as the development guideline document says, the component tests work fine, but the e2e tests almost all fail.
I have my chromedriver executable at the folder C:\webdrivers and I have this path in the test.properties file
![before test](https://user-images.githubusercontent.com/50575801/58745833-204a2380-845f-11e9-855f-7933cf139641.PNG)
**note:** I tried multiple versions of the path for test.chromedriver.path such as"C:/webdrivers/chromedriver" and "C:/webdrivers/chromedrive.exe" and none of them worked.
I have "Disable cache" option checked in chrome settings, and I have both front-end and back-end dev-servers running (I stop and rerun them every time I run the tests).
Yet when I run the tests I get this:

```To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.4.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Task :e2eTestTry1

e2e-tests > e2e-tests > teammates.e2e.cases.util.TestNgXmlTest > checkTestsInTestNg PASSED

e2e-tests > e2e-tests > teammates.e2e.cases.util.TestPropertiesTest > testContent PASSED

e2e-tests > e2e-tests > teammates.e2e.cases.e2e.TimezoneSyncerTest > baseClassSetup FAILED
    org.openqa.selenium.WebDriverException

e2e-tests > e2e-tests > teammates.e2e.cases.e2e.AdminHomePageE2ETest > baseClassSetup FAILED
    org.openqa.selenium.WebDriverException

e2e-tests > e2e-tests > teammates.e2e.cases.e2e.SystemErrorEmailReportE2ETest > testAll PASSED

e2e-tests > e2e-tests > teammates.e2e.cases.e2e.StudentProfilePageE2ETest > baseClassSetup FAILED
    org.openqa.selenium.WebDriverException

e2e-tests > e2e-tests > teammates.e2e.cases.e2e.StudentHomePageE2ETest > baseClassSetup FAILED
    org.openqa.selenium.WebDriverException

e2e-tests > e2e-tests > teammates.e2e.cases.e2e.StudentCourseDetailsPageE2ETest > baseClassSetup FAILED
    org.openqa.selenium.WebDriverException

14 tests completed, 5 failed, 6 skipped
There were failing tests

> Task :e2eTestTry2

Failed suite [e2e-tests] > e2e-tests(failed) > teammates.e2e.cases.e2e.AdminHomePageE2ETest > baseClassSetup FAILED
    org.openqa.selenium.WebDriverException

Failed suite [e2e-tests] > e2e-tests(failed) > teammates.e2e.cases.e2e.StudentProfilePageE2ETest > baseClassSetup FAILE
    org.openqa.selenium.WebDriverException

Failed suite [e2e-tests] > e2e-tests(failed) > teammates.e2e.cases.e2e.StudentCourseDetailsPageE2ETest > baseClassSetup FAILED
    org.openqa.selenium.WebDriverException

Failed suite [e2e-tests] > e2e-tests(failed) > teammates.e2e.cases.e2e.TimezoneSyncerTest > baseClassSetup FAILED
    org.openqa.selenium.WebDriverException

Failed suite [e2e-tests] > e2e-tests(failed) > teammates.e2e.cases.e2e.StudentHomePageE2ETest > baseClassSetup FAILED
    org.openqa.selenium.WebDriverException

11 tests completed, 5 failed, 6 skipped
There were failing tests

> Task :e2eTestTry3

Failed suite [Failed suite [e2e-tests]] > e2e-tests(failed)(failed) > teammates.e2e.cases.e2e.StudentProfilePageE2ETest > baseClassSetup FAILED
    org.openqa.selenium.WebDriverException

Failed suite [Failed suite [e2e-tests]] > e2e-tests(failed)(failed) > teammates.e2e.cases.e2e.StudentCourseDetailsPageE2ETest > baseClassSetup FAILED
    org.openqa.selenium.WebDriverException

Failed suite [Failed suite [e2e-tests]] > e2e-tests(failed)(failed) > teammates.e2e.cases.e2e.TimezoneSyncerTest > baseClassSetup FAILED
    org.openqa.selenium.WebDriverException

Failed suite [Failed suite [e2e-tests]] > e2e-tests(failed)(failed) > teammates.e2e.cases.e2e.AdminHomePageE2ETest > baseClassSetup FAILED
    org.openqa.selenium.WebDriverException

Failed suite [Failed suite [e2e-tests]] > e2e-tests(failed)(failed) > teammates.e2e.cases.e2e.StudentHomePageE2ETest > baseClassSetup FAILED
    org.openqa.selenium.WebDriverException

11 tests completed, 5 failed, 6 skipped
There were failing tests

> Task :e2eTestTry4

org.gradle.internal.serialize.PlaceholderException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: WIN10
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-P2N8951', ip: '10.0.0.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_211'
Driver info: driver.version: FirefoxDriver
        at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:100)
        at java.util.Optional.orElseGet(Optional.java:267)
        at org.openqa.selenium.firefox.FirefoxOptions.getBinary(FirefoxOptions.java:216)
        at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:187)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
        at teammates.e2e.pageobjects.Browser.createWebDriver(Browser.java:128)
        at teammates.e2e.pageobjects.Browser.<init>(Browser.java:56)
        at teammates.e2e.pageobjects.BrowserPool.requestInstance(BrowserPool.java:72)
        at teammates.e2e.pageobjects.BrowserPool.getBrowser(BrowserPool.java:43)
        at teammates.e2e.cases.e2e.BaseE2ETestCase.prepareBrowser(BaseE2ETestCase.java:40)
        at teammates.e2e.cases.e2e.BaseE2ETestCase.baseClassSetup(BaseE2ETestCase.java:36)
        ...

Failed suite [Failed suite [Failed suite [e2e-tests]]] > e2e-tests(failed)(failed)(failed) > teammates.e2e.cases.e2e.AdminHomePageE2ETest > baseClassSetup FAILED
    org.openqa.selenium.WebDriverException

org.gradle.internal.serialize.PlaceholderException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: WIN10
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-P2N8951', ip: '10.0.0.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_211'
Driver info: driver.version: FirefoxDriver
        at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:100)
        at java.util.Optional.orElseGet(Optional.java:267)
        at org.openqa.selenium.firefox.FirefoxOptions.getBinary(FirefoxOptions.java:216)
        at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:187)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
        at teammates.e2e.pageobjects.Browser.createWebDriver(Browser.java:128)
        at teammates.e2e.pageobjects.Browser.<init>(Browser.java:56)
        at teammates.e2e.pageobjects.BrowserPool.requestInstance(BrowserPool.java:72)
        at teammates.e2e.pageobjects.BrowserPool.getBrowser(BrowserPool.java:43)
        at teammates.e2e.cases.e2e.BaseE2ETestCase.prepareBrowser(BaseE2ETestCase.java:40)
        at teammates.e2e.cases.e2e.BaseE2ETestCase.baseClassSetup(BaseE2ETestCase.java:36)
        ...

Failed suite [Failed suite [Failed suite [e2e-tests]]] > e2e-tests(failed)(failed)(failed) > teammates.e2e.cases.e2e.StudentCourseDetailsPageE2ETest > baseClassSetup FAILED
    org.openqa.selenium.WebDriverException

org.gradle.internal.serialize.PlaceholderException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: WIN10
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-P2N8951', ip: '10.0.0.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_211'
Driver info: driver.version: FirefoxDriver
        at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:100)
        at java.util.Optional.orElseGet(Optional.java:267)
        at org.openqa.selenium.firefox.FirefoxOptions.getBinary(FirefoxOptions.java:216)
        at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:187)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
        at teammates.e2e.pageobjects.Browser.createWebDriver(Browser.java:128)
        at teammates.e2e.pageobjects.Browser.<init>(Browser.java:56)
        at teammates.e2e.pageobjects.BrowserPool.requestInstance(BrowserPool.java:72)
        at teammates.e2e.pageobjects.BrowserPool.getBrowser(BrowserPool.java:43)
        at teammates.e2e.cases.e2e.BaseE2ETestCase.prepareBrowser(BaseE2ETestCase.java:40)
        at teammates.e2e.cases.e2e.BaseE2ETestCase.baseClassSetup(BaseE2ETestCase.java:36)
        ...

Failed suite [Failed suite [Failed suite [e2e-tests]]] > e2e-tests(failed)(failed)(failed) > teammates.e2e.cases.e2e.StudentProfilePageE2ETest > baseClassSetup FAILED
    org.openqa.selenium.WebDriverException

org.gradle.internal.serialize.PlaceholderException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: WIN10
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-P2N8951', ip: '10.0.0.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_211'
Driver info: driver.version: FirefoxDriver
        at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:100)
        at java.util.Optional.orElseGet(Optional.java:267)
        at org.openqa.selenium.firefox.FirefoxOptions.getBinary(FirefoxOptions.java:216)
        at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:187)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
        at teammates.e2e.pageobjects.Browser.createWebDriver(Browser.java:128)
        at teammates.e2e.pageobjects.Browser.<init>(Browser.java:56)
        at teammates.e2e.pageobjects.BrowserPool.requestInstance(BrowserPool.java:72)
        at teammates.e2e.pageobjects.BrowserPool.getBrowser(BrowserPool.java:43)
        at teammates.e2e.cases.e2e.BaseE2ETestCase.prepareBrowser(BaseE2ETestCase.java:40)
        at teammates.e2e.cases.e2e.BaseE2ETestCase.baseClassSetup(BaseE2ETestCase.java:36)
        ...

Failed suite [Failed suite [Failed suite [e2e-tests]]] > e2e-tests(failed)(failed)(failed) > teammates.e2e.cases.e2e.TimezoneSyncerTest > baseClassSetup FAILED
    org.openqa.selenium.WebDriverException

org.gradle.internal.serialize.PlaceholderException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: WIN10
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-P2N8951', ip: '10.0.0.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_211'
Driver info: driver.version: FirefoxDriver
        at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:100)
        at java.util.Optional.orElseGet(Optional.java:267)
        at org.openqa.selenium.firefox.FirefoxOptions.getBinary(FirefoxOptions.java:216)
        at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:187)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
        at teammates.e2e.pageobjects.Browser.createWebDriver(Browser.java:128)
        at teammates.e2e.pageobjects.Browser.<init>(Browser.java:56)
        at teammates.e2e.pageobjects.BrowserPool.requestInstance(BrowserPool.java:72)
        at teammates.e2e.pageobjects.BrowserPool.getBrowser(BrowserPool.java:43)
        at teammates.e2e.cases.e2e.BaseE2ETestCase.prepareBrowser(BaseE2ETestCase.java:40)
        at teammates.e2e.cases.e2e.BaseE2ETestCase.baseClassSetup(BaseE2ETestCase.java:36)
        ...

Failed suite [Failed suite [Failed suite [e2e-tests]]] > e2e-tests(failed)(failed)(failed) > teammates.e2e.cases.e2e.StudentHomePageE2ETest > baseClassSetup FAILED
    org.openqa.selenium.WebDriverException

11 tests completed, 5 failed, 6 skipped

> Task :e2eTestTry4 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':e2eTestTry4'.
> There were failing tests

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
16 actionable tasks: 13 executed, 3 up-to-date
```

**and my test.properties file gets reset to this:**

![after test](https://user-images.githubusercontent.com/50575801/58746142-7620ca80-8463-11e9-917f-99f4a2a77494.PNG)

**note:** the first time I ran the tests I did not notice the "test.selenium.browser" field so I ran the tests with the test.properties file like in this picture, maybe that has something to do with it resetting the file to this state?

**Attempts to resolve the problem**
I tried running failed tests and I'm actually not sure what it did? the only output it gave on the console is:
```
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.4.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

BUILD SUCCESSFUL in 3s
5 actionable tasks: 5 up-to-date
```
and the file where the results can be viewed at is just:
![failed tests](https://user-images.githubusercontent.com/50575801/58746645-1c230380-8469-11e9-88e3-3688e3a5b68d.PNG)

I tried running component tests again just to make sure they still work, all but one passed, I'm not sure why this one fails now but I don't think it's relevant.

I'm running the tests from console because when I try to run the tests from eclipse I get a different issue where it doesn't seem to run the tests at all, it gives the error "Error: Could not find or load main class org.testng.remote.RemoteTestNG" and just sits at 0/0 tests. This happens with both component tests and e2e tests.

**Comment by xpdavid** [comment]
Hi @RonMosenzon , This is where the (browser) driver will be initialised. https://github.com/TEAMMATES/teammates/blob/f5f03a070890e1608c7dbe51eac5de9097913fe2/src/e2e/java/teammates/e2e/pageobjects/Browser.java#L104 You may want to check whether ChromeDriver is initialised or not.

**Comment by RonMosenzon** [comment]
Thanks a lot, looking at the code there a bit I found my mistake, I was editing the file "teammates/build/resources/test/test.properties" instead of "teammates/src/e2e/resources/test.properties".
