### ISSUE TITLE
Hourly email sending causes 'GC overhead limit exceeded' error

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9936]
v6.16.3 (the current live version)

I've been getting similar errors during December/January period although this is an off-peak period. A few per day. Usually connected with an hourly task such as sending reminders.

>Error Message: teammates.common.util.Logger severe: Exception occured while performing http://teammatesv4.appspot.com/auto/feedbackSessionPublishedReminders|||
java.lang.OutOfMemoryError: GC overhead limit exceeded
at java.time.ZoneRegion.ofId(ZoneRegion.java:126)
at java.time.ZoneId.of(ZoneId.java:411)
at java.time.ZoneId.of(ZoneId.java:359)
at teammates.storage.api.CoursesDb.makeAttributes(CoursesDb.java:148)
at teammates.storage.api.CoursesDb.makeAttributes(CoursesDb.java:28)
at teammates.storage.api.EntitiesDb.makeAttributesOrNull(EntitiesDb.java:266)
at teammates.storage.api.EntitiesDb.makeAttributesOrNull(EntitiesDb.java:261)
at teammates.storage.api.CoursesDb.getCourse(CoursesDb.java:58)
at teammates.logic.core.CoursesLogic.getCourse(CoursesLogic.java:118)
at teammates.logic.core.FeedbackSessionsLogic.getFeedbackSessionsWhichNeedAutomatedPublishedEmailsToBeSent(FeedbackSessionsLogic.java:1003)
at teammates.logic.api.Logic.getFeedbackSessionsWhichNeedAutomatedPublishedEmailsToBeSent(Logic.java:2071)
at teammates.ui.automated.FeedbackSessionPublishedRemindersAction.execute(FeedbackSessionPublishedRemindersAction.java:25)
at teammates.ui.automated.AutomatedServlet.doPost(AutomatedServlet.java:46)
at teammates.ui.automated.AutomatedServlet.doGet(AutomatedServlet.java:24)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)

**Comment by xpdavid** [comment]
#9943 has a temp fix while we don't know whether the issue will come again. Let's leave it here and prioritize for V7 first. In addition, this issue is also relevant in V7 and one should at least apply the fix in #9943 for V7.

**Comment by wkurniawan07** [comment]
Closing as this has been fixed
